import type { Metadata } from 'next'
import { getTranslations } from 'next-intl/server'
import { Body, Heading, Li, Ul } from '@/components/ui/typography'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { POLICY_LAST_UPDATED_DISPLAY } from '@/lib/consent'
import {
  LEGAL_ENTITY_ADDRESS,
  LEGAL_ENTITY_NAME,
  LEGAL_ENTITY_REGISTRY_CODE,
  PRIVACY_EMAIL,
  PRIVACY_EMAIL_HREF,
} from '@/lib/support'

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations('meta.legal.privacy')
  return {
    title: t('title'),
    description: t('description'),
  }
}

// "Last updated" derives from POLICY_LAST_UPDATED (src/lib/consent.ts) —
// the single source of truth, bumped alongside CURRENT_TERMS_VERSION.
const LAST_UPDATED = POLICY_LAST_UPDATED_DISPLAY

interface Processor {
  name: string
  role: string
  dataCategories: string
  region: string
  transferBasis: string
  dpaUrl: string
  note?: string
}

/**
 * Source of truth: `compliance/README.md` (DPA table, signed under Honkadori
 * OÜ — HON-459). LOUD RULE: when any new vendor that processes user data is
 * added anywhere in the codebase, add a row here AND update
 * `compliance/README.md` in the same PR. Region strings are exact on purpose
 * — "EU (Frankfurt)", not "Europe".
 */
const PROCESSORS: Processor[] = [
  {
    name: 'Anthropic, PBC',
    role: 'AI meal planning (LLM)',
    dataCategories: 'Prompts (household preferences, allergens, dietary data) and AI output',
    region: 'US',
    transferBasis: 'EU SCCs Module 2 + UK Addendum + EU-US DPF',
    dpaUrl: 'https://www.anthropic.com/legal/data-processing-addendum',
  },
  {
    name: 'Resend (Plus Five, Inc.)',
    role: 'Transactional email',
    dataCategories: 'Email address, message metadata',
    region: 'US',
    transferBasis: 'EU SCCs Module 2 + UK SCCs + EU-US DPF',
    dpaUrl: 'https://resend.com/legal/dpa',
  },
  {
    name: 'Vercel Inc.',
    role: 'Hosting',
    dataCategories: 'Request metadata, application logs',
    region: 'US/EU',
    transferBasis: 'EU SCCs (2021) Module 2 + UK IDTA',
    dpaUrl: 'https://vercel.com/legal/dpa',
  },
  {
    name: 'Neon (a Databricks company)',
    role: 'Database',
    dataCategories: 'All user records',
    region: 'EU (Frankfurt); importer Databricks, Inc. (US)',
    transferBasis: 'EU SCCs Modules 2/3 + UK Addendum + Swiss addendum',
    dpaUrl: 'https://neon.com/dpa',
  },
  {
    name: 'PostHog, Inc.',
    role: 'Product analytics + error tracking',
    dataCategories: 'Usage events, device info',
    region: 'EU (Frankfurt); processor PostHog, Inc. (US)',
    transferBasis: 'EU-US DPF + EU SCCs Module 2 + UK IDTA + Swiss addendum',
    dpaUrl: 'https://posthog.com/dpa',
    note: 'Active only after you accept analytics cookies.',
  },
]

function Section({
  id,
  title,
  children,
}: {
  id?: string
  title: string
  children: React.ReactNode
}) {
  return (
    <section id={id} className="mt-10 flex flex-col gap-3">
      <Heading variant="h2">{title}</Heading>
      {children}
    </section>
  )
}

export default function PrivacyPage() {
  return (
    <>
      <div className="flex flex-col gap-4">
        <Heading>Privacy policy</Heading>
        <Body variant="muted">Last updated: {LAST_UPDATED}</Body>
        <Body variant="lead">
          Wobblepot is an AI-powered meal planning app for households. This policy explains what
          personal data we collect, why, who processes it for us, how long we keep it, and the
          rights you have over it.
        </Body>
      </div>

      <Section title="The short version">
        <Ul>
          <Li>
            <Body>
              We collect what the app needs to plan meals for your household — your account details,
              household preferences, allergens, and pantry — and nothing else.
            </Body>
          </Li>
          <Li>
            <Body>
              Meal plans are generated by AI: your household preferences, allergens, and dietary
              data are sent to Anthropic for that purpose.
            </Body>
          </Li>
          <Li>
            <Body>We never sell your data, and analytics only runs if you opt in.</Body>
          </Li>
          <Li>
            <Body>
              You can export your data or delete your account at any time; deleted accounts are
              purged within 30 days.
            </Body>
          </Li>
        </Ul>
      </Section>

      <Section title="Who we are">
        <Body>
          The data controller is {LEGAL_ENTITY_NAME}, an Estonian private limited company, registry
          code {LEGAL_ENTITY_REGISTRY_CODE}, registered at {LEGAL_ENTITY_ADDRESS}. Wobblepot is the
          trade name {LEGAL_ENTITY_NAME} operates under.
        </Body>
        <Body>
          For anything related to your personal data, contact{' '}
          <a className="underline" href={PRIVACY_EMAIL_HREF}>
            {PRIVACY_EMAIL}
          </a>
          .
        </Body>
      </Section>

      <Section title="What data we collect">
        <Ul>
          <Li>
            <Body>Account: email address, name, and a hashed password.</Body>
          </Li>
          <Li>
            <Body>
              Household: household members and their preferences, allergens, and dietary
              restrictions. Member profiles may describe people other than the account holder,
              including children.
            </Body>
          </Li>
          <Li>
            <Body>Meals: AI-generated meal plans, recipes, swaps, and preparation tips.</Body>
          </Li>
          <Li>
            <Body>Pantry: your pantry inventory and shopping lists.</Body>
          </Li>
          <Li>
            <Body>
              Usage analytics and error reports — only if you accept analytics cookies (see{' '}
              <a className="underline" href="#cookies">
                Cookies
              </a>
              ).
            </Body>
          </Li>
        </Ul>
      </Section>

      <Section title="Why we process it">
        <Ul>
          <Li>
            <Body>
              <strong>Contract performance</strong> (GDPR Art. 6(1)(b)): running your account,
              generating meal plans, managing your pantry and shopping lists — the service you
              signed up for.
            </Body>
          </Li>
          <Li>
            <Body>
              <strong>Consent</strong> (Art. 6(1)(a)): product analytics and error tracking, which
              stay off until you accept analytics cookies. You can withdraw at any time from the
              cookie settings in the footer.
            </Body>
          </Li>
          <Li>
            <Body>
              <strong>Legitimate interests</strong> (Art. 6(1)(f)): keeping the service secure —
              rate limiting, abuse prevention, and operational logging.
            </Body>
          </Li>
        </Ul>
      </Section>

      <Section title="AI processing">
        <Body>
          Meal-plan generation, swap suggestions, and preparation tips are produced by a large
          language model operated by Anthropic. To generate them, we transmit your household
          preferences, allergens, and member dietary data to Anthropic. The AI output (meal plans,
          tips) is stored with your household. Anthropic processes this data as our processor under
          the agreement listed below and does not use it to train models.
        </Body>
      </Section>

      <Section title="Who processes data for us">
        <Body>
          We use five processors. All five involve a transfer to the United States, covered by the
          safeguards listed for each. We have a data processing agreement with every one of them.
        </Body>
        <Table containerLabel="Processors">
          <TableHeader>
            <TableRow>
              <TableHead>Processor</TableHead>
              <TableHead className="whitespace-normal">Role + data</TableHead>
              <TableHead className="whitespace-normal">Region</TableHead>
              <TableHead className="whitespace-normal">Transfer safeguards</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {PROCESSORS.map((p) => (
              <TableRow key={p.name}>
                <TableHead scope="row" className="align-top font-medium whitespace-normal">
                  <a className="underline" href={p.dpaUrl}>
                    {p.name}
                  </a>
                </TableHead>
                <TableCell className="align-top whitespace-normal">
                  {p.role} — {p.dataCategories}
                  {p.note ? ` ${p.note}` : ''}
                </TableCell>
                <TableCell className="align-top whitespace-normal">{p.region}</TableCell>
                <TableCell className="align-top whitespace-normal">{p.transferBasis}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
        <Body variant="muted">
          Each processor name links to the vendor&apos;s data processing agreement.
        </Body>
      </Section>

      <Section title="How long we keep data">
        <Ul>
          <Li>
            <Body>
              Account data: if you delete your account, everything is purged within 30 days of the
              request. During that window you can change your mind by emailing{' '}
              <a className="underline" href={PRIVACY_EMAIL_HREF}>
                {PRIVACY_EMAIL}
              </a>
              .
            </Body>
          </Li>
          <Li>
            <Body>
              Database backups: our database keeps a 24-hour point-in-time-recovery window, so
              backup copies of deleted data clear automatically within 24 hours.
            </Body>
          </Li>
          <Li>
            <Body>Application logs: runtime logs are kept for 1 day, build logs for 7 days.</Body>
          </Li>
          <Li>
            <Body>
              Transactional email records: delivery metadata is retained for roughly 30 days by our
              email provider.
            </Body>
          </Li>
          <Li>
            <Body>
              Sign-in sessions: rotating 7-day lifetime, refreshed while you use the app; expired
              sessions are invalid immediately.
            </Body>
          </Li>
          <Li>
            <Body>AI usage records: kept on a 12-month rolling window for cost control.</Body>
          </Li>
          <Li>
            <Body>
              Active account data (meal plans, pantry, preferences): kept for as long as your
              account is active.
            </Body>
          </Li>
        </Ul>
      </Section>

      <Section title="Your rights">
        <Body>Under the GDPR (and UK GDPR) you can:</Body>
        <Ul>
          <Li>
            <Body>
              <strong>Access and export</strong> your data — download a machine-readable copy at{' '}
              {/* Plain <a download>, NOT next/link: this is a file-download
                  Route Handler. <Link> would SPA-navigate instead of
                  downloading, and its viewport prefetch would silently run
                  the export and burn a daily rate-limit slot. Mirrors
                  profile/page.tsx. */}
              <a className="underline" href="/api/auth/user/export" download>
                /api/auth/user/export
              </a>{' '}
              while signed in (Art. 15 and 20).
            </Body>
          </Li>
          <Li>
            <Body>
              <strong>Rectify</strong> anything inaccurate — most data is editable in the app; for
              the rest, email us (Art. 16).
            </Body>
          </Li>
          <Li>
            <Body>
              <strong>Erase</strong> your account and data (Art. 17) — see the retention section
              above for the 30-day window.
            </Body>
          </Li>
          <Li>
            <Body>
              <strong>Object</strong> to processing based on legitimate interests (Art. 21), and{' '}
              <strong>withdraw consent</strong> for analytics at any time.
            </Body>
          </Li>
        </Ul>
        <Body>
          To exercise any of these, email{' '}
          <a className="underline" href={PRIVACY_EMAIL_HREF}>
            {PRIVACY_EMAIL}
          </a>{' '}
          from the address on your account, and tell us which request you are making. We acknowledge
          within 72 hours and fulfil within 30 days.
        </Body>
        <Body>
          You can also complain to your local data protection supervisory authority. In Estonia that
          is the Data Protection Inspectorate (Andmekaitse Inspektsioon,{' '}
          <a className="underline" href="https://www.aki.ee">
            aki.ee
          </a>
          ); if you live elsewhere in the EU or UK, your own national authority is equally
          competent.
        </Body>
      </Section>

      <Section title="Children's data">
        <Body>
          Wobblepot accounts are for people aged 16 or over, across all EU and UK jurisdictions.
          Household member profiles can describe children — their allergens and dietary needs are
          often exactly what a family needs planned around. By adding a member under 16, you confirm
          that you are their parent or legal guardian and consent on their behalf to this data being
          used for meal planning.
        </Body>
      </Section>

      <Section id="cookies" title="Cookies">
        <Body>
          Essential cookies keep you signed in and remember your cookie choice — they are always on,
          because the app cannot work without them. Analytics cookies are off by default and only
          set after you accept them in the cookie banner. You can change your choice at any time via
          &ldquo;Cookie settings&rdquo; in the footer.
        </Body>
      </Section>

      <Section title="Changes to this policy">
        <Body>
          When this policy or the terms of service change materially, we update the date at the top
          and bump the version users accept at sign-up. If the changes affect you significantly, we
          will ask you to review and accept them again.
        </Body>
      </Section>

      <Section title="Contact">
        <Body>
          {LEGAL_ENTITY_NAME} · registry code {LEGAL_ENTITY_REGISTRY_CODE} · {LEGAL_ENTITY_ADDRESS}{' '}
          ·{' '}
          <a className="underline" href={PRIVACY_EMAIL_HREF}>
            {PRIVACY_EMAIL}
          </a>
        </Body>
      </Section>
    </>
  )
}
