import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

// Cheap regression safeguard: Prisma cannot model partial unique indexes, so
// the SQL must be hand-rolled and stay in this migration file forever. If a
// future migration is generated by `prisma migrate dev` and accidentally drops
// or rewrites this index, this test catches it.
describe('migration 20260423120000_i18n_foundation', () => {
  const sql = readFileSync(join(__dirname, 'migration.sql'), 'utf-8')

  it('adds locale column to household with English default', () => {
    expect(sql).toMatch(/ALTER TABLE "household" ADD COLUMN "locale" TEXT NOT NULL DEFAULT 'en'/)
  })

  it('adds nullable householdId column to ingredient', () => {
    expect(sql).toMatch(/ALTER TABLE "ingredient" ADD COLUMN "householdId" TEXT;/)
  })

  it('drops the old global unique index on ingredient.name', () => {
    expect(sql).toMatch(/DROP INDEX "ingredient_name_key"/)
  })

  it('creates the partial unique index for household-scoped ingredient names', () => {
    expect(sql).toMatch(/CREATE UNIQUE INDEX "ingredient_household_name_key"/)
    expect(sql).toMatch(/WHERE "householdId" IS NOT NULL/)
  })

  it('creates the partial unique index for the global ingredient pool', () => {
    expect(sql).toMatch(/CREATE UNIQUE INDEX "ingredient_global_name_key"/)
    expect(sql).toMatch(/WHERE "householdId" IS NULL/)
  })

  it('adds cascade-delete foreign key on ingredient.householdId', () => {
    expect(sql).toMatch(/ingredient_householdId_fkey.*ON DELETE CASCADE/s)
  })

  it('creates the ingredient_translation table with composite unique key', () => {
    expect(sql).toMatch(/CREATE TABLE "ingredient_translation"/)
    expect(sql).toMatch(/CREATE UNIQUE INDEX "ingredient_translation_ingredientId_locale_key"/)
  })

  it('creates the meal_translation table with composite unique key', () => {
    expect(sql).toMatch(/CREATE TABLE "meal_translation"/)
    expect(sql).toMatch(/CREATE UNIQUE INDEX "meal_translation_mealId_locale_key"/)
  })

  it('cascades translation deletes from parent rows', () => {
    expect(sql).toMatch(/ingredient_translation_ingredientId_fkey.*ON DELETE CASCADE/s)
    expect(sql).toMatch(/meal_translation_mealId_fkey.*ON DELETE CASCADE/s)
  })
})
