// ============================================
// SEED IMPORT COVERAGE - Ingredient Expansion for Recipe Imports
// ============================================
// This file fills gaps identified during recipe import testing.
// Common ingredients from popular recipe sites (BBC Good Food, AllRecipes,
// SimplyRecipes, etc.) that were landing as "unmatched" during imports.
// Generated for HON-320.

export const importCoverageIngredients = [
  // ============================================
  // SPICES & SEASONINGS (30)
  // ============================================
  {
    name: 'cayenne pepper',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 318,
    protein: 12,
    carbs: 57,
    fat: 17,
    fiber: 27,
  },
  {
    name: 'fajita seasoning',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 310,
    protein: 10,
    carbs: 55,
    fat: 5,
    fiber: 12,
  },
  {
    name: 'lemon pepper seasoning',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 270,
    protein: 11,
    carbs: 58,
    fat: 3,
    fiber: 26,
  },
  {
    name: 'garlic salt',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 100,
    protein: 2,
    carbs: 23,
    fat: 0.5,
    fiber: 1,
  },
  {
    name: 'mustard powder',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 508,
    protein: 26,
    carbs: 28,
    fat: 36,
    fiber: 12,
  },
  {
    name: 'dried basil',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 233,
    protein: 23,
    carbs: 48,
    fat: 4,
    fiber: 38,
  },
  {
    name: 'dried oregano',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 265,
    protein: 9,
    carbs: 69,
    fat: 4,
    fiber: 43,
  },
  {
    name: 'dried parsley',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 292,
    protein: 27,
    carbs: 50,
    fat: 5,
    fiber: 27,
  },
  {
    name: 'dried dill',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 253,
    protein: 20,
    carbs: 56,
    fat: 4,
    fiber: 12,
  },
  // Fresh herbs
  {
    name: 'fresh basil',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 23,
    protein: 3.2,
    carbs: 2.6,
    fat: 0.6,
    fiber: 1.6,
  },
  {
    name: 'fresh parsley',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 36,
    protein: 3,
    carbs: 6.3,
    fat: 0.8,
    fiber: 3.3,
  },
  {
    name: 'fresh cilantro',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 23,
    protein: 2.1,
    carbs: 3.7,
    fat: 0.5,
    fiber: 2.8,
  },
  {
    name: 'fresh mint',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 44,
    protein: 3.3,
    carbs: 8.4,
    fat: 0.7,
    fiber: 6.8,
  },
  {
    name: 'fresh dill',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 43,
    protein: 3.5,
    carbs: 7,
    fat: 1.1,
    fiber: 2.1,
  },
  {
    name: 'fresh chives',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 30,
    protein: 3.3,
    carbs: 4.4,
    fat: 0.7,
    fiber: 2.5,
  },
  {
    name: 'fresh tarragon',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 50,
    protein: 3.5,
    carbs: 8,
    fat: 1.1,
    fiber: 3,
  },
  {
    name: 'fresh sage',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 99,
    protein: 3.7,
    carbs: 21,
    fat: 1.7,
    fiber: 8,
  },
  {
    name: 'fresh marjoram',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 48,
    protein: 2.7,
    carbs: 8,
    fat: 0.9,
    fiber: 4,
  },
  {
    name: 'fresh thyme',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 101,
    protein: 5.6,
    carbs: 24,
    fat: 1.7,
    fiber: 14,
  },
  {
    name: 'fresh rosemary',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 131,
    protein: 3.3,
    carbs: 21,
    fat: 5.9,
    fiber: 14,
  },
  {
    name: 'fresh oregano',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 66,
    protein: 2.5,
    carbs: 11,
    fat: 2,
    fiber: 5,
  },
  // Dried herbs
  {
    name: 'dried tarragon',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 295,
    protein: 23,
    carbs: 50,
    fat: 7.2,
    fiber: 7.4,
  },
  {
    name: 'dried sage',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 315,
    protein: 11,
    carbs: 61,
    fat: 13,
    fiber: 40,
  },
  {
    name: 'dried marjoram',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 271,
    protein: 12,
    carbs: 43,
    fat: 7,
    fiber: 18,
  },
  {
    name: 'dried mint',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 285,
    protein: 20,
    carbs: 53,
    fat: 6,
    fiber: 30,
  },
  {
    name: 'dried chives',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 311,
    protein: 22,
    carbs: 65,
    fat: 3.5,
    fiber: 27,
  },
  // Specialty herbs
  {
    name: 'thai basil',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 23,
    protein: 3.2,
    carbs: 2.6,
    fat: 0.6,
    fiber: 1.6,
  },
  {
    name: 'pumpkin pie spice',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 342,
    protein: 7,
    carbs: 69,
    fat: 9,
    fiber: 21,
  },
  {
    name: 'seasoning salt',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 5,
    protein: 0,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'celery seed',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 392,
    protein: 18,
    carbs: 42,
    fat: 25,
    fiber: 12,
  },

  // ============================================
  // CHILLIES (4)
  // ============================================
  {
    name: 'red chilli',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 2,
    carbs: 9,
    fat: 0.4,
    fiber: 1.5,
    gramsPerPiece: 15,
  },
  {
    name: 'green chilli',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 2,
    carbs: 9,
    fat: 0.2,
    fiber: 1.5,
    gramsPerPiece: 15,
  },
  {
    name: "bird's eye chilli",
    category: 'spice',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 2,
    carbs: 9,
    fat: 0.4,
    fiber: 1.5,
    gramsPerPiece: 5,
  },
  {
    name: 'pepperoncini',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 20,
    protein: 1,
    carbs: 4,
    fat: 0.3,
    fiber: 2,
    gramsPerPiece: 15,
  },

  // ============================================
  // OLIVES (3)
  // ============================================
  {
    name: 'black olive',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 115,
    protein: 0.8,
    carbs: 6,
    fat: 11,
    fiber: 3.2,
  },
  {
    name: 'green olive',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 145,
    protein: 1,
    carbs: 4,
    fat: 15,
    fiber: 3.3,
  },
  {
    name: 'kalamata olive',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 235,
    protein: 1.4,
    carbs: 4,
    fat: 24,
    fiber: 2.5,
  },

  // ============================================
  // DELI MEATS (2)
  // ============================================
  {
    name: 'pepperoni',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 504,
    protein: 22,
    carbs: 1,
    fat: 46,
    fiber: 0,
  },
  {
    name: 'salami',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 336,
    protein: 22,
    carbs: 1,
    fat: 26,
    fiber: 0,
  },

  // ============================================
  // PRODUCE VARIANTS (10)
  // ============================================
  {
    name: 'red onion',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    gramsPerPiece: 150,
  },
  {
    name: 'yellow onion',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    gramsPerPiece: 150,
  },
  {
    name: 'sweet onion',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 32,
    protein: 0.8,
    carbs: 7.6,
    fat: 0.1,
    fiber: 0.9,
    gramsPerPiece: 150,
  },
  {
    name: 'green bell pepper',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 20,
    protein: 0.9,
    carbs: 4.6,
    fat: 0.2,
    fiber: 1.7,
    gramsPerPiece: 150,
  },
  {
    name: 'yellow bell pepper',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 27,
    protein: 1,
    carbs: 6.3,
    fat: 0.2,
    fiber: 0.9,
    gramsPerPiece: 150,
  },
  {
    name: 'roma tomato',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    gramsPerPiece: 60,
  },
  {
    name: 'grape tomato',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
  },
  {
    name: 'baby spinach',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
  },
  {
    name: 'red cabbage',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 31,
    protein: 1.4,
    carbs: 7.4,
    fat: 0.2,
    fiber: 2.1,
  },
  {
    name: 'green cabbage',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 25,
    protein: 1.3,
    carbs: 5.8,
    fat: 0.1,
    fiber: 2.5,
  },

  // ============================================
  // CANNED / JARRED (6)
  // ============================================
  {
    name: 'crushed tomatoes',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 32,
    protein: 1.6,
    carbs: 6.5,
    fat: 0.3,
    fiber: 1.5,
  },
  {
    name: 'fire-roasted tomatoes',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 22,
    protein: 1,
    carbs: 4.5,
    fat: 0.2,
    fiber: 1,
  },
  {
    name: 'canned pumpkin',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 34,
    protein: 1.1,
    carbs: 8.1,
    fat: 0.3,
    fiber: 2.9,
  },
  {
    name: 'canned green chiles',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 25,
    protein: 1,
    carbs: 5,
    fat: 0.2,
    fiber: 1.5,
  },
  {
    name: 'roasted red peppers',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 26,
    protein: 0.9,
    carbs: 5.5,
    fat: 0.2,
    fiber: 1.2,
  },
  {
    name: 'tomato puree',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 38,
    protein: 1.6,
    carbs: 8.9,
    fat: 0.2,
    fiber: 1.5,
  },

  // ============================================
  // SAUCES & CONDIMENTS (7)
  // ============================================
  {
    name: 'enchilada sauce',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 60,
    protein: 1.5,
    carbs: 9,
    fat: 2,
    fiber: 1,
    densityGPerMl: 1.05,
  },
  {
    name: 'marinara sauce',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 50,
    protein: 1.5,
    carbs: 8,
    fat: 1.5,
    fiber: 1.5,
    densityGPerMl: 1.05,
  },
  {
    name: 'alfredo sauce',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 160,
    protein: 4,
    carbs: 5,
    fat: 14,
    fiber: 0,
    densityGPerMl: 1.05,
  },
  {
    name: 'buffalo sauce',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 33,
    protein: 0.5,
    carbs: 7,
    fat: 0.5,
    fiber: 0,
    densityGPerMl: 1.05,
  },
  {
    name: 'ranch dressing',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: ['eggs', 'dairy'],
    calories: 450,
    protein: 2,
    carbs: 6,
    fat: 47,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'italian dressing',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 280,
    protein: 0.5,
    carbs: 10,
    fat: 27,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'balsamic glaze',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 170,
    protein: 0.5,
    carbs: 40,
    fat: 0.1,
    fiber: 0,
    densityGPerMl: 1.3,
  },

  // ============================================
  // CHEESE (21)
  // ============================================
  {
    name: 'pepper jack cheese',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 370,
    protein: 24,
    carbs: 1,
    fat: 30,
    fiber: 0,
  },
  {
    name: 'monterey jack cheese',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 373,
    protein: 25,
    carbs: 1,
    fat: 30,
    fiber: 0,
  },
  {
    name: 'swiss cheese',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 380,
    protein: 27,
    carbs: 5,
    fat: 28,
    fiber: 0,
  },
  {
    name: 'colby jack cheese',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 394,
    protein: 24,
    carbs: 2,
    fat: 32,
    fiber: 0,
  },

  // Hard cheeses
  {
    name: 'aged cheddar',
    category: 'dairy',
    subcategory: 'hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 410,
    protein: 25,
    carbs: 0.5,
    fat: 34,
  },
  {
    name: 'comté',
    category: 'dairy',
    subcategory: 'hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 411,
    protein: 27,
    carbs: 0.5,
    fat: 34,
  },
  {
    name: 'aged gouda',
    category: 'dairy',
    subcategory: 'hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 390,
    protein: 28,
    carbs: 0,
    fat: 31,
  },
  {
    name: 'smoked gouda',
    category: 'dairy',
    subcategory: 'hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 356,
    protein: 25,
    carbs: 2.2,
    fat: 27,
  },
  {
    name: 'edam',
    category: 'dairy',
    subcategory: 'hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 357,
    protein: 25,
    carbs: 1.4,
    fat: 28,
  },
  {
    name: 'pecorino romano',
    category: 'dairy',
    subcategory: 'hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 387,
    protein: 32,
    carbs: 0,
    fat: 28,
  },

  // Semi-hard cheeses
  {
    name: 'havarti',
    category: 'dairy',
    subcategory: 'semi-hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 371,
    protein: 23,
    carbs: 0,
    fat: 31,
  },
  {
    name: 'raclette',
    category: 'dairy',
    subcategory: 'semi-hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 357,
    protein: 23,
    carbs: 0,
    fat: 29,
  },
  {
    name: 'jarlsberg',
    category: 'dairy',
    subcategory: 'semi-hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 352,
    protein: 27,
    carbs: 0,
    fat: 27,
  },
  {
    name: 'colby',
    category: 'dairy',
    subcategory: 'semi-hard cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 394,
    protein: 24,
    carbs: 2.6,
    fat: 32,
  },

  // Fresh cheeses
  {
    name: 'buffalo mozzarella',
    category: 'dairy',
    subcategory: 'fresh cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 280,
    protein: 17,
    carbs: 0,
    fat: 23,
  },
  {
    name: 'fromage blanc',
    category: 'dairy',
    subcategory: 'fresh cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 107,
    protein: 7,
    carbs: 4,
    fat: 7,
  },
  {
    name: 'chèvre',
    category: 'dairy',
    subcategory: 'fresh cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 364,
    protein: 22,
    carbs: 1,
    fat: 30,
  },

  // Soft / rind cheeses
  {
    name: 'boursin',
    category: 'dairy',
    subcategory: 'soft cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 410,
    protein: 6,
    carbs: 3,
    fat: 42,
  },
  {
    name: 'taleggio',
    category: 'dairy',
    subcategory: 'soft cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 315,
    protein: 19,
    carbs: 0,
    fat: 26,
  },

  // Blue cheeses
  {
    name: 'gorgonzola',
    category: 'dairy',
    subcategory: 'blue cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 353,
    protein: 21,
    carbs: 2,
    fat: 29,
  },
  {
    name: 'roquefort',
    category: 'dairy',
    subcategory: 'blue cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 369,
    protein: 22,
    carbs: 2,
    fat: 31,
  },

  // ============================================
  // DAIRY (2)
  // ============================================
  {
    name: 'half and half',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 130,
    protein: 3,
    carbs: 4.3,
    fat: 12,
    fiber: 0,
    densityGPerMl: 1.03,
  },
  {
    name: 'whipped cream',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 257,
    protein: 3,
    carbs: 13,
    fat: 22,
    fiber: 0,
  },

  // ============================================
  // BAKING / GRAINS (4)
  // ============================================
  {
    name: 'self-raising flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 349,
    protein: 9,
    carbs: 74,
    fat: 1,
    fiber: 2,
  },
  {
    name: 'whole wheat pasta',
    category: 'carb',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 348,
    protein: 15,
    carbs: 75,
    fat: 1.4,
    fiber: 8,
  },
  {
    name: 'angel hair pasta',
    category: 'carb',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 371,
    protein: 13,
    carbs: 75,
    fat: 1.5,
    fiber: 3.2,
  },
  {
    name: 'elbow macaroni',
    category: 'carb',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 371,
    protein: 13,
    carbs: 75,
    fat: 1.5,
    fiber: 3.2,
  },

  // ============================================
  // PROTEINS (4)
  // ============================================
  {
    name: 'andouille sausage',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 231,
    protein: 14,
    carbs: 2,
    fat: 18,
    fiber: 0,
  },
  {
    name: 'breakfast sausage',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 339,
    protein: 14,
    carbs: 1,
    fat: 31,
    fiber: 0,
  },
  {
    name: 'kielbasa',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 325,
    protein: 14,
    carbs: 4,
    fat: 28,
    fiber: 0,
  },
  {
    name: 'smoked sausage',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 295,
    protein: 12,
    carbs: 2,
    fat: 27,
    fiber: 0,
  },

  // ============================================
  // POULTRY — CUTS & FORMS (16)
  // ============================================
  {
    name: 'whole chicken',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 239,
    protein: 27,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  {
    name: 'chicken leg',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 184,
    protein: 26,
    carbs: 0,
    fat: 8,
    fiber: 0,
  },
  {
    name: 'chicken fillet',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
  },
  {
    name: 'chicken cutlet',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
  },
  {
    name: 'chicken mince',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 143,
    protein: 17,
    carbs: 0,
    fat: 8,
    fiber: 0,
  },
  {
    name: 'chicken tender',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
  },
  {
    name: 'chicken strip',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
  },
  {
    name: 'whole turkey',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 170,
    protein: 29,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  {
    name: 'turkey leg',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 159,
    protein: 27,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  {
    name: 'turkey drumstick',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 159,
    protein: 27,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  {
    name: 'turkey mince',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 149,
    protein: 20,
    carbs: 0,
    fat: 7,
    fiber: 0,
  },
  {
    name: 'duck fillet',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 337,
    protein: 19,
    carbs: 0,
    fat: 28,
    fiber: 0,
  },
  {
    name: 'duck confit',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 230,
    protein: 22,
    carbs: 0,
    fat: 15,
    fiber: 0,
  },
  {
    name: 'cornish hen',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 220,
    protein: 25,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  {
    name: 'pheasant',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 133,
    protein: 24,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
  },
  {
    name: 'guinea fowl',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 158,
    protein: 23,
    carbs: 0,
    fat: 6.5,
    fiber: 0,
  },

  // ============================================
  // BEEF — CUTS & FORMS (20)
  // ============================================
  {
    name: 'beef tenderloin',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 218,
    protein: 26,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    name: 'beef fillet',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 218,
    protein: 26,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    name: 'beef rump',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 176,
    protein: 28,
    carbs: 0,
    fat: 7,
    fiber: 0,
  },
  {
    name: 'beef topside',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 170,
    protein: 29,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  {
    name: 'beef round',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 168,
    protein: 28,
    carbs: 0,
    fat: 5.5,
    fiber: 0,
  },
  {
    name: 'beef shank',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 201,
    protein: 34,
    carbs: 0,
    fat: 7,
    fiber: 0,
  },
  {
    name: 'beef cheek',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 234,
    protein: 28,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  {
    name: 'stewing beef',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 225,
    protein: 26,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  {
    name: 'beef stew meat',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 225,
    protein: 26,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  {
    name: 'beef strips',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 218,
    protein: 26,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    name: 'beef meatball',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 250,
    protein: 17,
    carbs: 6,
    fat: 17,
    fiber: 0,
  },
  {
    name: 'beef patty',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
  },
  {
    name: 'burger patty',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
  },
  {
    name: 't-bone steak',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 247,
    protein: 24,
    carbs: 0,
    fat: 16,
    fiber: 0,
  },
  {
    name: 'rump steak',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 176,
    protein: 28,
    carbs: 0,
    fat: 7,
    fiber: 0,
  },
  {
    name: 'fillet steak',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 218,
    protein: 26,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    name: 'sirloin steak',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 218,
    protein: 27,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    name: 'new york strip',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 224,
    protein: 27,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    name: 'beef roast',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 225,
    protein: 26,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  {
    name: 'beef jerky',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 410,
    protein: 33,
    carbs: 11,
    fat: 26,
    fiber: 0,
  },

  // ============================================
  // VEAL (7)
  // ============================================
  {
    name: 'veal',
    category: 'protein',
    subcategory: 'veal',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 144,
    protein: 24,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  {
    name: 'veal cutlet',
    category: 'protein',
    subcategory: 'veal',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 144,
    protein: 24,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  {
    name: 'veal escalope',
    category: 'protein',
    subcategory: 'veal',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 144,
    protein: 24,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  {
    name: 'veal chop',
    category: 'protein',
    subcategory: 'veal',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 183,
    protein: 24,
    carbs: 0,
    fat: 9,
    fiber: 0,
  },
  {
    name: 'veal shank',
    category: 'protein',
    subcategory: 'veal',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 170,
    protein: 28,
    carbs: 0,
    fat: 6,
    fiber: 0,
  },
  {
    name: 'veal mince',
    category: 'protein',
    subcategory: 'veal',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 172,
    protein: 19,
    carbs: 0,
    fat: 10,
    fiber: 0,
  },
  {
    name: 'veal loin',
    category: 'protein',
    subcategory: 'veal',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 144,
    protein: 24,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },

  // ============================================
  // PORK — CUTS, CURED & FORMS (25)
  // ============================================
  {
    name: 'pork fillet',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 143,
    protein: 26,
    carbs: 0,
    fat: 3.5,
    fiber: 0,
  },
  {
    name: 'pork steak',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 231,
    protein: 25,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  {
    name: 'pork cutlet',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 231,
    protein: 25,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  {
    name: 'pork escalope',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 143,
    protein: 26,
    carbs: 0,
    fat: 3.5,
    fiber: 0,
  },
  {
    name: 'pork mince',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 263,
    protein: 17,
    carbs: 0,
    fat: 21,
    fiber: 0,
  },
  {
    name: 'pork leg',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 215,
    protein: 26,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    name: 'pork rack',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 277,
    protein: 21,
    carbs: 0,
    fat: 21,
    fiber: 0,
  },
  {
    name: 'pork schnitzel',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 231,
    protein: 25,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  {
    name: 'pulled pork',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 236,
    protein: 17,
    carbs: 0,
    fat: 18,
    fiber: 0,
  },
  {
    name: 'smoked bacon',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 541,
    protein: 37,
    carbs: 1.4,
    fat: 42,
    fiber: 0,
  },
  {
    name: 'back bacon',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 215,
    protein: 25,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    name: 'streaky bacon',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 541,
    protein: 37,
    carbs: 1.4,
    fat: 42,
    fiber: 0,
  },
  {
    name: 'bacon rasher',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 541,
    protein: 37,
    carbs: 1.4,
    fat: 42,
    fiber: 0,
  },
  {
    name: 'smoked ham',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 145,
    protein: 21,
    carbs: 1.5,
    fat: 6,
    fiber: 0,
  },
  {
    name: 'cooked ham',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 126,
    protein: 19,
    carbs: 2,
    fat: 4.5,
    fiber: 0,
  },
  {
    name: 'ham steak',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 145,
    protein: 21,
    carbs: 1.5,
    fat: 6,
    fiber: 0,
  },
  {
    name: 'bratwurst',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 333,
    protein: 14,
    carbs: 3,
    fat: 29,
    fiber: 0,
  },
  {
    name: 'frankfurter',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 290,
    protein: 12,
    carbs: 2,
    fat: 26,
    fiber: 0,
  },
  {
    name: 'hot dog',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 290,
    protein: 12,
    carbs: 2,
    fat: 26,
    fiber: 0,
  },
  {
    name: 'mortadella',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 311,
    protein: 14,
    carbs: 3,
    fat: 27,
    fiber: 0,
  },
  {
    name: 'liver pâté',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 319,
    protein: 12,
    carbs: 4,
    fat: 28,
    fiber: 0,
  },
  {
    name: 'nduja',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 400,
    protein: 15,
    carbs: 2,
    fat: 37,
    fiber: 0,
  },
  {
    name: 'guanciale',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 655,
    protein: 8,
    carbs: 0,
    fat: 69,
    fiber: 0,
  },
  {
    name: 'speck',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 303,
    protein: 30,
    carbs: 1,
    fat: 20,
    fiber: 0,
  },
  {
    name: 'lardons',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 541,
    protein: 37,
    carbs: 1.4,
    fat: 42,
    fiber: 0,
  },

  // ============================================
  // LAMB — CUTS & FORMS (9)
  // ============================================
  {
    name: 'lamb fillet',
    category: 'protein',
    subcategory: 'lamb',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 182,
    protein: 26,
    carbs: 0,
    fat: 8,
    fiber: 0,
  },
  {
    name: 'lamb steak',
    category: 'protein',
    subcategory: 'lamb',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 234,
    protein: 25,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  {
    name: 'lamb cutlet',
    category: 'protein',
    subcategory: 'lamb',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 294,
    protein: 25,
    carbs: 0,
    fat: 21,
    fiber: 0,
  },
  // lamb rack: already seeded in seed-comprehensive.ts (260 cal, 21g protein, 19g fat)
  {
    name: 'lamb mince',
    category: 'protein',
    subcategory: 'lamb',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 283,
    protein: 17,
    carbs: 0,
    fat: 23,
    fiber: 0,
  },
  {
    name: 'lamb neck',
    category: 'protein',
    subcategory: 'lamb',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 260,
    protein: 18,
    carbs: 0,
    fat: 20,
    fiber: 0,
  },
  {
    name: 'lamb breast',
    category: 'protein',
    subcategory: 'lamb',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 353,
    protein: 17,
    carbs: 0,
    fat: 31,
    fiber: 0,
  },
  {
    name: 'lamb liver',
    category: 'protein',
    subcategory: 'offal',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 139,
    protein: 20,
    carbs: 1.8,
    fat: 5,
    fiber: 0,
  },
  {
    name: 'lamb rump',
    category: 'protein',
    subcategory: 'lamb',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 210,
    protein: 26,
    carbs: 0,
    fat: 11,
    fiber: 0,
  },

  // ============================================
  // GAME (5)
  // ============================================
  {
    name: 'venison steak',
    category: 'protein',
    subcategory: 'game',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 158,
    protein: 30,
    carbs: 0,
    fat: 3.2,
    fiber: 0,
  },
  {
    name: 'venison mince',
    category: 'protein',
    subcategory: 'game',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 187,
    protein: 26,
    carbs: 0,
    fat: 8.5,
    fiber: 0,
  },
  {
    name: 'venison loin',
    category: 'protein',
    subcategory: 'game',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 150,
    protein: 30,
    carbs: 0,
    fat: 2.5,
    fiber: 0,
  },
  {
    name: 'wild boar',
    category: 'protein',
    subcategory: 'game',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 160,
    protein: 28,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  {
    name: 'wild boar steak',
    category: 'protein',
    subcategory: 'game',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 160,
    protein: 28,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },

  // ============================================
  // MISCELLANEOUS (3)
  // ============================================
  {
    name: 'canola oil',
    category: 'fat',
    defaultUnit: 'g',
    allergens: [],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    densityGPerMl: 0.92,
  },
  {
    name: 'cooking spray',
    category: 'fat',
    defaultUnit: 'g',
    allergens: [],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
  },
  {
    name: 'liquid honey',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    fiber: 0.2,
    densityGPerMl: 1.42,
  },

  // ============================================
  // FISH - Fillet variants (15)
  // ============================================
  {
    name: 'trout fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 119,
    protein: 20.5,
    carbs: 0,
    fat: 3.5,
  },
  {
    name: 'haddock fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 20,
    carbs: 0,
    fat: 0.6,
  },
  {
    name: 'halibut fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 111,
    protein: 23,
    carbs: 0,
    fat: 2,
  },
  {
    name: 'sea bass fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 97,
    protein: 18,
    carbs: 0,
    fat: 2,
  },
  {
    name: 'tilapia fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 96,
    protein: 20,
    carbs: 0,
    fat: 1.7,
  },
  {
    name: 'mackerel fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 205,
    protein: 19,
    carbs: 0,
    fat: 14,
  },
  {
    name: 'sole fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'swordfish steak',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 144,
    protein: 23,
    carbs: 0,
    fat: 5,
  },
  {
    name: 'snapper fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 21,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'catfish fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 95,
    protein: 16.4,
    carbs: 0,
    fat: 2.8,
  },
  {
    name: 'perch fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 91,
    protein: 19.4,
    carbs: 0,
    fat: 0.9,
  },
  {
    name: 'monkfish fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 76,
    protein: 14.5,
    carbs: 0,
    fat: 1.5,
  },
  {
    name: 'pike fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 88,
    protein: 19,
    carbs: 0,
    fat: 0.7,
  },
  {
    name: 'grouper fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 92,
    protein: 19.4,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'mahi mahi fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 85,
    protein: 18.5,
    carbs: 0,
    fat: 0.7,
  },

  // ============================================
  // FISH - Steak variants (3)
  // ============================================
  {
    name: 'tuna steak',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 132,
    protein: 29,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'salmon steak',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
  },
  {
    name: 'halibut steak',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 111,
    protein: 23,
    carbs: 0,
    fat: 2,
  },

  // ============================================
  // FISH - Missing common species (21)
  // ============================================
  {
    name: 'pollock',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 92,
    protein: 19.4,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'pollock fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 92,
    protein: 19.4,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'plaice',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 91,
    protein: 18.8,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'plaice fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 91,
    protein: 18.8,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'herring',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 158,
    protein: 18,
    carbs: 0,
    fat: 9,
  },
  {
    name: 'herring fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 158,
    protein: 18,
    carbs: 0,
    fat: 9,
  },
  {
    name: 'whiting',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 18.3,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'whiting fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 18.3,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'sea bream',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 20,
    carbs: 0,
    fat: 1.8,
  },
  {
    name: 'sea bream fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 20,
    carbs: 0,
    fat: 1.8,
  },
  {
    name: 'flounder',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14.1,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'flounder fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14.1,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'red snapper',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 21,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'red snapper fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 21,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'barramundi',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 110,
    protein: 23,
    carbs: 0,
    fat: 2,
  },
  {
    name: 'barramundi fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 110,
    protein: 23,
    carbs: 0,
    fat: 2,
  },
  {
    name: 'arctic char',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 135,
    protein: 20,
    carbs: 0,
    fat: 5.5,
  },
  {
    name: 'arctic char fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 135,
    protein: 20,
    carbs: 0,
    fat: 5.5,
  },
  {
    name: 'pangasius fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 15,
    carbs: 0,
    fat: 3,
  },
  {
    name: 'dover sole',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14.1,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'dover sole fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14.1,
    carbs: 0,
    fat: 1.2,
  },

  // ============================================
  // FISH - Common preparations and preserved forms (10)
  // ============================================
  {
    name: 'fish fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 18,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'white fish fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 18,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'smoked haddock',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 101,
    protein: 23,
    carbs: 0,
    fat: 0.9,
  },
  {
    name: 'smoked herring',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 217,
    protein: 24,
    carbs: 0,
    fat: 13,
  },
  {
    name: 'pickled herring',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 262,
    protein: 14,
    carbs: 10,
    fat: 18,
  },
  {
    name: 'canned salmon',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 153,
    protein: 21,
    carbs: 0,
    fat: 7,
  },
  {
    name: 'canned mackerel',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 156,
    protein: 23,
    carbs: 0,
    fat: 6.3,
  },
  {
    name: 'canned anchovies',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 210,
    protein: 29,
    carbs: 0,
    fat: 10,
  },
  {
    name: 'salt cod',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 290,
    protein: 63,
    carbs: 0,
    fat: 2.4,
  },
  {
    name: 'gravlax',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 150,
    protein: 19,
    carbs: 2,
    fat: 7.5,
  },

  // ============================================
  // SHELLFISH - Missing forms (10)
  // ============================================
  {
    name: 'shrimp peeled',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'king prawn',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'tiger prawn',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'crab leg',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 84,
    protein: 18.3,
    carbs: 0,
    fat: 0.6,
  },
  {
    name: 'lobster tail',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 89,
    protein: 19,
    carbs: 0,
    fat: 0.9,
  },
  {
    name: 'baby shrimp',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'cooked shrimp',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'smoked mussel',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 126,
    protein: 18,
    carbs: 4,
    fat: 3.5,
  },
  {
    name: 'clam meat',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 74,
    protein: 13,
    carbs: 3,
    fat: 1,
  },
  {
    name: 'calamari',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 92,
    protein: 16,
    carbs: 3,
    fat: 1.4,
  },

  // ============================================
  // PASTA, RICE & GRAINS (11)
  // ============================================

  // --- Pasta shapes (5) ---
  {
    name: 'linguine',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 352,
    protein: 12,
    carbs: 71,
    fat: 1.5,
    fiber: 3,
  },
  {
    name: 'orecchiette',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 352,
    protein: 12,
    carbs: 71,
    fat: 1.5,
    fiber: 3,
  },
  {
    name: 'bucatini',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 352,
    protein: 12,
    carbs: 71,
    fat: 1.5,
    fiber: 3,
  },
  {
    name: 'paccheri',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 352,
    protein: 12,
    carbs: 71,
    fat: 1.5,
    fiber: 3,
  },
  {
    name: 'tortellini',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten', 'eggs'],
    calories: 291,
    protein: 12,
    carbs: 47,
    fat: 6,
    fiber: 2,
  },

  // --- Rice varieties (4) ---
  {
    name: 'sushi rice',
    category: 'carb',
    subcategory: 'rice',
    defaultUnit: 'g',
    allergens: [],
    calories: 130,
    protein: 2.4,
    carbs: 29,
    fat: 0.2,
    fiber: 0.3,
  },
  {
    name: 'long grain rice',
    category: 'carb',
    subcategory: 'rice',
    defaultUnit: 'g',
    allergens: [],
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
  },
  {
    name: 'short grain rice',
    category: 'carb',
    subcategory: 'rice',
    defaultUnit: 'g',
    allergens: [],
    calories: 130,
    protein: 2.4,
    carbs: 29,
    fat: 0.2,
    fiber: 0.3,
  },
  {
    name: 'risotto rice',
    category: 'carb',
    subcategory: 'rice',
    defaultUnit: 'g',
    allergens: [],
    calories: 130,
    protein: 2.4,
    carbs: 29,
    fat: 0.2,
    fiber: 0.4,
  },

  // --- Other grains (2) ---
  {
    name: 'pearl barley',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 123,
    protein: 2.3,
    carbs: 28,
    fat: 0.4,
    fiber: 3.8,
  },
  {
    name: 'semolina',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 360,
    protein: 13,
    carbs: 73,
    fat: 1.1,
    fiber: 4,
  },

  // ============================================
  // NUTS, SEEDS & COCONUT FORMS (12)
  // ============================================

  // --- Tree nut forms (6) ---
  {
    name: 'chestnut',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 213,
    protein: 3,
    carbs: 45,
    fat: 2.2,
    fiber: 8,
  },
  {
    name: 'flaked almonds',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
  },
  {
    name: 'ground almonds',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
  },
  {
    name: 'sliced almonds',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
  },
  {
    name: 'chopped walnuts',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 7,
  },
  {
    name: 'candied pecans',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 520,
    protein: 5,
    carbs: 40,
    fat: 40,
    fiber: 5,
  },

  // --- Nut butter (1) ---
  {
    name: 'hazelnut spread',
    category: 'fat',
    subcategory: 'nut-butter',
    defaultUnit: 'g',
    allergens: ['nuts', 'dairy'],
    calories: 539,
    protein: 6,
    carbs: 58,
    fat: 31,
    fiber: 3,
  },

  // --- Seed variants (2) ---
  {
    name: 'ground flax seeds',
    category: 'fat',
    subcategory: 'seed',
    defaultUnit: 'g',
    allergens: [],
    calories: 534,
    protein: 18,
    carbs: 29,
    fat: 42,
    fiber: 27,
  },
  {
    name: 'black sesame seeds',
    category: 'fat',
    subcategory: 'seed',
    defaultUnit: 'g',
    allergens: ['sesame'],
    calories: 573,
    protein: 18,
    carbs: 23,
    fat: 50,
    fiber: 12,
  },

  // --- Coconut forms (3) ---
  {
    name: 'shredded coconut',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 660,
    protein: 7,
    carbs: 24,
    fat: 65,
    fiber: 16,
  },
  {
    name: 'desiccated coconut',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 660,
    protein: 7,
    carbs: 24,
    fat: 65,
    fiber: 16,
  },
  {
    name: 'toasted coconut',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 592,
    protein: 6,
    carbs: 26,
    fat: 55,
    fiber: 14,
  },

  // ============================================
  // ASIAN & INTERNATIONAL CONDIMENTS (9)
  // ============================================
  // Fills gaps for international condiments not covered by
  // seed.ts, seed-expansion.ts, or seed-comprehensive.ts.
  // Generated for HON-407.

  // --- East Asian (2) ---
  {
    name: 'toban djan',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: ['soy'],
    calories: 60,
    protein: 3,
    carbs: 8,
    fat: 2,
    fiber: 2,
  },
  {
    name: 'dashi',
    category: 'condiment',
    subcategory: 'liquid',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 3,
    protein: 0.5,
    carbs: 0.3,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.0,
  },

  // --- Southeast Asian (3) ---
  {
    name: 'fish paste',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 113,
    protein: 18,
    carbs: 5,
    fat: 2,
    fiber: 0,
  },
  {
    name: 'shrimp paste',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 168,
    protein: 30,
    carbs: 7,
    fat: 2,
    fiber: 0,
  },
  {
    name: 'pandan extract',
    category: 'condiment',
    subcategory: 'liquid',
    defaultUnit: 'g',
    allergens: [],
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.0,
  },

  // --- South Asian (2) ---
  {
    name: 'tamarind concentrate',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: [],
    calories: 239,
    protein: 3,
    carbs: 63,
    fat: 0.6,
    fiber: 5,
  },
  {
    name: 'curry paste',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: [],
    calories: 84,
    protein: 2,
    carbs: 10,
    fat: 4,
    fiber: 3,
  },

  // --- Latin American (2) ---
  {
    name: 'adobo sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: [],
    calories: 24,
    protein: 0.5,
    carbs: 5,
    fat: 0.3,
    fiber: 1,
    densityGPerMl: 1.05,
  },
  {
    name: 'mole paste',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: ['sesame', 'nuts'],
    calories: 200,
    protein: 5,
    carbs: 25,
    fat: 10,
    fiber: 4,
  },

  // ============================================
  // CROSS-CUISINE HIGH-PRIORITY (5) — HON-411
  // ============================================
  {
    name: 'chili oil',
    category: 'fat',
    subcategory: 'oil',
    defaultUnit: 'g',
    allergens: [],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    densityGPerMl: 0.92,
  },
  {
    name: 'palm oil',
    category: 'fat',
    subcategory: 'oil',
    defaultUnit: 'g',
    allergens: [],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    densityGPerMl: 0.91,
  },
  {
    name: 'puff pastry',
    category: 'carb',
    subcategory: 'pastry',
    defaultUnit: 'g',
    allergens: ['gluten', 'dairy'],
    calories: 558,
    protein: 7.3,
    carbs: 45,
    fat: 38,
    fiber: 1.6,
  },
  {
    name: 'salmon',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  {
    name: 'cod',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 82,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
  },

  // ============================================
  // AUDIT FIX — Wrong fuzzy matches (HON-410)
  // ============================================

  // --- Sauces & Condiments ---
  {
    name: 'tonkatsu sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['soy', 'gluten'],
    calories: 120,
    protein: 0.5,
    carbs: 29,
    fat: 0.1,
    fiber: 0.3,
    densityGPerMl: 1.15,
  },
  {
    name: 'tamarind',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: [],
    calories: 239,
    protein: 2.8,
    carbs: 62.5,
    fat: 0.6,
    fiber: 5.1,
  },
  {
    name: 'custard powder',
    category: 'baking',
    defaultUnit: 'g',
    allergens: [],
    calories: 380,
    protein: 0.5,
    carbs: 92,
    fat: 0.5,
    fiber: 0,
  },

  // --- Leaves (wrapping / garnish) ---
  {
    name: 'perilla leaves',
    category: 'vegetable',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 37,
    protein: 3.7,
    carbs: 3.4,
    fat: 0.1,
    fiber: 3.5,
  },
  {
    name: 'banana leaves',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    gramsPerPiece: 50,
  },
  {
    name: 'grape leaves',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 93,
    protein: 5.6,
    carbs: 17.3,
    fat: 2.1,
    fiber: 11,
    gramsPerPiece: 4,
  },

  // --- Sausages ---
  {
    name: 'calabresa sausage',
    category: 'protein',
    subcategory: 'sausage',
    defaultUnit: 'g',
    allergens: [],
    calories: 290,
    protein: 15,
    carbs: 2,
    fat: 25,
    fiber: 0,
    proteinType: 'pork',
  },
  {
    name: 'Cumberland sausage',
    category: 'protein',
    subcategory: 'sausage',
    defaultUnit: 'g',
    allergens: [],
    calories: 280,
    protein: 14,
    carbs: 3,
    fat: 24,
    fiber: 0,
    proteinType: 'pork',
  },

  // --- Thai, Vietnamese & Chinese pantry (7) ---
  {
    name: 'pandan leaf',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 35,
    protein: 2.5,
    carbs: 5.5,
    fat: 0.5,
    fiber: 2.8,
  },
  {
    name: 'annatto seeds',
    category: 'spice',
    subcategory: 'seed',
    defaultUnit: 'g',
    allergens: [],
    calories: 373,
    protein: 14,
    carbs: 52,
    fat: 13,
    fiber: 17,
  },
  {
    name: 'vietnamese coffee',
    category: 'condiment',
    subcategory: 'beverage',
    defaultUnit: 'g',
    allergens: [],
    calories: 353,
    protein: 12.6,
    carbs: 65.4,
    fat: 11.7,
    fiber: 0,
  },
  {
    name: 'gai lan',
    category: 'vegetable',
    subcategory: 'leafy green',
    defaultUnit: 'g',
    allergens: [],
    calories: 26,
    protein: 1.2,
    carbs: 4.7,
    fat: 0.6,
    fiber: 2.0,
  },
  {
    name: 'choy sum',
    category: 'vegetable',
    subcategory: 'leafy green',
    defaultUnit: 'g',
    allergens: [],
    calories: 13,
    protein: 1.7,
    carbs: 1.6,
    fat: 0.2,
    fiber: 1.0,
  },
  {
    name: 'dried lily buds',
    category: 'vegetable',
    subcategory: 'dried vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 284,
    protein: 9,
    carbs: 63,
    fat: 0.5,
    fiber: 7.4,
  },
  {
    name: 'tofu skin',
    category: 'legume',
    subcategory: 'soy product',
    defaultUnit: 'g',
    allergens: ['soy'],
    calories: 387,
    protein: 52,
    carbs: 11,
    fat: 16,
    fiber: 0.6,
  },

  // ── Mediterranean & French specialty ingredients (HON-417) ── 12 items

  // Spanish
  {
    name: 'piquillo peppers',
    category: 'vegetable',
    subcategory: 'pepper',
    defaultUnit: 'g',
    allergens: [],
    calories: 30,
    protein: 1,
    carbs: 5.5,
    fat: 0.3,
    fiber: 2,
  },
  {
    name: 'soppressata',
    category: 'protein',
    subcategory: 'cured meat',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 425,
    protein: 23,
    carbs: 1,
    fat: 37,
  },
  {
    name: 'carnaroli rice',
    category: 'carb',
    subcategory: 'rice',
    defaultUnit: 'g',
    allergens: [],
    calories: 350,
    protein: 7,
    carbs: 78,
    fat: 0.5,
    fiber: 1,
  },
  {
    name: '00 flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 340,
    protein: 11,
    carbs: 70,
    fat: 1,
    fiber: 2.5,
  },
  {
    name: 'calabrian chili',
    category: 'spice',
    subcategory: 'chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 28,
    protein: 1.3,
    carbs: 5.5,
    fat: 0.3,
    fiber: 1.5,
  },
  {
    name: 'bresaola',
    category: 'protein',
    subcategory: 'cured meat',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 151,
    protein: 33,
    carbs: 0,
    fat: 2.6,
  },

  // French
  {
    name: 'foie gras',
    category: 'protein',
    subcategory: 'offal',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 462,
    protein: 11.4,
    carbs: 4.7,
    fat: 43.8,
  },
  {
    name: 'cornichons',
    category: 'vegetable',
    subcategory: 'pickle',
    defaultUnit: 'g',
    allergens: [],
    calories: 14,
    protein: 0.5,
    carbs: 2.3,
    fat: 0.2,
    fiber: 1,
  },
  {
    name: 'fleur de sel',
    category: 'condiment',
    subcategory: 'salt',
    defaultUnit: 'g',
    allergens: [],
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
  },
  {
    name: 'calvados',
    category: 'condiment',
    subcategory: 'spirit',
    defaultUnit: 'g',
    allergens: [],
    calories: 233,
    protein: 0,
    carbs: 0,
    fat: 0,
    densityGPerMl: 0.94,
  },
  {
    name: 'haricots verts',
    category: 'vegetable',
    subcategory: 'green bean',
    defaultUnit: 'g',
    allergens: [],
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.1,
    fiber: 3.4,
  },

  // Greek
  {
    name: 'phyllo dough',
    category: 'carb',
    subcategory: 'pastry',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 310,
    protein: 5.7,
    carbs: 52,
    fat: 8,
    fiber: 1.8,
  },
]
