// ============================================
// SEED IMPORT COVERAGE - Ingredient Expansion for Recipe Imports
// ============================================
// This file fills gaps identified during recipe import testing.
// Common ingredients from popular recipe sites (BBC Good Food, AllRecipes,
// SimplyRecipes, etc.) that were landing as "unmatched" during imports.
// Generated for HON-320.

export const importCoverageIngredients = [
  // ============================================
  // SPICES & SEASONINGS (12)
  // ============================================
  {
    name: 'cayenne pepper',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 318,
    protein: 12,
    carbs: 57,
    fat: 17,
    fiber: 27,
  },
  {
    name: 'fajita seasoning',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 310,
    protein: 10,
    carbs: 55,
    fat: 5,
    fiber: 12,
  },
  {
    name: 'lemon pepper seasoning',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 270,
    protein: 11,
    carbs: 58,
    fat: 3,
    fiber: 26,
  },
  {
    name: 'garlic salt',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 100,
    protein: 2,
    carbs: 23,
    fat: 0.5,
    fiber: 1,
  },
  {
    name: 'mustard powder',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 508,
    protein: 26,
    carbs: 28,
    fat: 36,
    fiber: 12,
  },
  {
    name: 'dried basil',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 233,
    protein: 23,
    carbs: 48,
    fat: 4,
    fiber: 38,
  },
  {
    name: 'dried oregano',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 265,
    protein: 9,
    carbs: 69,
    fat: 4,
    fiber: 43,
  },
  {
    name: 'dried parsley',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 292,
    protein: 27,
    carbs: 50,
    fat: 5,
    fiber: 27,
  },
  {
    name: 'dried dill',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 253,
    protein: 20,
    carbs: 56,
    fat: 4,
    fiber: 12,
  },
  {
    name: 'pumpkin pie spice',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 342,
    protein: 7,
    carbs: 69,
    fat: 9,
    fiber: 21,
  },
  {
    name: 'seasoning salt',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 5,
    protein: 0,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'celery seed',
    category: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 392,
    protein: 18,
    carbs: 42,
    fat: 25,
    fiber: 12,
  },

  // ============================================
  // CHILLIES (4)
  // ============================================
  {
    name: 'red chilli',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 2,
    carbs: 9,
    fat: 0.4,
    fiber: 1.5,
    gramsPerPiece: 15,
  },
  {
    name: 'green chilli',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 2,
    carbs: 9,
    fat: 0.2,
    fiber: 1.5,
    gramsPerPiece: 15,
  },
  {
    name: "bird's eye chilli",
    category: 'spice',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 2,
    carbs: 9,
    fat: 0.4,
    fiber: 1.5,
    gramsPerPiece: 5,
  },
  {
    name: 'pepperoncini',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 20,
    protein: 1,
    carbs: 4,
    fat: 0.3,
    fiber: 2,
    gramsPerPiece: 15,
  },

  // ============================================
  // OLIVES (3)
  // ============================================
  {
    name: 'black olive',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 115,
    protein: 0.8,
    carbs: 6,
    fat: 11,
    fiber: 3.2,
  },
  {
    name: 'green olive',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 145,
    protein: 1,
    carbs: 4,
    fat: 15,
    fiber: 3.3,
  },
  {
    name: 'kalamata olive',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 235,
    protein: 1.4,
    carbs: 4,
    fat: 24,
    fiber: 2.5,
  },

  // ============================================
  // DELI MEATS (2)
  // ============================================
  {
    name: 'pepperoni',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 504,
    protein: 22,
    carbs: 1,
    fat: 46,
    fiber: 0,
  },
  {
    name: 'salami',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 336,
    protein: 22,
    carbs: 1,
    fat: 26,
    fiber: 0,
  },

  // ============================================
  // PRODUCE VARIANTS (10)
  // ============================================
  {
    name: 'red onion',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    gramsPerPiece: 150,
  },
  {
    name: 'yellow onion',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    gramsPerPiece: 150,
  },
  {
    name: 'sweet onion',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 32,
    protein: 0.8,
    carbs: 7.6,
    fat: 0.1,
    fiber: 0.9,
    gramsPerPiece: 150,
  },
  {
    name: 'green bell pepper',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 20,
    protein: 0.9,
    carbs: 4.6,
    fat: 0.2,
    fiber: 1.7,
    gramsPerPiece: 150,
  },
  {
    name: 'yellow bell pepper',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 27,
    protein: 1,
    carbs: 6.3,
    fat: 0.2,
    fiber: 0.9,
    gramsPerPiece: 150,
  },
  {
    name: 'roma tomato',
    category: 'vegetable',
    defaultUnit: 'piece',
    allergens: [],
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    gramsPerPiece: 60,
  },
  {
    name: 'grape tomato',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
  },
  {
    name: 'baby spinach',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
  },
  {
    name: 'red cabbage',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 31,
    protein: 1.4,
    carbs: 7.4,
    fat: 0.2,
    fiber: 2.1,
  },
  {
    name: 'green cabbage',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 25,
    protein: 1.3,
    carbs: 5.8,
    fat: 0.1,
    fiber: 2.5,
  },

  // ============================================
  // CANNED / JARRED (6)
  // ============================================
  {
    name: 'crushed tomatoes',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 32,
    protein: 1.6,
    carbs: 6.5,
    fat: 0.3,
    fiber: 1.5,
  },
  {
    name: 'fire-roasted tomatoes',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 22,
    protein: 1,
    carbs: 4.5,
    fat: 0.2,
    fiber: 1,
  },
  {
    name: 'canned pumpkin',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 34,
    protein: 1.1,
    carbs: 8.1,
    fat: 0.3,
    fiber: 2.9,
  },
  {
    name: 'canned green chiles',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 25,
    protein: 1,
    carbs: 5,
    fat: 0.2,
    fiber: 1.5,
  },
  {
    name: 'roasted red peppers',
    category: 'vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 26,
    protein: 0.9,
    carbs: 5.5,
    fat: 0.2,
    fiber: 1.2,
  },
  {
    name: 'tomato puree',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 38,
    protein: 1.6,
    carbs: 8.9,
    fat: 0.2,
    fiber: 1.5,
  },

  // ============================================
  // SAUCES & CONDIMENTS (7)
  // ============================================
  {
    name: 'enchilada sauce',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 60,
    protein: 1.5,
    carbs: 9,
    fat: 2,
    fiber: 1,
    densityGPerMl: 1.05,
  },
  {
    name: 'marinara sauce',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 50,
    protein: 1.5,
    carbs: 8,
    fat: 1.5,
    fiber: 1.5,
    densityGPerMl: 1.05,
  },
  {
    name: 'alfredo sauce',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 160,
    protein: 4,
    carbs: 5,
    fat: 14,
    fiber: 0,
    densityGPerMl: 1.05,
  },
  {
    name: 'buffalo sauce',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 33,
    protein: 0.5,
    carbs: 7,
    fat: 0.5,
    fiber: 0,
    densityGPerMl: 1.05,
  },
  {
    name: 'ranch dressing',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: ['eggs', 'dairy'],
    calories: 450,
    protein: 2,
    carbs: 6,
    fat: 47,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'italian dressing',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 280,
    protein: 0.5,
    carbs: 10,
    fat: 27,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'balsamic glaze',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 170,
    protein: 0.5,
    carbs: 40,
    fat: 0.1,
    fiber: 0,
    densityGPerMl: 1.3,
  },

  // ============================================
  // CHEESE (4)
  // ============================================
  {
    name: 'pepper jack cheese',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 370,
    protein: 24,
    carbs: 1,
    fat: 30,
    fiber: 0,
  },
  {
    name: 'monterey jack cheese',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 373,
    protein: 25,
    carbs: 1,
    fat: 30,
    fiber: 0,
  },
  {
    name: 'swiss cheese',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 380,
    protein: 27,
    carbs: 5,
    fat: 28,
    fiber: 0,
  },
  {
    name: 'colby jack cheese',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 394,
    protein: 24,
    carbs: 2,
    fat: 32,
    fiber: 0,
  },

  // ============================================
  // DAIRY (2)
  // ============================================
  {
    name: 'half and half',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 130,
    protein: 3,
    carbs: 4.3,
    fat: 12,
    fiber: 0,
    densityGPerMl: 1.03,
  },
  {
    name: 'whipped cream',
    category: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 257,
    protein: 3,
    carbs: 13,
    fat: 22,
    fiber: 0,
  },

  // ============================================
  // BAKING / GRAINS (4)
  // ============================================
  {
    name: 'self-raising flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 349,
    protein: 9,
    carbs: 74,
    fat: 1,
    fiber: 2,
  },
  {
    name: 'whole wheat pasta',
    category: 'carb',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 348,
    protein: 15,
    carbs: 75,
    fat: 1.4,
    fiber: 8,
  },
  {
    name: 'angel hair pasta',
    category: 'carb',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 371,
    protein: 13,
    carbs: 75,
    fat: 1.5,
    fiber: 3.2,
  },
  {
    name: 'elbow macaroni',
    category: 'carb',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 371,
    protein: 13,
    carbs: 75,
    fat: 1.5,
    fiber: 3.2,
  },

  // ============================================
  // PROTEINS (4)
  // ============================================
  {
    name: 'andouille sausage',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 231,
    protein: 14,
    carbs: 2,
    fat: 18,
    fiber: 0,
  },
  {
    name: 'breakfast sausage',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 339,
    protein: 14,
    carbs: 1,
    fat: 31,
    fiber: 0,
  },
  {
    name: 'kielbasa',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 325,
    protein: 14,
    carbs: 4,
    fat: 28,
    fiber: 0,
  },
  {
    name: 'smoked sausage',
    category: 'protein',
    subcategory: 'pork',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 295,
    protein: 12,
    carbs: 2,
    fat: 27,
    fiber: 0,
  },

  // ============================================
  // MISCELLANEOUS (3)
  // ============================================
  {
    name: 'canola oil',
    category: 'fat',
    defaultUnit: 'g',
    allergens: [],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    densityGPerMl: 0.92,
  },
  {
    name: 'cooking spray',
    category: 'fat',
    defaultUnit: 'g',
    allergens: [],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
  },
  {
    name: 'liquid honey',
    category: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    fiber: 0.2,
    densityGPerMl: 1.42,
  },

  // ============================================
  // FISH - Fillet variants (15)
  // ============================================
  {
    name: 'trout fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 119,
    protein: 20.5,
    carbs: 0,
    fat: 3.5,
  },
  {
    name: 'haddock fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 20,
    carbs: 0,
    fat: 0.6,
  },
  {
    name: 'halibut fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 111,
    protein: 23,
    carbs: 0,
    fat: 2,
  },
  {
    name: 'sea bass fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 97,
    protein: 18,
    carbs: 0,
    fat: 2,
  },
  {
    name: 'tilapia fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 96,
    protein: 20,
    carbs: 0,
    fat: 1.7,
  },
  {
    name: 'mackerel fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 205,
    protein: 19,
    carbs: 0,
    fat: 14,
  },
  {
    name: 'sole fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'swordfish steak',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 144,
    protein: 23,
    carbs: 0,
    fat: 5,
  },
  {
    name: 'snapper fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 21,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'catfish fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 95,
    protein: 16.4,
    carbs: 0,
    fat: 2.8,
  },
  {
    name: 'perch fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 91,
    protein: 19.4,
    carbs: 0,
    fat: 0.9,
  },
  {
    name: 'monkfish fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 76,
    protein: 14.5,
    carbs: 0,
    fat: 1.5,
  },
  {
    name: 'pike fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 88,
    protein: 19,
    carbs: 0,
    fat: 0.7,
  },
  {
    name: 'grouper fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 92,
    protein: 19.4,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'mahi mahi fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 85,
    protein: 18.5,
    carbs: 0,
    fat: 0.7,
  },

  // ============================================
  // FISH - Steak variants (3)
  // ============================================
  {
    name: 'tuna steak',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 132,
    protein: 29,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'salmon steak',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
  },
  {
    name: 'halibut steak',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 111,
    protein: 23,
    carbs: 0,
    fat: 2,
  },

  // ============================================
  // FISH - Missing common species (21)
  // ============================================
  {
    name: 'pollock',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 92,
    protein: 19.4,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'pollock fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 92,
    protein: 19.4,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'plaice',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 91,
    protein: 18.8,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'plaice fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 91,
    protein: 18.8,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'herring',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 158,
    protein: 18,
    carbs: 0,
    fat: 9,
  },
  {
    name: 'herring fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 158,
    protein: 18,
    carbs: 0,
    fat: 9,
  },
  {
    name: 'whiting',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 18.3,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'whiting fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 18.3,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'sea bream',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 20,
    carbs: 0,
    fat: 1.8,
  },
  {
    name: 'sea bream fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 20,
    carbs: 0,
    fat: 1.8,
  },
  {
    name: 'flounder',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14.1,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'flounder fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14.1,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'red snapper',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 21,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'red snapper fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 100,
    protein: 21,
    carbs: 0,
    fat: 1.3,
  },
  {
    name: 'barramundi',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 110,
    protein: 23,
    carbs: 0,
    fat: 2,
  },
  {
    name: 'barramundi fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 110,
    protein: 23,
    carbs: 0,
    fat: 2,
  },
  {
    name: 'arctic char',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 135,
    protein: 20,
    carbs: 0,
    fat: 5.5,
  },
  {
    name: 'arctic char fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 135,
    protein: 20,
    carbs: 0,
    fat: 5.5,
  },
  {
    name: 'pangasius fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 15,
    carbs: 0,
    fat: 3,
  },
  {
    name: 'Dover sole',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14.1,
    carbs: 0,
    fat: 1.2,
  },
  {
    name: 'Dover sole fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 70,
    protein: 14.1,
    carbs: 0,
    fat: 1.2,
  },

  // ============================================
  // FISH - Common preparations and preserved forms (10)
  // ============================================
  {
    name: 'fish fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 18,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'white fish fillet',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 90,
    protein: 18,
    carbs: 0,
    fat: 1,
  },
  {
    name: 'smoked haddock',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 101,
    protein: 23,
    carbs: 0,
    fat: 0.9,
  },
  {
    name: 'smoked herring',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 217,
    protein: 24,
    carbs: 0,
    fat: 13,
  },
  {
    name: 'pickled herring',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 262,
    protein: 14,
    carbs: 10,
    fat: 18,
  },
  {
    name: 'canned salmon',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 153,
    protein: 21,
    carbs: 0,
    fat: 7,
  },
  {
    name: 'canned mackerel',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 156,
    protein: 23,
    carbs: 0,
    fat: 6.3,
  },
  {
    name: 'canned anchovies',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 210,
    protein: 29,
    carbs: 0,
    fat: 10,
  },
  {
    name: 'salt cod',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 290,
    protein: 63,
    carbs: 0,
    fat: 2.4,
  },
  {
    name: 'gravlax',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 150,
    protein: 19,
    carbs: 2,
    fat: 7.5,
  },

  // ============================================
  // SHELLFISH - Missing forms (10)
  // ============================================
  {
    name: 'shrimp peeled',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'king prawn',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'tiger prawn',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'crab leg',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 84,
    protein: 18.3,
    carbs: 0,
    fat: 0.6,
  },
  {
    name: 'lobster tail',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 89,
    protein: 19,
    carbs: 0,
    fat: 0.9,
  },
  {
    name: 'baby shrimp',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'cooked shrimp',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    name: 'smoked mussel',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 126,
    protein: 18,
    carbs: 4,
    fat: 3.5,
  },
  {
    name: 'clam meat',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 74,
    protein: 13,
    carbs: 3,
    fat: 1,
  },
  {
    name: 'calamari',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 92,
    protein: 16,
    carbs: 3,
    fat: 1.4,
  },
]
