// ============================================
// SEED COMPREHENSIVE - AI-Generated Ingredient Expansion
// ============================================
// This file expands the ingredient library to cover baking, Asian, Latin,
// Indian, Mediterranean pantry items, condiments, wines, proteins, and produce.
// Generated for HON-248.

// ============================================
// COMPREHENSIVE INGREDIENTS
// ============================================

export const comprehensiveIngredients = [
  // ============================================
  // BAKING - Flours (8)
  // ============================================
  {
    name: 'all-purpose flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 364,
    protein: 10,
    carbs: 76,
    fat: 1,
    fiber: 2.7,
  },
  {
    name: 'bread flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 361,
    protein: 12,
    carbs: 72,
    fat: 1.7,
    fiber: 2.4,
  },
  {
    name: 'cake flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 362,
    protein: 8,
    carbs: 79,
    fat: 0.8,
    fiber: 1.8,
  },
  {
    name: 'whole wheat flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 340,
    protein: 13,
    carbs: 72,
    fat: 2.5,
    fiber: 10.7,
  },
  {
    name: 'semolina flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 360,
    protein: 13,
    carbs: 73,
    fat: 1.1,
    fiber: 3.9,
  },
  {
    name: 'chickpea flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: [],
    calories: 387,
    protein: 22,
    carbs: 58,
    fat: 6.7,
    fiber: 10.8,
  },
  {
    name: 'rice flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: [],
    calories: 366,
    protein: 6,
    carbs: 80,
    fat: 1.4,
    fiber: 2.4,
  },
  {
    name: 'almond flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 571,
    protein: 21,
    carbs: 20,
    fat: 50,
    fiber: 10,
  },

  // ============================================
  // BAKING - Sugars & Sweeteners (7)
  // ============================================
  {
    name: 'granulated sugar',
    category: 'carb',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 387,
    protein: 0,
    carbs: 100,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'powdered sugar',
    category: 'carb',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 389,
    protein: 0,
    carbs: 100,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'caster sugar',
    category: 'carb',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 387,
    protein: 0,
    carbs: 100,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'coconut sugar',
    category: 'carb',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 375,
    protein: 1,
    carbs: 94,
    fat: 0.5,
    fiber: 0,
  },
  {
    name: 'molasses',
    category: 'condiment',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 290,
    protein: 0,
    carbs: 75,
    fat: 0.1,
    fiber: 0,
    densityGPerMl: 1.4,
  },
  {
    name: 'corn syrup',
    category: 'condiment',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 286,
    protein: 0,
    carbs: 78,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.38,
  },
  {
    name: 'light brown sugar',
    category: 'carb',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 380,
    protein: 0,
    carbs: 98,
    fat: 0,
    fiber: 0,
  },

  // ============================================
  // BAKING - Leaveners & Baking Essentials (8)
  // ============================================
  {
    name: 'baking soda',
    category: 'spice',
    subcategory: 'leavener',
    defaultUnit: 'g',
    allergens: [],
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'baking powder',
    category: 'spice',
    subcategory: 'leavener',
    defaultUnit: 'g',
    allergens: [],
    calories: 53,
    protein: 0,
    carbs: 28,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'active dry yeast',
    category: 'spice',
    subcategory: 'leavener',
    defaultUnit: 'g',
    allergens: [],
    calories: 325,
    protein: 40,
    carbs: 42,
    fat: 6.2,
    fiber: 27,
  },
  {
    name: 'cornstarch',
    category: 'carb',
    subcategory: 'starch',
    defaultUnit: 'g',
    allergens: [],
    calories: 381,
    protein: 0.3,
    carbs: 91,
    fat: 0.1,
    fiber: 0.9,
  },
  {
    name: 'cream of tartar',
    category: 'spice',
    subcategory: 'leavener',
    defaultUnit: 'g',
    allergens: [],
    calories: 258,
    protein: 0,
    carbs: 62,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'gelatin',
    category: 'condiment',
    subcategory: 'thickener',
    defaultUnit: 'g',
    allergens: [],
    calories: 335,
    protein: 86,
    carbs: 0,
    fat: 0.1,
    fiber: 0,
  },
  {
    name: 'tapioca starch',
    category: 'carb',
    subcategory: 'starch',
    defaultUnit: 'g',
    allergens: [],
    calories: 360,
    protein: 0.2,
    carbs: 89,
    fat: 0,
    fiber: 0.9,
  },
  {
    name: 'potato starch',
    category: 'carb',
    subcategory: 'starch',
    defaultUnit: 'g',
    allergens: [],
    calories: 357,
    protein: 0.1,
    carbs: 88,
    fat: 0,
    fiber: 0,
  },

  // ============================================
  // BAKING - Extracts & Flavorings (4)
  // ============================================
  {
    name: 'vanilla extract',
    category: 'condiment',
    subcategory: 'extract',
    defaultUnit: 'g',
    allergens: [],
    calories: 288,
    protein: 0.1,
    carbs: 13,
    fat: 0.1,
    fiber: 0,
    densityGPerMl: 1.03,
  },
  {
    name: 'almond extract',
    category: 'condiment',
    subcategory: 'extract',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 259,
    protein: 0,
    carbs: 3,
    fat: 0,
    fiber: 0,
    densityGPerMl: 0.95,
  },
  {
    name: 'rose water',
    category: 'condiment',
    subcategory: 'extract',
    defaultUnit: 'g',
    allergens: [],
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'orange blossom water',
    category: 'condiment',
    subcategory: 'extract',
    defaultUnit: 'g',
    allergens: [],
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.0,
  },

  // ============================================
  // BAKING - Chocolate & Cocoa (4)
  // ============================================
  {
    name: 'chocolate chips',
    category: 'condiment',
    subcategory: 'chocolate',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 502,
    protein: 5,
    carbs: 60,
    fat: 29,
    fiber: 5,
  },
  {
    name: 'unsweetened chocolate',
    category: 'condiment',
    subcategory: 'chocolate',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 501,
    protein: 13,
    carbs: 30,
    fat: 43,
    fiber: 17,
  },
  {
    name: 'white chocolate',
    category: 'condiment',
    subcategory: 'chocolate',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 539,
    protein: 6,
    carbs: 59,
    fat: 32,
    fiber: 0,
  },
  {
    name: 'dutch process cocoa powder',
    category: 'condiment',
    subcategory: 'chocolate',
    defaultUnit: 'g',
    allergens: [],
    calories: 228,
    protein: 20,
    carbs: 58,
    fat: 14,
    fiber: 33,
  },

  // ============================================
  // ASIAN PANTRY - Sauces & Pastes (12)
  // ============================================
  {
    name: 'dark soy sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['soy', 'gluten'],
    calories: 60,
    protein: 5,
    carbs: 9,
    fat: 0.1,
    fiber: 0,
    densityGPerMl: 1.15,
  },
  {
    name: 'light soy sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['soy', 'gluten'],
    calories: 53,
    protein: 8,
    carbs: 4,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.1,
  },
  {
    name: 'sweet soy sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['soy', 'gluten'],
    calories: 165,
    protein: 3,
    carbs: 35,
    fat: 0.1,
    fiber: 0,
    densityGPerMl: 1.3,
  },
  {
    name: 'black bean sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['soy'],
    calories: 65,
    protein: 4,
    carbs: 8,
    fat: 1.5,
    fiber: 1,
    densityGPerMl: 1.1,
  },
  {
    name: 'chili garlic sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: [],
    calories: 80,
    protein: 2,
    carbs: 17,
    fat: 0.5,
    fiber: 2,
    densityGPerMl: 1.1,
  },
  {
    name: 'sweet chili sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: [],
    calories: 221,
    protein: 0.5,
    carbs: 54,
    fat: 0.2,
    fiber: 0.5,
    densityGPerMl: 1.2,
  },
  {
    name: 'plum sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['soy'],
    calories: 184,
    protein: 0.4,
    carbs: 46,
    fat: 0.1,
    fiber: 0.5,
    densityGPerMl: 1.2,
  },
  {
    name: 'xo sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['shellfish', 'fish'],
    calories: 390,
    protein: 15,
    carbs: 20,
    fat: 28,
    fiber: 0,
    densityGPerMl: 1.05,
  },
  {
    name: 'thai sweet basil',
    category: 'vegetable',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 23,
    protein: 3.2,
    carbs: 2.7,
    fat: 0.6,
    fiber: 1.6,
  },
  {
    name: 'white miso paste',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: ['soy', 'gluten'],
    calories: 198,
    protein: 12,
    carbs: 26,
    fat: 6,
    fiber: 5,
    densityGPerMl: 1.15,
  },
  {
    name: 'red miso paste',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: ['soy', 'gluten'],
    calories: 198,
    protein: 13,
    carbs: 23,
    fat: 6,
    fiber: 5,
    densityGPerMl: 1.15,
  },
  {
    name: 'curry paste massaman',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: ['fish', 'peanuts'],
    calories: 125,
    protein: 3,
    carbs: 12,
    fat: 7,
    fiber: 3,
    densityGPerMl: 1.1,
  },

  // ============================================
  // ASIAN PANTRY - Noodles & Rice (6)
  // ============================================
  {
    name: 'glass noodles',
    category: 'carb',
    subcategory: 'noodle',
    defaultUnit: 'g',
    allergens: [],
    calories: 334,
    protein: 0.1,
    carbs: 83,
    fat: 0.1,
    fiber: 0,
  },
  {
    name: 'ramen noodles',
    category: 'carb',
    subcategory: 'noodle',
    defaultUnit: 'g',
    allergens: ['gluten', 'eggs'],
    calories: 457,
    protein: 9,
    carbs: 65,
    fat: 18,
    fiber: 2,
  },
  {
    name: 'wonton wrappers',
    category: 'carb',
    subcategory: 'wrapper',
    defaultUnit: 'g',
    allergens: ['gluten', 'eggs'],
    calories: 291,
    protein: 8,
    carbs: 56,
    fat: 2.8,
    fiber: 1.5,
  },
  {
    name: 'spring roll wrappers',
    category: 'carb',
    subcategory: 'wrapper',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 305,
    protein: 7,
    carbs: 64,
    fat: 1.5,
    fiber: 1.2,
  },
  {
    name: 'sticky rice',
    category: 'carb',
    subcategory: 'rice',
    defaultUnit: 'g',
    allergens: [],
    calories: 370,
    protein: 6.8,
    carbs: 81,
    fat: 0.6,
    fiber: 1,
  },
  {
    name: 'black rice',
    category: 'carb',
    subcategory: 'rice',
    defaultUnit: 'g',
    allergens: [],
    calories: 356,
    protein: 8.9,
    carbs: 76,
    fat: 2.8,
    fiber: 3.4,
  },

  // ============================================
  // ASIAN PANTRY - Vegetables & Aromatics (10)
  // ============================================
  {
    name: 'baby corn',
    category: 'vegetable',
    subcategory: 'asian vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 26,
    protein: 2,
    carbs: 5,
    fat: 0.2,
    fiber: 2,
  },
  {
    name: 'chinese broccoli',
    category: 'vegetable',
    subcategory: 'asian vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 26,
    protein: 1.2,
    carbs: 4,
    fat: 0.6,
    fiber: 2.2,
  },
  {
    name: 'yu choy',
    category: 'vegetable',
    subcategory: 'asian vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 16,
    protein: 1.7,
    carbs: 2,
    fat: 0.2,
    fiber: 1.5,
  },
  {
    name: 'shiso leaf',
    category: 'vegetable',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 37,
    protein: 3.9,
    carbs: 4.4,
    fat: 1,
    fiber: 3.4,
  },
  {
    name: 'thai chili',
    category: 'vegetable',
    subcategory: 'pepper',
    defaultUnit: 'g',
    allergens: [],
    calories: 40,
    protein: 1.9,
    carbs: 9,
    fat: 0.4,
    fiber: 1.5,
  },
  {
    name: 'chinese celery',
    category: 'vegetable',
    subcategory: 'asian vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 14,
    protein: 0.7,
    carbs: 3,
    fat: 0.2,
    fiber: 1.6,
  },
  {
    name: 'morning glory',
    category: 'vegetable',
    subcategory: 'asian vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 19,
    protein: 2.6,
    carbs: 3.1,
    fat: 0.2,
    fiber: 2,
  },
  {
    name: 'bitter melon',
    category: 'vegetable',
    subcategory: 'asian vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 17,
    protein: 1,
    carbs: 3.7,
    fat: 0.2,
    fiber: 2.8,
  },
  {
    name: 'long beans',
    category: 'vegetable',
    subcategory: 'asian vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 47,
    protein: 2.5,
    carbs: 8,
    fat: 0.4,
    fiber: 3,
  },
  {
    name: 'fresh turmeric',
    category: 'spice',
    subcategory: 'root spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 312,
    protein: 8,
    carbs: 67,
    fat: 3.3,
    fiber: 21,
  },

  // ============================================
  // ASIAN PANTRY - Other (6)
  // ============================================
  {
    name: 'palm sugar',
    category: 'carb',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 371,
    protein: 0.4,
    carbs: 93,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'toasted sesame oil',
    category: 'fat',
    subcategory: 'oil',
    defaultUnit: 'g',
    allergens: ['sesame'],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    densityGPerMl: 0.92,
  },
  {
    name: 'rice paper',
    category: 'carb',
    subcategory: 'wrapper',
    defaultUnit: 'g',
    allergens: [],
    calories: 309,
    protein: 0.8,
    carbs: 76,
    fat: 0.1,
    fiber: 0.3,
  },
  {
    name: 'dried shiitake mushroom',
    category: 'vegetable',
    subcategory: 'mushroom',
    defaultUnit: 'g',
    allergens: [],
    calories: 296,
    protein: 9.6,
    carbs: 63,
    fat: 1,
    fiber: 11.5,
  },
  {
    name: 'fermented black beans',
    category: 'condiment',
    subcategory: 'fermented',
    defaultUnit: 'g',
    allergens: ['soy'],
    calories: 173,
    protein: 15,
    carbs: 17,
    fat: 5,
    fiber: 7,
  },
  {
    name: 'bonito flakes',
    category: 'condiment',
    subcategory: 'dried seafood',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 338,
    protein: 76,
    carbs: 0,
    fat: 3,
    fiber: 0,
  },

  // ============================================
  // LATIN PANTRY (12)
  // ============================================
  {
    name: 'achiote paste',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: [],
    calories: 300,
    protein: 5,
    carbs: 50,
    fat: 9,
    fiber: 10,
  },
  {
    name: 'queso fresco',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 299,
    protein: 21,
    carbs: 3,
    fat: 22,
    fiber: 0,
  },
  {
    name: 'crema mexicana',
    category: 'dairy',
    subcategory: 'cream',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 195,
    protein: 2.5,
    carbs: 3.5,
    fat: 19,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'tomatillo',
    category: 'vegetable',
    subcategory: 'nightshade',
    defaultUnit: 'g',
    allergens: [],
    calories: 32,
    protein: 1,
    carbs: 6,
    fat: 1,
    fiber: 1.9,
  },
  {
    name: 'nopales',
    category: 'vegetable',
    subcategory: 'cactus',
    defaultUnit: 'g',
    allergens: [],
    calories: 16,
    protein: 1.3,
    carbs: 3.3,
    fat: 0.1,
    fiber: 2.2,
  },
  {
    name: 'masa harina',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: [],
    calories: 365,
    protein: 9,
    carbs: 76,
    fat: 3.8,
    fiber: 7.3,
  },
  {
    name: 'cotija cheese',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 393,
    protein: 29,
    carbs: 2,
    fat: 30,
    fiber: 0,
  },
  {
    name: 'epazote',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 32,
    protein: 3,
    carbs: 4,
    fat: 0.5,
    fiber: 4,
  },
  {
    name: 'mexican oregano',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 265,
    protein: 9,
    carbs: 69,
    fat: 4.3,
    fiber: 43,
  },
  {
    name: 'ancho chili powder',
    category: 'spice',
    subcategory: 'chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 282,
    protein: 12,
    carbs: 50,
    fat: 8,
    fiber: 28,
  },
  {
    name: 'chipotle powder',
    category: 'spice',
    subcategory: 'chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 282,
    protein: 12,
    carbs: 50,
    fat: 8,
    fiber: 28,
  },
  {
    name: 'pepitas',
    category: 'fat',
    subcategory: 'seed',
    defaultUnit: 'g',
    allergens: [],
    calories: 559,
    protein: 30,
    carbs: 11,
    fat: 49,
    fiber: 6,
  },

  // ============================================
  // MEXICAN - Dried Chilies & Specialty (6)
  // ============================================
  {
    name: 'guajillo chili',
    category: 'spice',
    subcategory: 'dried chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 324,
    protein: 11,
    carbs: 56,
    fat: 6,
    fiber: 29,
  },
  {
    name: 'pasilla chili',
    category: 'spice',
    subcategory: 'dried chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 324,
    protein: 11,
    carbs: 56,
    fat: 6,
    fiber: 29,
  },
  {
    name: 'arbol chili',
    category: 'spice',
    subcategory: 'dried chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 324,
    protein: 11,
    carbs: 56,
    fat: 6,
    fiber: 29,
  },
  {
    name: 'queso oaxaca',
    category: 'dairy',
    subcategory: 'cheese',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 316,
    protein: 25,
    carbs: 2,
    fat: 23,
    fiber: 0,
  },
  {
    name: 'huitlacoche',
    category: 'vegetable',
    subcategory: 'fungus',
    defaultUnit: 'g',
    allergens: [],
    calories: 35,
    protein: 3.5,
    carbs: 4,
    fat: 0.7,
    fiber: 2,
  },
  {
    name: 'piloncillo',
    category: 'condiment',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 375,
    protein: 0.4,
    carbs: 93,
    fat: 0.1,
    fiber: 0,
  },

  // ============================================
  // INDIAN PANTRY (14)
  // ============================================
  {
    name: 'curry leaves',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 108,
    protein: 6.1,
    carbs: 18,
    fat: 1,
    fiber: 6.4,
  },
  {
    name: 'asafoetida',
    category: 'spice',
    subcategory: 'spice',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 297,
    protein: 4,
    carbs: 68,
    fat: 1.1,
    fiber: 4,
  },
  {
    name: 'green cardamom',
    category: 'spice',
    subcategory: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 311,
    protein: 11,
    carbs: 68,
    fat: 6.7,
    fiber: 28,
  },
  {
    name: 'black cardamom',
    category: 'spice',
    subcategory: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 311,
    protein: 11,
    carbs: 68,
    fat: 6.7,
    fiber: 28,
  },
  {
    name: 'chana dal',
    category: 'legume',
    subcategory: 'lentil',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 364,
    protein: 22,
    carbs: 60,
    fat: 5,
    fiber: 12,
  },
  {
    name: 'urad dal',
    category: 'legume',
    subcategory: 'lentil',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 341,
    protein: 25,
    carbs: 59,
    fat: 1.6,
    fiber: 18,
  },
  {
    name: 'moong dal',
    category: 'legume',
    subcategory: 'lentil',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 347,
    protein: 24,
    carbs: 63,
    fat: 1.2,
    fiber: 16,
  },
  {
    name: 'toor dal',
    category: 'legume',
    subcategory: 'lentil',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 343,
    protein: 22,
    carbs: 62,
    fat: 1.5,
    fiber: 15,
  },
  {
    name: 'kashmiri chili powder',
    category: 'spice',
    subcategory: 'chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 282,
    protein: 12,
    carbs: 50,
    fat: 8,
    fiber: 28,
  },
  {
    name: 'amchur powder',
    category: 'spice',
    subcategory: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 300,
    protein: 2,
    carbs: 72,
    fat: 1,
    fiber: 8,
  },
  {
    name: 'black mustard seeds',
    category: 'spice',
    subcategory: 'seed spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 508,
    protein: 26,
    carbs: 28,
    fat: 36,
    fiber: 12,
  },
  {
    name: 'nigella seeds',
    category: 'spice',
    subcategory: 'seed spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 345,
    protein: 16,
    carbs: 52,
    fat: 15,
    fiber: 8,
  },
  {
    name: 'ajwain seeds',
    category: 'spice',
    subcategory: 'seed spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 305,
    protein: 16,
    carbs: 43,
    fat: 25,
    fiber: 21,
  },
  {
    name: 'jaggery',
    category: 'carb',
    subcategory: 'sweetener',
    defaultUnit: 'g',
    allergens: [],
    calories: 383,
    protein: 0.4,
    carbs: 97,
    fat: 0.1,
    fiber: 0,
  },

  // ============================================
  // MEDITERRANEAN (10)
  // ============================================
  {
    name: 'pomegranate molasses',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: [],
    calories: 293,
    protein: 0.3,
    carbs: 72,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.35,
  },
  {
    name: 'freekeh',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 325,
    protein: 12.6,
    carbs: 72,
    fat: 2.5,
    fiber: 16.5,
  },
  {
    name: 'pine nuts',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 673,
    protein: 14,
    carbs: 13,
    fat: 68,
    fiber: 3.7,
  },
  {
    name: 'preserved lemon',
    category: 'condiment',
    subcategory: 'preserved',
    defaultUnit: 'g',
    allergens: [],
    calories: 27,
    protein: 0.6,
    carbs: 6,
    fat: 0.2,
    fiber: 2,
  },
  {
    name: 'dukkah',
    category: 'spice',
    subcategory: 'spice blend',
    defaultUnit: 'g',
    allergens: ['nuts', 'sesame'],
    calories: 520,
    protein: 18,
    carbs: 22,
    fat: 42,
    fiber: 10,
  },
  {
    name: 'aleppo pepper',
    category: 'spice',
    subcategory: 'chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 282,
    protein: 12,
    carbs: 50,
    fat: 8,
    fiber: 28,
  },
  {
    name: 'urfa pepper',
    category: 'spice',
    subcategory: 'chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 282,
    protein: 12,
    carbs: 50,
    fat: 8,
    fiber: 28,
  },
  {
    name: 'baharat',
    category: 'spice',
    subcategory: 'spice blend',
    defaultUnit: 'g',
    allergens: [],
    calories: 260,
    protein: 10,
    carbs: 50,
    fat: 8,
    fiber: 20,
  },
  {
    name: 'pearl couscous',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 376,
    protein: 13,
    carbs: 77,
    fat: 1.6,
    fiber: 5,
  },
  {
    name: 'provolone',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 351,
    protein: 25,
    carbs: 2.1,
    fat: 27,
    fiber: 0,
  },

  // ============================================
  // CONDIMENTS & SAUCES (16)
  // ============================================
  {
    name: 'tomato paste',
    category: 'condiment',
    subcategory: 'tomato',
    defaultUnit: 'g',
    allergens: [],
    calories: 82,
    protein: 4.3,
    carbs: 19,
    fat: 0.5,
    fiber: 4.1,
    densityGPerMl: 1.1,
  },
  {
    name: 'yellow mustard',
    category: 'condiment',
    subcategory: 'mustard',
    defaultUnit: 'g',
    allergens: [],
    calories: 60,
    protein: 4,
    carbs: 6,
    fat: 3,
    fiber: 3,
    densityGPerMl: 1.05,
  },
  {
    name: 'stone ground mustard',
    category: 'condiment',
    subcategory: 'mustard',
    defaultUnit: 'g',
    allergens: [],
    calories: 67,
    protein: 4,
    carbs: 5,
    fat: 4,
    fiber: 3,
    densityGPerMl: 1.05,
  },
  {
    name: 'honey mustard',
    category: 'condiment',
    subcategory: 'mustard',
    defaultUnit: 'g',
    allergens: [],
    calories: 200,
    protein: 1,
    carbs: 28,
    fat: 10,
    fiber: 0,
    densityGPerMl: 1.1,
  },
  {
    name: 'white vinegar',
    category: 'condiment',
    subcategory: 'vinegar',
    defaultUnit: 'g',
    allergens: [],
    calories: 18,
    protein: 0,
    carbs: 0.04,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.01,
  },
  {
    name: 'red wine vinegar',
    category: 'condiment',
    subcategory: 'vinegar',
    defaultUnit: 'g',
    allergens: [],
    calories: 19,
    protein: 0,
    carbs: 0.3,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.01,
  },
  {
    name: 'white wine vinegar',
    category: 'condiment',
    subcategory: 'vinegar',
    defaultUnit: 'g',
    allergens: [],
    calories: 18,
    protein: 0,
    carbs: 0.3,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.01,
  },
  {
    name: 'malt vinegar',
    category: 'condiment',
    subcategory: 'vinegar',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 18,
    protein: 0,
    carbs: 0.2,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.01,
  },
  {
    name: 'bbq sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: [],
    calories: 172,
    protein: 0.8,
    carbs: 40,
    fat: 0.6,
    fiber: 0.5,
    densityGPerMl: 1.15,
  },
  {
    name: 'steak sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: [],
    calories: 100,
    protein: 0.5,
    carbs: 25,
    fat: 0,
    fiber: 0.3,
    densityGPerMl: 1.1,
  },
  {
    name: 'horseradish',
    category: 'condiment',
    subcategory: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 48,
    protein: 1.2,
    carbs: 11,
    fat: 0.7,
    fiber: 3.3,
  },
  {
    name: 'prepared horseradish',
    category: 'condiment',
    subcategory: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 55,
    protein: 1.5,
    carbs: 12,
    fat: 0.5,
    fiber: 2,
    densityGPerMl: 1.05,
  },
  {
    name: 'relish',
    category: 'condiment',
    subcategory: 'condiment',
    defaultUnit: 'g',
    allergens: [],
    calories: 130,
    protein: 0.5,
    carbs: 33,
    fat: 0.4,
    fiber: 0.5,
    densityGPerMl: 1.1,
  },
  {
    name: 'tartar sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['eggs'],
    calories: 350,
    protein: 0.5,
    carbs: 6,
    fat: 35,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'anchovy paste',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 110,
    protein: 13,
    carbs: 0,
    fat: 6,
    fiber: 0,
    densityGPerMl: 1.1,
  },
  {
    name: 'capers in brine',
    category: 'condiment',
    subcategory: 'preserved',
    defaultUnit: 'g',
    allergens: [],
    calories: 23,
    protein: 2.4,
    carbs: 1.7,
    fat: 0.9,
    fiber: 3.2,
  },

  // ============================================
  // WINES & SPIRITS for cooking (6)
  // ============================================
  {
    name: 'red wine',
    category: 'condiment',
    subcategory: 'cooking wine',
    defaultUnit: 'g',
    allergens: [],
    calories: 85,
    protein: 0.1,
    carbs: 2.6,
    fat: 0,
    fiber: 0,
    densityGPerMl: 0.99,
  },
  {
    name: 'white wine',
    category: 'condiment',
    subcategory: 'cooking wine',
    defaultUnit: 'g',
    allergens: [],
    calories: 82,
    protein: 0.1,
    carbs: 2.6,
    fat: 0,
    fiber: 0,
    densityGPerMl: 0.99,
  },
  {
    name: 'dry sherry',
    category: 'condiment',
    subcategory: 'cooking wine',
    defaultUnit: 'g',
    allergens: [],
    calories: 116,
    protein: 0.2,
    carbs: 1.4,
    fat: 0,
    fiber: 0,
    densityGPerMl: 0.98,
  },
  {
    name: 'marsala wine',
    category: 'condiment',
    subcategory: 'cooking wine',
    defaultUnit: 'g',
    allergens: [],
    calories: 130,
    protein: 0.1,
    carbs: 7,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'cooking sherry',
    category: 'condiment',
    subcategory: 'cooking wine',
    defaultUnit: 'g',
    allergens: [],
    calories: 48,
    protein: 0.1,
    carbs: 5.6,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'rum',
    category: 'condiment',
    subcategory: 'spirit',
    defaultUnit: 'g',
    allergens: [],
    calories: 231,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    densityGPerMl: 0.94,
  },

  // ============================================
  // PROTEINS - Fish & Seafood (12)
  // ============================================
  {
    name: 'mahi mahi',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 85,
    protein: 18.5,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
  },
  {
    name: 'grouper',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 92,
    protein: 19.4,
    carbs: 0,
    fat: 1,
    fiber: 0,
  },
  {
    name: 'catfish',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 95,
    protein: 16.4,
    carbs: 0,
    fat: 2.8,
    fiber: 0,
  },
  {
    name: 'perch',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 91,
    protein: 19.4,
    carbs: 0,
    fat: 0.9,
    fiber: 0,
  },
  {
    name: 'monkfish',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 76,
    protein: 14.5,
    carbs: 0,
    fat: 1.5,
    fiber: 0,
  },
  {
    name: 'smelt',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 97,
    protein: 17.6,
    carbs: 0,
    fat: 2.4,
    fiber: 0,
  },
  {
    name: 'king crab',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 84,
    protein: 18.3,
    carbs: 0,
    fat: 0.6,
    fiber: 0,
  },
  {
    name: 'crawfish',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 82,
    protein: 16.8,
    carbs: 0,
    fat: 1.2,
    fiber: 0,
  },
  {
    name: 'sea urchin',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 120,
    protein: 13.4,
    carbs: 3.3,
    fat: 4.8,
    fiber: 0,
  },
  {
    name: 'conch',
    category: 'protein',
    subcategory: 'shellfish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    calories: 130,
    protein: 26,
    carbs: 1,
    fat: 1.6,
    fiber: 0,
  },
  {
    name: 'canned sardines',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 208,
    protein: 24.6,
    carbs: 0,
    fat: 11.5,
    fiber: 0,
  },
  {
    name: 'smoked mackerel',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 305,
    protein: 19,
    carbs: 0,
    fat: 25,
    fiber: 0,
  },

  // ============================================
  // PROTEINS - Other Meats (8)
  // ============================================
  {
    name: 'rabbit',
    category: 'protein',
    subcategory: 'game',
    proteinType: 'pork',
    defaultUnit: 'g',
    allergens: [],
    calories: 136,
    protein: 20.1,
    carbs: 0,
    fat: 5.6,
    fiber: 0,
  },
  {
    name: 'venison',
    category: 'protein',
    subcategory: 'game',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 158,
    protein: 30,
    carbs: 0,
    fat: 3.2,
    fiber: 0,
  },
  {
    name: 'bison',
    category: 'protein',
    subcategory: 'game',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 143,
    protein: 28.4,
    carbs: 0,
    fat: 2.4,
    fiber: 0,
  },
  {
    name: 'lamb kidney',
    category: 'protein',
    subcategory: 'offal',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 97,
    protein: 15.7,
    carbs: 0.8,
    fat: 3.3,
    fiber: 0,
  },
  {
    name: 'beef liver',
    category: 'protein',
    subcategory: 'offal',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 135,
    protein: 20.4,
    carbs: 3.9,
    fat: 3.6,
    fiber: 0,
  },
  {
    name: 'oxtail',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 262,
    protein: 22,
    carbs: 0,
    fat: 19,
    fiber: 0,
  },
  {
    name: 'bone marrow',
    category: 'protein',
    subcategory: 'beef',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 786,
    protein: 7,
    carbs: 0,
    fat: 84,
    fiber: 0,
  },
  {
    name: 'turkey sausage',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 166,
    protein: 16,
    carbs: 2,
    fat: 10,
    fiber: 0,
  },

  // ============================================
  // PRODUCE - Mushrooms (5)
  // ============================================
  {
    name: 'maitake mushroom',
    category: 'vegetable',
    subcategory: 'mushroom',
    defaultUnit: 'g',
    allergens: [],
    calories: 31,
    protein: 1.9,
    carbs: 4.3,
    fat: 0.2,
    fiber: 2.7,
  },
  {
    name: 'chanterelle mushroom',
    category: 'vegetable',
    subcategory: 'mushroom',
    defaultUnit: 'g',
    allergens: [],
    calories: 32,
    protein: 1.5,
    carbs: 6.9,
    fat: 0.5,
    fiber: 3.8,
  },
  {
    name: 'porcini mushroom',
    category: 'vegetable',
    subcategory: 'mushroom',
    defaultUnit: 'g',
    allergens: [],
    calories: 26,
    protein: 3.7,
    carbs: 3.3,
    fat: 0.3,
    fiber: 2.1,
  },
  {
    name: 'cremini mushroom',
    category: 'vegetable',
    subcategory: 'mushroom',
    defaultUnit: 'g',
    allergens: [],
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.1,
    fiber: 1,
  },
  {
    name: 'dried porcini mushroom',
    category: 'vegetable',
    subcategory: 'mushroom',
    defaultUnit: 'g',
    allergens: [],
    calories: 296,
    protein: 30,
    carbs: 45,
    fat: 2.5,
    fiber: 18,
  },

  // ============================================
  // PRODUCE - Fresh Herbs (8)
  // ============================================
  {
    name: 'lemon thyme',
    category: 'vegetable',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 101,
    protein: 5.6,
    carbs: 24,
    fat: 1.7,
    fiber: 14,
  },
  {
    name: 'chervil',
    category: 'vegetable',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 237,
    protein: 23,
    carbs: 49,
    fat: 4,
    fiber: 11,
  },
  {
    name: 'sorrel',
    category: 'vegetable',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 22,
    protein: 2,
    carbs: 3.2,
    fat: 0.7,
    fiber: 2.9,
  },
  {
    name: 'lovage',
    category: 'vegetable',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 20,
    protein: 3.5,
    carbs: 1.3,
    fat: 0.4,
    fiber: 1.5,
  },
  {
    name: 'lavender',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 23,
    protein: 4,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'lemon verbena',
    category: 'spice',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 20,
    protein: 0.3,
    carbs: 4,
    fat: 0.2,
    fiber: 1,
  },
  {
    name: 'flat leaf parsley',
    category: 'vegetable',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 36,
    protein: 3,
    carbs: 6.3,
    fat: 0.8,
    fiber: 3.3,
  },
  {
    name: 'curly parsley',
    category: 'vegetable',
    subcategory: 'herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 36,
    protein: 3,
    carbs: 6.3,
    fat: 0.8,
    fiber: 3.3,
  },

  // ============================================
  // PRODUCE - Vegetables (20)
  // ============================================
  {
    name: 'romanesco',
    category: 'vegetable',
    subcategory: 'cruciferous',
    defaultUnit: 'g',
    allergens: [],
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
    fiber: 2,
  },
  {
    name: 'sunchoke',
    category: 'vegetable',
    subcategory: 'root',
    defaultUnit: 'g',
    allergens: [],
    calories: 73,
    protein: 2,
    carbs: 17.4,
    fat: 0,
    fiber: 1.6,
  },
  {
    name: 'celeriac',
    category: 'vegetable',
    subcategory: 'root',
    defaultUnit: 'g',
    allergens: [],
    calories: 42,
    protein: 1.5,
    carbs: 9.2,
    fat: 0.3,
    fiber: 1.8,
  },
  {
    name: 'rutabaga',
    category: 'vegetable',
    subcategory: 'root',
    defaultUnit: 'g',
    allergens: [],
    calories: 36,
    protein: 1.2,
    carbs: 8.6,
    fat: 0.2,
    fiber: 2.3,
  },
  {
    name: 'jicama',
    category: 'vegetable',
    subcategory: 'root',
    defaultUnit: 'g',
    allergens: [],
    calories: 38,
    protein: 0.7,
    carbs: 9,
    fat: 0.1,
    fiber: 4.9,
  },
  {
    name: 'fennel bulb',
    category: 'vegetable',
    subcategory: 'bulb',
    defaultUnit: 'g',
    allergens: [],
    calories: 31,
    protein: 1.2,
    carbs: 7.3,
    fat: 0.2,
    fiber: 3.1,
  },
  {
    name: 'shallot',
    category: 'vegetable',
    subcategory: 'allium',
    defaultUnit: 'g',
    allergens: [],
    calories: 72,
    protein: 2.5,
    carbs: 17,
    fat: 0.1,
    fiber: 3.2,
  },
  {
    name: 'pearl onion',
    category: 'vegetable',
    subcategory: 'allium',
    defaultUnit: 'g',
    allergens: [],
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
  },
  {
    name: 'ramp',
    category: 'vegetable',
    subcategory: 'allium',
    defaultUnit: 'g',
    allergens: [],
    calories: 35,
    protein: 2,
    carbs: 6,
    fat: 0.3,
    fiber: 2,
  },
  {
    name: 'fiddlehead fern',
    category: 'vegetable',
    subcategory: 'green',
    defaultUnit: 'g',
    allergens: [],
    calories: 34,
    protein: 4.6,
    carbs: 5.5,
    fat: 0.4,
    fiber: 3,
  },
  {
    name: 'pea shoots',
    category: 'vegetable',
    subcategory: 'microgreen',
    defaultUnit: 'g',
    allergens: [],
    calories: 42,
    protein: 2.8,
    carbs: 7.5,
    fat: 0.4,
    fiber: 2.6,
  },
  {
    name: 'sunflower sprouts',
    category: 'vegetable',
    subcategory: 'microgreen',
    defaultUnit: 'g',
    allergens: [],
    calories: 30,
    protein: 3,
    carbs: 4,
    fat: 0.5,
    fiber: 1.5,
  },
  {
    name: 'broccoli rabe',
    category: 'vegetable',
    subcategory: 'cruciferous',
    defaultUnit: 'g',
    allergens: [],
    calories: 22,
    protein: 3.2,
    carbs: 2.9,
    fat: 0.5,
    fiber: 2.7,
  },
  {
    name: 'sugar snap peas',
    category: 'vegetable',
    subcategory: 'legume vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 42,
    protein: 2.8,
    carbs: 7.6,
    fat: 0.2,
    fiber: 2.6,
  },
  {
    name: 'wax beans',
    category: 'vegetable',
    subcategory: 'legume vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.1,
    fiber: 2.7,
  },
  {
    name: 'hearts of palm',
    category: 'vegetable',
    subcategory: 'tropical vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 28,
    protein: 2.5,
    carbs: 4.6,
    fat: 0.6,
    fiber: 2.4,
  },
  {
    name: 'gem lettuce',
    category: 'vegetable',
    subcategory: 'leafy green',
    defaultUnit: 'piece',
    allergens: [],
    calories: 14,
    protein: 1.4,
    carbs: 2.2,
    fat: 0.2,
    fiber: 1.3,
    gramsPerPiece: 120,
  },
  {
    name: 'frisee',
    category: 'vegetable',
    subcategory: 'leafy green',
    defaultUnit: 'g',
    allergens: [],
    calories: 17,
    protein: 1.3,
    carbs: 3.4,
    fat: 0.2,
    fiber: 3.1,
  },
  {
    name: 'savoy cabbage',
    category: 'vegetable',
    subcategory: 'cruciferous',
    defaultUnit: 'g',
    allergens: [],
    calories: 27,
    protein: 2,
    carbs: 6,
    fat: 0.1,
    fiber: 3.1,
  },
  {
    name: 'purple cabbage',
    category: 'vegetable',
    subcategory: 'cruciferous',
    defaultUnit: 'g',
    allergens: [],
    calories: 31,
    protein: 1.4,
    carbs: 7.4,
    fat: 0.2,
    fiber: 2.1,
  },

  // ============================================
  // PRODUCE - Fruits (10)
  // ============================================
  {
    name: 'kumquat',
    category: 'fruit',
    subcategory: 'citrus',
    defaultUnit: 'g',
    allergens: [],
    calories: 71,
    protein: 1.9,
    carbs: 16,
    fat: 0.9,
    fiber: 6.5,
  },
  {
    name: 'key lime',
    category: 'fruit',
    subcategory: 'citrus',
    defaultUnit: 'piece',
    allergens: [],
    calories: 30,
    protein: 0.7,
    carbs: 11,
    fat: 0.2,
    fiber: 2.8,
    gramsPerPiece: 15,
  },
  {
    name: 'yuzu',
    category: 'fruit',
    subcategory: 'citrus',
    defaultUnit: 'piece',
    allergens: [],
    calories: 30,
    protein: 0.5,
    carbs: 7,
    fat: 0.3,
    fiber: 1.8,
    gramsPerPiece: 50,
  },
  {
    name: 'golden kiwi',
    category: 'fruit',
    subcategory: 'tropical',
    defaultUnit: 'piece',
    allergens: [],
    calories: 63,
    protein: 1.1,
    carbs: 15,
    fat: 0.3,
    fiber: 2,
    gramsPerPiece: 80,
  },
  {
    name: 'tamarillo',
    category: 'fruit',
    subcategory: 'tropical',
    defaultUnit: 'piece',
    allergens: [],
    calories: 31,
    protein: 2,
    carbs: 4,
    fat: 0.4,
    fiber: 3.3,
    gramsPerPiece: 60,
  },
  {
    name: 'cactus pear',
    category: 'fruit',
    subcategory: 'tropical',
    defaultUnit: 'piece',
    allergens: [],
    calories: 41,
    protein: 0.7,
    carbs: 10,
    fat: 0.5,
    fiber: 3.6,
    gramsPerPiece: 150,
  },
  {
    name: 'feijoa',
    category: 'fruit',
    subcategory: 'tropical',
    defaultUnit: 'piece',
    allergens: [],
    calories: 55,
    protein: 1,
    carbs: 13,
    fat: 0.6,
    fiber: 6.4,
    gramsPerPiece: 50,
  },
  {
    name: 'cherimoya',
    category: 'fruit',
    subcategory: 'tropical',
    defaultUnit: 'piece',
    allergens: [],
    calories: 75,
    protein: 1.6,
    carbs: 18,
    fat: 0.7,
    fiber: 3,
    gramsPerPiece: 250,
  },
  {
    name: 'dried mango',
    category: 'fruit',
    subcategory: 'dried fruit',
    defaultUnit: 'g',
    allergens: [],
    calories: 319,
    protein: 2.4,
    carbs: 78,
    fat: 1.2,
    fiber: 2,
  },
  {
    name: 'dried figs',
    category: 'fruit',
    subcategory: 'dried fruit',
    defaultUnit: 'g',
    allergens: [],
    calories: 249,
    protein: 3.3,
    carbs: 64,
    fat: 0.9,
    fiber: 9.8,
  },

  // ============================================
  // DAIRY & ALTERNATIVES (10)
  // ============================================
  {
    name: 'oat milk',
    category: 'dairy',
    subcategory: 'milk alternative',
    proteinType: 'none',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 47,
    protein: 1,
    carbs: 7,
    fat: 1.5,
    fiber: 0.8,
    densityGPerMl: 1.03,
  },
  {
    name: 'almond milk',
    category: 'dairy',
    subcategory: 'milk alternative',
    proteinType: 'none',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 13,
    protein: 0.4,
    carbs: 0.3,
    fat: 1.1,
    fiber: 0.2,
    densityGPerMl: 1.02,
  },
  {
    name: 'coconut milk canned',
    category: 'dairy',
    subcategory: 'milk alternative',
    proteinType: 'none',
    defaultUnit: 'g',
    allergens: [],
    calories: 197,
    protein: 2.3,
    carbs: 2.8,
    fat: 21,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'soy milk',
    category: 'dairy',
    subcategory: 'milk alternative',
    proteinType: 'none',
    defaultUnit: 'g',
    allergens: ['soy'],
    calories: 33,
    protein: 2.9,
    carbs: 1.2,
    fat: 1.8,
    fiber: 0.4,
    densityGPerMl: 1.03,
  },
  {
    name: 'plain yogurt',
    category: 'dairy',
    subcategory: 'yogurt',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    densityGPerMl: 1.05,
  },
  {
    name: 'skyr',
    category: 'dairy',
    subcategory: 'yogurt',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 63,
    protein: 11,
    carbs: 4,
    fat: 0.2,
    fiber: 0,
    densityGPerMl: 1.05,
  },
  {
    name: 'burrata',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 270,
    protein: 17,
    carbs: 1,
    fat: 22,
    fiber: 0,
  },
  {
    name: 'manchego',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 392,
    protein: 25,
    carbs: 0.5,
    fat: 32,
    fiber: 0,
  },
  {
    name: 'fontina',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 389,
    protein: 25,
    carbs: 1.5,
    fat: 31,
    fiber: 0,
  },
  {
    name: 'quark',
    category: 'dairy',
    subcategory: 'fermented dairy',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 67,
    protein: 12,
    carbs: 4,
    fat: 0.2,
    fiber: 0,
    densityGPerMl: 1.05,
  },

  // ============================================
  // FATS, NUTS & SEEDS (10)
  // ============================================
  {
    name: 'walnut oil',
    category: 'fat',
    subcategory: 'oil',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    densityGPerMl: 0.92,
  },
  {
    name: 'truffle oil',
    category: 'fat',
    subcategory: 'oil',
    defaultUnit: 'g',
    allergens: [],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    densityGPerMl: 0.92,
  },
  {
    name: 'flaxseed oil',
    category: 'fat',
    subcategory: 'oil',
    defaultUnit: 'g',
    allergens: [],
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    densityGPerMl: 0.93,
  },
  {
    name: 'hemp seeds',
    category: 'fat',
    subcategory: 'seed',
    defaultUnit: 'g',
    allergens: [],
    calories: 553,
    protein: 32,
    carbs: 9,
    fat: 49,
    fiber: 4,
  },
  {
    name: 'poppy seeds',
    category: 'spice',
    subcategory: 'seed spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 525,
    protein: 18,
    carbs: 28,
    fat: 42,
    fiber: 19,
  },
  {
    name: 'macadamia nuts',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 718,
    protein: 8,
    carbs: 14,
    fat: 76,
    fiber: 8.6,
  },
  {
    name: 'brazil nuts',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 656,
    protein: 14,
    carbs: 12,
    fat: 66,
    fiber: 7.5,
  },
  {
    name: 'hazelnuts',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 628,
    protein: 15,
    carbs: 17,
    fat: 61,
    fiber: 9.7,
  },
  {
    name: 'pecan',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 691,
    protein: 9,
    carbs: 14,
    fat: 72,
    fiber: 9.6,
  },
  {
    name: 'pistachio',
    category: 'fat',
    subcategory: 'nut',
    defaultUnit: 'g',
    allergens: ['nuts'],
    calories: 560,
    protein: 20,
    carbs: 28,
    fat: 45,
    fiber: 10,
  },

  // ============================================
  // SPICES & SEASONINGS (18)
  // ============================================
  {
    name: 'smoked paprika',
    category: 'spice',
    subcategory: 'chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 282,
    protein: 14,
    carbs: 54,
    fat: 13,
    fiber: 35,
  },
  {
    name: 'onion powder',
    category: 'spice',
    subcategory: 'dried vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 341,
    protein: 10.4,
    carbs: 79,
    fat: 1.1,
    fiber: 15,
  },
  {
    name: 'garlic powder',
    category: 'spice',
    subcategory: 'dried vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 331,
    protein: 17,
    carbs: 73,
    fat: 0.7,
    fiber: 9,
  },
  {
    name: 'celery salt',
    category: 'spice',
    subcategory: 'salt blend',
    defaultUnit: 'g',
    allergens: [],
    calories: 15,
    protein: 1,
    carbs: 2,
    fat: 0.3,
    fiber: 1,
  },
  {
    name: 'white pepper',
    category: 'spice',
    subcategory: 'pepper',
    defaultUnit: 'g',
    allergens: [],
    calories: 296,
    protein: 10.4,
    carbs: 69,
    fat: 2.1,
    fiber: 26,
  },
  {
    name: 'szechuan peppercorn',
    category: 'spice',
    subcategory: 'pepper',
    defaultUnit: 'g',
    allergens: [],
    calories: 296,
    protein: 10,
    carbs: 64,
    fat: 3.3,
    fiber: 26,
  },
  {
    name: 'pink peppercorn',
    category: 'spice',
    subcategory: 'pepper',
    defaultUnit: 'g',
    allergens: [],
    calories: 296,
    protein: 6,
    carbs: 70,
    fat: 3,
    fiber: 20,
  },
  {
    name: 'ground coriander',
    category: 'spice',
    subcategory: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 298,
    protein: 12,
    carbs: 55,
    fat: 18,
    fiber: 42,
  },
  {
    name: 'ground ginger',
    category: 'spice',
    subcategory: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 335,
    protein: 9,
    carbs: 72,
    fat: 4.2,
    fiber: 14,
  },
  {
    name: 'anise seed',
    category: 'spice',
    subcategory: 'seed spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 337,
    protein: 17.6,
    carbs: 50,
    fat: 16,
    fiber: 15,
  },
  {
    name: 'juniper berry',
    category: 'spice',
    subcategory: 'spice',
    defaultUnit: 'g',
    allergens: [],
    calories: 10,
    protein: 0.4,
    carbs: 2,
    fat: 0.1,
    fiber: 1,
  },
  {
    name: 'vanilla bean',
    category: 'spice',
    subcategory: 'spice',
    defaultUnit: 'piece',
    allergens: [],
    calories: 288,
    protein: 0.1,
    carbs: 13,
    fat: 0.1,
    fiber: 0,
    gramsPerPiece: 5,
  },
  {
    name: 'old bay seasoning',
    category: 'spice',
    subcategory: 'spice blend',
    defaultUnit: 'g',
    allergens: [],
    calories: 233,
    protein: 8,
    carbs: 46,
    fat: 5,
    fiber: 12,
  },
  {
    name: 'five spice powder',
    category: 'spice',
    subcategory: 'spice blend',
    defaultUnit: 'g',
    allergens: [],
    calories: 340,
    protein: 7,
    carbs: 63,
    fat: 8,
    fiber: 15,
  },
  {
    name: 'berbere',
    category: 'spice',
    subcategory: 'spice blend',
    defaultUnit: 'g',
    allergens: [],
    calories: 280,
    protein: 10,
    carbs: 50,
    fat: 6,
    fiber: 20,
  },
  {
    name: 'togarashi',
    category: 'spice',
    subcategory: 'spice blend',
    defaultUnit: 'g',
    allergens: ['sesame'],
    calories: 300,
    protein: 12,
    carbs: 50,
    fat: 8,
    fiber: 20,
  },
  {
    name: 'dried thyme',
    category: 'spice',
    subcategory: 'dried herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 276,
    protein: 9.1,
    carbs: 64,
    fat: 7.4,
    fiber: 37,
  },
  {
    name: 'dried rosemary',
    category: 'spice',
    subcategory: 'dried herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 331,
    protein: 4.9,
    carbs: 64,
    fat: 15,
    fiber: 43,
  },

  // ============================================
  // LEGUMES (8)
  // ============================================
  {
    name: 'lima beans',
    category: 'legume',
    subcategory: 'bean',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 115,
    protein: 7.8,
    carbs: 21,
    fat: 0.4,
    fiber: 7,
  },
  {
    name: 'great northern beans',
    category: 'legume',
    subcategory: 'bean',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 339,
    protein: 21,
    carbs: 62,
    fat: 1.1,
    fiber: 17,
  },
  {
    name: 'cranberry beans',
    category: 'legume',
    subcategory: 'bean',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 335,
    protein: 23,
    carbs: 60,
    fat: 1.2,
    fiber: 25,
  },
  {
    name: 'pigeon peas',
    category: 'legume',
    subcategory: 'pea',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 343,
    protein: 22,
    carbs: 63,
    fat: 1.5,
    fiber: 15,
  },
  {
    name: 'black-eyed peas',
    category: 'legume',
    subcategory: 'pea',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 336,
    protein: 24,
    carbs: 60,
    fat: 1.3,
    fiber: 11,
  },
  {
    name: 'french green lentils',
    category: 'legume',
    subcategory: 'lentil',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 352,
    protein: 25,
    carbs: 60,
    fat: 1.1,
    fiber: 31,
  },
  {
    name: 'yellow lentils',
    category: 'legume',
    subcategory: 'lentil',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 352,
    protein: 25,
    carbs: 63,
    fat: 1.1,
    fiber: 11,
  },
  {
    name: 'lupini beans',
    category: 'legume',
    subcategory: 'bean',
    proteinType: 'legume',
    defaultUnit: 'g',
    allergens: [],
    calories: 371,
    protein: 36,
    carbs: 40,
    fat: 10,
    fiber: 19,
  },

  // ============================================
  // CARBS - Grains & Pasta (10)
  // ============================================
  {
    name: 'amaranth',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: [],
    calories: 371,
    protein: 14,
    carbs: 65,
    fat: 7,
    fiber: 6.7,
  },
  {
    name: 'teff',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: [],
    calories: 367,
    protein: 13,
    carbs: 73,
    fat: 2.4,
    fiber: 8,
  },
  {
    name: 'spelt',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 338,
    protein: 15,
    carbs: 70,
    fat: 2.4,
    fiber: 11,
  },
  {
    name: 'kamut',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 337,
    protein: 15,
    carbs: 68,
    fat: 2.2,
    fiber: 11,
  },
  {
    name: 'wheat berries',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 339,
    protein: 13.7,
    carbs: 72,
    fat: 1.9,
    fiber: 12.2,
  },
  {
    name: 'pappardelle',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten', 'eggs'],
    calories: 371,
    protein: 14,
    carbs: 72,
    fat: 3,
    fiber: 2.5,
  },
  {
    name: 'rigatoni',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 371,
    protein: 13,
    carbs: 75,
    fat: 1.5,
    fiber: 3,
  },
  {
    name: 'macaroni',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 371,
    protein: 13,
    carbs: 75,
    fat: 1.5,
    fiber: 3,
  },
  {
    name: 'vermicelli',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 371,
    protein: 13,
    carbs: 75,
    fat: 1.5,
    fiber: 3,
  },
  {
    name: 'farfalle',
    category: 'carb',
    subcategory: 'pasta',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 371,
    protein: 13,
    carbs: 75,
    fat: 1.5,
    fiber: 3,
  },

  // ============================================
  // CARBS - Breads & Wraps (6)
  // ============================================
  {
    name: 'flour tortilla',
    category: 'carb',
    subcategory: 'flatbread',
    defaultUnit: 'piece',
    allergens: ['gluten'],
    calories: 312,
    protein: 8,
    carbs: 52,
    fat: 8,
    fiber: 2.1,
    gramsPerPiece: 45,
  },
  {
    name: 'corn tortilla',
    category: 'carb',
    subcategory: 'flatbread',
    defaultUnit: 'piece',
    allergens: [],
    calories: 218,
    protein: 5.7,
    carbs: 45,
    fat: 2.8,
    fiber: 5.3,
    gramsPerPiece: 30,
  },
  {
    name: 'lavash',
    category: 'carb',
    subcategory: 'flatbread',
    defaultUnit: 'piece',
    allergens: ['gluten'],
    calories: 275,
    protein: 10,
    carbs: 50,
    fat: 3.5,
    fiber: 2,
    gramsPerPiece: 70,
  },
  {
    name: 'pumpernickel bread',
    category: 'carb',
    subcategory: 'bread',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 250,
    protein: 8.7,
    carbs: 47,
    fat: 3.1,
    fiber: 6.5,
  },
  {
    name: 'challah bread',
    category: 'carb',
    subcategory: 'bread',
    defaultUnit: 'g',
    allergens: ['gluten', 'eggs'],
    calories: 283,
    protein: 9,
    carbs: 50,
    fat: 5,
    fiber: 1.5,
  },
  {
    name: 'matzo',
    category: 'carb',
    subcategory: 'bread',
    defaultUnit: 'piece',
    allergens: ['gluten'],
    calories: 395,
    protein: 10,
    carbs: 84,
    fat: 1.4,
    fiber: 3,
    gramsPerPiece: 30,
  },

  // ============================================
  // MISC PANTRY (8)
  // ============================================
  {
    name: 'coconut aminos',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: [],
    calories: 100,
    protein: 0,
    carbs: 20,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.1,
  },
  {
    name: 'liquid smoke',
    category: 'condiment',
    subcategory: 'flavoring',
    defaultUnit: 'g',
    allergens: [],
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'msg',
    category: 'spice',
    subcategory: 'seasoning',
    defaultUnit: 'g',
    allergens: [],
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'dashi powder',
    category: 'condiment',
    subcategory: 'broth base',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 176,
    protein: 20,
    carbs: 24,
    fat: 0.5,
    fiber: 0,
  },
  {
    name: 'agar agar',
    category: 'condiment',
    subcategory: 'thickener',
    defaultUnit: 'g',
    allergens: [],
    calories: 306,
    protein: 6,
    carbs: 81,
    fat: 0.3,
    fiber: 8,
  },
  {
    name: 'pectin',
    category: 'condiment',
    subcategory: 'thickener',
    defaultUnit: 'g',
    allergens: [],
    calories: 325,
    protein: 0.3,
    carbs: 90,
    fat: 0.1,
    fiber: 0,
  },
  {
    name: 'arrowroot powder',
    category: 'carb',
    subcategory: 'starch',
    defaultUnit: 'g',
    allergens: [],
    calories: 357,
    protein: 0.3,
    carbs: 88,
    fat: 0.1,
    fiber: 3.4,
  },
  {
    name: 'xanthan gum',
    category: 'condiment',
    subcategory: 'thickener',
    defaultUnit: 'g',
    allergens: [],
    calories: 333,
    protein: 0,
    carbs: 83,
    fat: 0,
    fiber: 83,
  },

  // ============================================
  // ADDITIONAL PRODUCE (12)
  // ============================================
  {
    name: 'kabocha squash',
    category: 'vegetable',
    subcategory: 'squash',
    defaultUnit: 'g',
    allergens: [],
    calories: 34,
    protein: 1.1,
    carbs: 8,
    fat: 0.1,
    fiber: 2.8,
  },
  {
    name: 'pattypan squash',
    category: 'vegetable',
    subcategory: 'squash',
    defaultUnit: 'g',
    allergens: [],
    calories: 18,
    protein: 1.2,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
  },
  {
    name: 'cubanelle pepper',
    category: 'vegetable',
    subcategory: 'pepper',
    defaultUnit: 'g',
    allergens: [],
    calories: 20,
    protein: 0.9,
    carbs: 4.3,
    fat: 0.1,
    fiber: 0.9,
  },
  {
    name: 'scotch bonnet pepper',
    category: 'vegetable',
    subcategory: 'pepper',
    defaultUnit: 'g',
    allergens: [],
    calories: 40,
    protein: 1.9,
    carbs: 9,
    fat: 0.4,
    fiber: 1.5,
  },
  {
    name: 'fresno pepper',
    category: 'vegetable',
    subcategory: 'pepper',
    defaultUnit: 'g',
    allergens: [],
    calories: 40,
    protein: 1.9,
    carbs: 9,
    fat: 0.4,
    fiber: 1.5,
  },
  {
    name: 'rainbow chard',
    category: 'vegetable',
    subcategory: 'leafy green',
    defaultUnit: 'g',
    allergens: [],
    calories: 19,
    protein: 1.8,
    carbs: 3.7,
    fat: 0.2,
    fiber: 1.6,
  },
  {
    name: 'dandelion greens',
    category: 'vegetable',
    subcategory: 'leafy green',
    defaultUnit: 'g',
    allergens: [],
    calories: 45,
    protein: 2.7,
    carbs: 9.2,
    fat: 0.7,
    fiber: 3.5,
  },
  {
    name: 'garlic scapes',
    category: 'vegetable',
    subcategory: 'allium',
    defaultUnit: 'g',
    allergens: [],
    calories: 44,
    protein: 2,
    carbs: 10,
    fat: 0.1,
    fiber: 1,
  },
  {
    name: 'banana blossom',
    category: 'vegetable',
    subcategory: 'tropical vegetable',
    defaultUnit: 'g',
    allergens: [],
    calories: 51,
    protein: 1.6,
    carbs: 10,
    fat: 0.6,
    fiber: 5.7,
  },
  {
    name: 'calabaza squash',
    category: 'vegetable',
    subcategory: 'squash',
    defaultUnit: 'g',
    allergens: [],
    calories: 19,
    protein: 0.8,
    carbs: 4.5,
    fat: 0.1,
    fiber: 1.7,
  },
  {
    name: 'cassava',
    category: 'carb',
    subcategory: 'root',
    defaultUnit: 'g',
    allergens: [],
    calories: 160,
    protein: 1.4,
    carbs: 38,
    fat: 0.3,
    fiber: 1.8,
  },
  {
    name: 'breadfruit',
    category: 'carb',
    subcategory: 'tropical starch',
    defaultUnit: 'g',
    allergens: [],
    calories: 103,
    protein: 1.1,
    carbs: 27,
    fat: 0.2,
    fiber: 4.9,
  },

  // ============================================
  // ADDITIONAL PROTEINS (8)
  // ============================================
  {
    name: 'elk',
    category: 'protein',
    subcategory: 'game',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 137,
    protein: 22.8,
    carbs: 0,
    fat: 4.8,
    fiber: 0,
  },
  {
    name: 'duck leg',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 217,
    protein: 17,
    carbs: 0,
    fat: 16,
    fiber: 0,
  },
  {
    name: 'goose',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 305,
    protein: 25,
    carbs: 0,
    fat: 22,
    fiber: 0,
  },
  {
    name: 'quail',
    category: 'protein',
    subcategory: 'poultry',
    proteinType: 'poultry',
    defaultUnit: 'g',
    allergens: [],
    calories: 192,
    protein: 25,
    carbs: 0,
    fat: 10,
    fiber: 0,
  },
  {
    name: 'lamb rack',
    category: 'protein',
    subcategory: 'lamb',
    proteinType: 'lamb',
    defaultUnit: 'g',
    allergens: [],
    calories: 260,
    protein: 21,
    carbs: 0,
    fat: 19,
    fiber: 0,
  },
  {
    name: 'beef tongue',
    category: 'protein',
    subcategory: 'offal',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 224,
    protein: 16,
    carbs: 3,
    fat: 16,
    fiber: 0,
  },
  {
    name: 'bone broth',
    category: 'protein',
    subcategory: 'broth',
    proteinType: 'beef',
    defaultUnit: 'g',
    allergens: [],
    calories: 17,
    protein: 3.5,
    carbs: 0.5,
    fat: 0.2,
    fiber: 0,
    densityGPerMl: 1.0,
  },
  {
    name: 'smoked trout',
    category: 'protein',
    subcategory: 'fish',
    proteinType: 'fish',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 117,
    protein: 20,
    carbs: 0,
    fat: 3.7,
    fiber: 0,
  },

  // ============================================
  // ADDITIONAL CONDIMENTS & SAUCES (10)
  // ============================================
  {
    name: 'fish sauce thai',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 35,
    protein: 5,
    carbs: 3.6,
    fat: 0,
    fiber: 0,
    densityGPerMl: 1.15,
  },
  {
    name: 'pesto',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['dairy', 'nuts'],
    calories: 330,
    protein: 5,
    carbs: 4,
    fat: 33,
    fiber: 1,
    densityGPerMl: 1.05,
  },
  {
    name: 'chimichurri',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: [],
    calories: 140,
    protein: 1,
    carbs: 3,
    fat: 14,
    fiber: 1,
    densityGPerMl: 0.95,
  },
  {
    name: 'gochugaru',
    category: 'spice',
    subcategory: 'chili',
    defaultUnit: 'g',
    allergens: [],
    calories: 282,
    protein: 12,
    carbs: 50,
    fat: 8,
    fiber: 28,
  },
  {
    name: 'ssamjang',
    category: 'condiment',
    subcategory: 'paste',
    defaultUnit: 'g',
    allergens: ['soy', 'gluten'],
    calories: 195,
    protein: 8,
    carbs: 27,
    fat: 6,
    fiber: 4,
    densityGPerMl: 1.1,
  },
  {
    name: 'mango chutney',
    category: 'condiment',
    subcategory: 'chutney',
    defaultUnit: 'g',
    allergens: [],
    calories: 210,
    protein: 0.5,
    carbs: 52,
    fat: 0.2,
    fiber: 0.5,
    densityGPerMl: 1.15,
  },
  {
    name: 'mint chutney',
    category: 'condiment',
    subcategory: 'chutney',
    defaultUnit: 'g',
    allergens: [],
    calories: 45,
    protein: 1.5,
    carbs: 8,
    fat: 1,
    fiber: 2,
    densityGPerMl: 1.0,
  },
  {
    name: 'cranberry sauce',
    category: 'condiment',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: [],
    calories: 151,
    protein: 0.1,
    carbs: 39,
    fat: 0.1,
    fiber: 0.7,
    densityGPerMl: 1.1,
  },
  {
    name: 'pickled ginger',
    category: 'condiment',
    subcategory: 'pickle',
    defaultUnit: 'g',
    allergens: [],
    calories: 20,
    protein: 0.2,
    carbs: 4.5,
    fat: 0,
    fiber: 0.5,
  },
  {
    name: 'kimchi',
    category: 'condiment',
    subcategory: 'fermented',
    defaultUnit: 'g',
    allergens: ['fish'],
    calories: 15,
    protein: 1.1,
    carbs: 2.4,
    fat: 0.5,
    fiber: 1.6,
  },

  // ============================================
  // ADDITIONAL DAIRY (6)
  // ============================================
  {
    name: 'clotted cream',
    category: 'dairy',
    subcategory: 'cream',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 586,
    protein: 1.6,
    carbs: 2.3,
    fat: 63,
    fiber: 0,
    densityGPerMl: 0.95,
  },
  {
    name: 'double cream',
    category: 'dairy',
    subcategory: 'cream',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 449,
    protein: 1.6,
    carbs: 2.6,
    fat: 48,
    fiber: 0,
    densityGPerMl: 0.98,
  },
  {
    name: 'neufchatel cheese',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 253,
    protein: 10,
    carbs: 3,
    fat: 22,
    fiber: 0,
  },
  {
    name: 'asiago',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 392,
    protein: 32,
    carbs: 0,
    fat: 29,
    fiber: 0,
  },
  {
    name: 'emmental',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 380,
    protein: 29,
    carbs: 0,
    fat: 29,
    fiber: 0,
  },
  {
    name: 'stilton',
    category: 'dairy',
    subcategory: 'cheese',
    proteinType: 'dairy',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 410,
    protein: 24,
    carbs: 0,
    fat: 35,
    fiber: 0,
  },

  // ============================================
  // ADDITIONAL CARBS & GRAINS (8)
  // ============================================
  {
    name: 'sorghum',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: [],
    calories: 329,
    protein: 11,
    carbs: 72,
    fat: 3.3,
    fiber: 6.3,
  },
  {
    name: 'steel cut oats',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 379,
    protein: 13,
    carbs: 68,
    fat: 6.5,
    fiber: 10,
  },
  {
    name: 'rolled oats',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 379,
    protein: 13,
    carbs: 68,
    fat: 6.5,
    fiber: 10,
  },
  {
    name: 'instant oats',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 379,
    protein: 13,
    carbs: 68,
    fat: 6.5,
    fiber: 10,
  },
  {
    name: 'corn meal',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: [],
    calories: 362,
    protein: 8.1,
    carbs: 77,
    fat: 3.6,
    fiber: 7.3,
  },
  {
    name: 'rice bran',
    category: 'carb',
    subcategory: 'bran',
    defaultUnit: 'g',
    allergens: [],
    calories: 316,
    protein: 13,
    carbs: 50,
    fat: 21,
    fiber: 21,
  },
  {
    name: 'wheat germ',
    category: 'carb',
    subcategory: 'grain',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 360,
    protein: 23,
    carbs: 52,
    fat: 10,
    fiber: 13,
  },
  {
    name: 'oat bran',
    category: 'carb',
    subcategory: 'bran',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 246,
    protein: 17,
    carbs: 66,
    fat: 7,
    fiber: 15,
  },

  // ============================================
  // INDIAN - Flours, Spices & Condiments (7)
  // ============================================
  {
    name: 'kasuri methi',
    category: 'spice',
    subcategory: 'dried herb',
    defaultUnit: 'g',
    allergens: [],
    calories: 323,
    protein: 23,
    carbs: 58,
    fat: 6,
    fiber: 25,
  },
  {
    name: 'tandoori masala',
    category: 'spice',
    subcategory: 'spice blend',
    defaultUnit: 'g',
    allergens: [],
    calories: 250,
    protein: 10,
    carbs: 45,
    fat: 5,
    fiber: 15,
  },
  {
    name: 'chaat masala',
    category: 'spice',
    subcategory: 'spice blend',
    defaultUnit: 'g',
    allergens: [],
    calories: 230,
    protein: 8,
    carbs: 42,
    fat: 4,
    fiber: 10,
  },
  {
    name: 'chapati flour',
    category: 'carb',
    subcategory: 'flour',
    defaultUnit: 'g',
    allergens: ['gluten'],
    calories: 340,
    protein: 12,
    carbs: 72,
    fat: 1.5,
    fiber: 11,
  },
  {
    name: 'papadum',
    category: 'carb',
    subcategory: 'flatbread',
    defaultUnit: 'piece',
    allergens: ['gluten'],
    calories: 371,
    protein: 25,
    carbs: 53,
    fat: 6,
    fiber: 15,
    gramsPerPiece: 10,
  },
  {
    name: 'Indian pickle',
    category: 'condiment',
    subcategory: 'pickle',
    defaultUnit: 'g',
    allergens: [],
    calories: 150,
    protein: 2,
    carbs: 10,
    fat: 12,
    fiber: 3,
  },
  {
    name: 'raita',
    category: 'dairy',
    subcategory: 'sauce',
    defaultUnit: 'g',
    allergens: ['dairy'],
    calories: 55,
    protein: 3,
    carbs: 5,
    fat: 2.5,
    fiber: 0.5,
  },
]
