import type { Metadata } from 'next'
import { getTranslations } from 'next-intl/server'
import Link from 'next/link'
import { Body, Heading, Li, Ul } from '@/components/ui/typography'
import {
  LEGAL_ENTITY_ADDRESS,
  LEGAL_ENTITY_NAME,
  LEGAL_ENTITY_REGISTRY_CODE,
  SUPPORT_EMAIL,
  SUPPORT_EMAIL_HREF,
} from '@/lib/support'

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations('meta.legal.terms')
  return {
    title: t('title'),
    description: t('description'),
  }
}

/**
 * Bump alongside CURRENT_TERMS_VERSION (src/lib/consent.ts) on any material
 * change — this is the user-visible anchor for consent versioning.
 */
const LAST_UPDATED = '3 June 2026'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10 flex flex-col gap-3">
      <Heading variant="h2">{title}</Heading>
      {children}
    </section>
  )
}

export default function TermsPage() {
  return (
    <>
      <div className="flex flex-col gap-4">
        <Heading>Terms of service</Heading>
        <Body variant="muted">Last updated: {LAST_UPDATED}</Body>
        <Body variant="lead">
          These terms govern your use of Wobblepot. By creating an account you agree to them and to
          the{' '}
          <Link className="underline" href="/privacy">
            privacy policy
          </Link>
          .
        </Body>
      </div>

      <Section title="The short version">
        <Ul>
          <Li>
            <Body>Wobblepot plans meals for your household with the help of AI.</Body>
          </Li>
          <Li>
            <Body>
              AI suggestions can be wrong — always verify ingredients and allergens yourself.
            </Body>
          </Li>
          <Li>
            <Body>Use the service normally and lawfully, and it is yours to enjoy.</Body>
          </Li>
          <Li>
            <Body>You can delete your account whenever you like.</Body>
          </Li>
        </Ul>
      </Section>

      <Section title="The service">
        <Body>
          Wobblepot is an AI-powered family meal planning app operated by {LEGAL_ENTITY_NAME}{' '}
          (registry code {LEGAL_ENTITY_REGISTRY_CODE}, {LEGAL_ENTITY_ADDRESS}). It generates weekly
          meal plans, swap suggestions, preparation tips, and shopping lists based on your
          household&apos;s preferences, allergens, and pantry. The service is currently in beta:
          features may change, and availability is not guaranteed.
        </Body>
      </Section>

      <Section title="Your account">
        <Body>
          You must be at least 16 years old to create an account. Keep your password secure — you
          are responsible for activity on your account. Provide accurate information, and keep your
          household member data honest: it drives what the AI plans for your family.
        </Body>
      </Section>

      <Section title="Acceptable use">
        <Body>You agree not to:</Body>
        <Ul>
          <Li>
            <Body>break the law or infringe others&apos; rights while using the service,</Body>
          </Li>
          <Li>
            <Body>
              probe, overload, or disrupt the service, or access it by automated means outside the
              features we provide,
            </Body>
          </Li>
          <Li>
            <Body>attempt to access other households&apos; data, or</Body>
          </Li>
          <Li>
            <Body>resell or white-label the service without our written agreement.</Body>
          </Li>
        </Ul>
      </Section>

      <Section title="AI-generated content">
        <Body>
          Meal plans, recipes, swap suggestions, preparation tips, and nutrition values are
          generated by AI and are estimates for guidance only — they are not medical, nutritional,
          or allergy advice. AI output can contain errors, including about allergens.{' '}
          <strong>
            Always verify ingredient labels and consult a healthcare professional for dietary
            decisions
          </strong>
          , especially where allergies or medical conditions are involved.
        </Body>
      </Section>

      <Section title="Termination">
        <Body>
          You can delete your account at any time from the app; your data is then purged within 30
          days as described in the{' '}
          <Link className="underline" href="/privacy">
            privacy policy
          </Link>
          . We may suspend or terminate accounts that violate these terms, after warning you where
          reasonable. We may discontinue the service with reasonable notice — in beta, that notice
          may be short.
        </Body>
      </Section>

      <Section title="Liability">
        <Body>
          The service is provided &ldquo;as is&rdquo;, without warranties of any kind to the extent
          the law allows. To the maximum extent permitted by law, {LEGAL_ENTITY_NAME}&apos;s total
          liability for claims arising from the service is limited to the amount you paid us in the
          12 months before the claim. Nothing in these terms limits liability that cannot be limited
          by law, including under mandatory consumer protection rules of your country of residence.
        </Body>
      </Section>

      <Section title="Governing law">
        <Body>
          These terms are governed by the laws of Estonia. Disputes belong to the courts of Estonia,
          except where mandatory consumer law lets you litigate at home.
        </Body>
      </Section>

      <Section title="Changes to these terms">
        <Body>
          When these terms change materially, we update the date at the top and bump the version
          users accept at sign-up. If the changes affect you significantly, we will ask you to
          review and accept them again.
        </Body>
      </Section>

      <Section title="Contact">
        <Body>
          Questions about these terms:{' '}
          <a className="underline" href={SUPPORT_EMAIL_HREF}>
            {SUPPORT_EMAIL}
          </a>
        </Body>
      </Section>
    </>
  )
}
