/**
 * Every imagine output from the first live model benchmark (HON-859,
 * `scripts/model-bench/results/2026-10-01-claude-sonnet-4-6-vs-claude-sonnet-5-5.md`),
 * reduced to what `findViolations` reads: the meal name and the ingredient
 * names. The raw run file is not committed, so the outputs are kept here.
 *
 * `claude-sonnet-4-6` ignored the household in the shellfish, fish and vegan
 * cases (HON-895); `claude-sonnet-5-5` honoured it in every run. The
 * forbidden-food tests assert both: the 4.6 violations are caught, and none of
 * the 5.5 meals is dropped.
 */

export interface RecordedMeal {
  name: string
  ingredients: string[]
}

export interface RecordedRun {
  caseId: string
  model: 'claude-sonnet-4-6' | 'claude-sonnet-5-5'
  run: number
  meals: RecordedMeal[]
}

export const HON_859_IMAGINE_RUNS: RecordedRun[] = [
  {
    caseId: 'en-chicken-rice-weeknight',
    model: 'claude-sonnet-4-6',
    run: 1,
    meals: [
      {
        name: 'Creamy Garlic Chicken and Rice',
        ingredients: [
          'chicken thigh',
          'white rice',
          'garlic',
          'onion',
          'chicken stock',
          'heavy cream',
          'butter',
          'thyme',
          'salt',
          'black pepper',
        ],
      },
      {
        name: 'Japanese-Style Chicken and Egg Rice Bowl (Oyakodon)',
        ingredients: [
          'chicken breast',
          'white rice',
          'egg',
          'onion',
          'soy sauce',
          'mirin',
          'sugar',
          'chicken stock',
          'chives',
        ],
      },
      {
        name: 'One-Pot Chicken, Vegetable and Rice Soup',
        ingredients: [
          'chicken thigh',
          'white rice',
          'carrot',
          'celery',
          'onion',
          'garlic',
          'chicken stock',
          'olive oil',
          'thyme',
          'parsley',
          'salt',
          'black pepper',
        ],
      },
    ],
  },
  {
    caseId: 'en-chicken-rice-weeknight',
    model: 'claude-sonnet-4-6',
    run: 2,
    meals: [
      {
        name: 'Creamy Garlic Chicken and Rice Bake',
        ingredients: [
          'chicken thigh',
          'long grain rice',
          'chicken stock',
          'sour cream',
          'garlic',
          'onion',
          'olive oil',
          'thyme',
          'salt',
          'black pepper',
        ],
      },
      {
        name: 'Chicken and Vegetable Congee',
        ingredients: [
          'chicken breast',
          'jasmine rice',
          'chicken stock',
          'ginger',
          'garlic',
          'spring onion',
          'carrot',
          'soy sauce',
          'sesame oil',
          'salt',
        ],
      },
      {
        name: 'Spanish-Style Chicken and Chorizo Rice',
        ingredients: [
          'chicken thigh',
          'chorizo',
          'long grain rice',
          'canned tomato',
          'chicken stock',
          'red bell pepper',
          'onion',
          'garlic',
          'smoked paprika',
          'olive oil',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-chicken-rice-weeknight',
    model: 'claude-sonnet-4-6',
    run: 3,
    meals: [
      {
        name: 'Creamy Garlic Chicken and Rice Bake',
        ingredients: [
          'chicken thigh',
          'long grain rice',
          'chicken stock',
          'sour cream',
          'garlic',
          'onion',
          'olive oil',
          'thyme',
          'salt',
          'black pepper',
        ],
      },
      {
        name: 'Chinese-Style Ginger Chicken Congee',
        ingredients: [
          'chicken breast',
          'jasmine rice',
          'chicken stock',
          'ginger',
          'garlic',
          'spring onion',
          'sesame oil',
          'soy sauce',
          'salt',
        ],
      },
      {
        name: 'Spanish-Style Chicken and Rice (Arroz con Pollo)',
        ingredients: [
          'chicken thigh',
          'long grain rice',
          'chicken stock',
          'tomato',
          'red bell pepper',
          'onion',
          'garlic',
          'smoked paprika',
          'olive oil',
          'salt',
          'black pepper',
        ],
      },
    ],
  },
  {
    caseId: 'en-chicken-rice-weeknight',
    model: 'claude-sonnet-5-5',
    run: 1,
    meals: [
      {
        name: 'Creamy Chicken and Rice Soup',
        ingredients: [
          'chicken breast',
          'rice',
          'onion',
          'carrot',
          'celery',
          'garlic',
          'chicken stock',
          'butter',
          'cream',
          'thyme',
          'salt',
        ],
      },
      {
        name: 'One-Pot Baked Chicken and Rice with Peas',
        ingredients: [
          'chicken thigh',
          'rice',
          'chicken stock',
          'onion',
          'garlic',
          'pea',
          'olive oil',
          'paprika',
          'garlic powder',
          'pepper',
        ],
      },
      {
        name: 'Lemon Chicken and Rice Skillet with Broccoli',
        ingredients: [
          'chicken breast',
          'rice',
          'broccoli',
          'lemon',
          'chicken stock',
          'onion',
          'garlic',
          'olive oil',
          'parmesan',
          'oregano',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-chicken-rice-weeknight',
    model: 'claude-sonnet-5-5',
    run: 2,
    meals: [
      {
        name: 'One-Pot Creamy Chicken and Rice Casserole',
        ingredients: [
          'chicken thigh',
          'rice',
          'onion',
          'garlic',
          'carrot',
          'pea',
          'chicken stock',
          'cream',
          'cheddar cheese',
          'thyme',
          'olive oil',
          'salt',
        ],
      },
      {
        name: 'Chicken and Rice Soup with Lemon and Herbs',
        ingredients: [
          'chicken breast',
          'rice',
          'chicken stock',
          'carrot',
          'celery',
          'onion',
          'garlic',
          'lemon',
          'parsley',
          'olive oil',
          'black pepper',
        ],
      },
      {
        name: 'Baked Chicken Thighs with Tomato Rice',
        ingredients: [
          'chicken thigh',
          'rice',
          'tomato passata',
          'chicken stock',
          'red bell pepper',
          'onion',
          'garlic',
          'smoked paprika',
          'oregano',
          'olive oil',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-chicken-rice-weeknight',
    model: 'claude-sonnet-5-5',
    run: 3,
    meals: [
      {
        name: 'Creamy Chicken and Rice Soup',
        ingredients: [
          'chicken breast',
          'rice',
          'carrot',
          'celery',
          'onion',
          'garlic',
          'chicken stock',
          'cream',
          'butter',
          'thyme',
          'salt',
        ],
      },
      {
        name: 'One-Pot Baked Chicken and Rice with Peas',
        ingredients: [
          'chicken thigh',
          'rice',
          'chicken stock',
          'onion',
          'garlic',
          'pea',
          'olive oil',
          'paprika',
          'oregano',
          'black pepper',
        ],
      },
      {
        name: 'Chicken Teriyaki Rice Bowls with Broccoli',
        ingredients: [
          'chicken breast',
          'rice',
          'broccoli',
          'soy sauce',
          'honey',
          'garlic',
          'ginger',
          'vegetable oil',
          'cornstarch',
          'sesame seed',
        ],
      },
    ],
  },
  {
    caseId: 'en-nut-allergy-noodles',
    model: 'claude-sonnet-4-6',
    run: 1,
    meals: [
      {
        name: 'Thai Satay Noodle Stir-Fry with Chicken',
        ingredients: [
          'chicken breast',
          'rice noodle',
          'sunflower seed butter',
          'coconut milk',
          'soy sauce',
          'lime juice',
          'garlic',
          'ginger',
          'red bell pepper',
          'carrot',
          'spring onion',
          'sesame oil',
          'olive oil',
          'honey',
          'coriander',
        ],
      },
      {
        name: 'Thai Satay Tofu & Vegetable Noodle Bowl',
        ingredients: [
          'firm tofu',
          'egg noodle',
          'sunflower seed butter',
          'coconut milk',
          'soy sauce',
          'lime juice',
          'garlic',
          'ginger',
          'broccoli',
          'sugar snap pea',
          'red bell pepper',
          'sesame oil',
          'vegetable oil',
          'honey',
          'sesame seed',
        ],
      },
      {
        name: 'Thai Satay Beef & Rice Noodle Stir-Fry',
        ingredients: [
          'beef sirloin',
          'rice noodle',
          'sunflower seed butter',
          'coconut milk',
          'soy sauce',
          'lime juice',
          'garlic',
          'ginger',
          'courgette',
          'bean sprout',
          'spring onion',
          'sesame oil',
          'vegetable oil',
          'brown sugar',
          'coriander',
        ],
      },
    ],
  },
  {
    caseId: 'en-nut-allergy-noodles',
    model: 'claude-sonnet-4-6',
    run: 2,
    meals: [
      {
        name: 'Thai Satay Noodle Stir-Fry with Chicken',
        ingredients: [
          'chicken breast',
          'rice noodle',
          'red bell pepper',
          'carrot',
          'broccolini',
          'sunflower seed butter',
          'soy sauce',
          'coconut milk',
          'lime',
          'garlic',
          'ginger',
          'sesame oil',
          'vegetable oil',
          'honey',
          'chives',
        ],
      },
      {
        name: 'Thai Satay Tofu Noodle Bowl',
        ingredients: [
          'firm tofu',
          'egg noodle',
          'snap pea',
          'cabbage',
          'spring onion',
          'sunflower seed butter',
          'coconut milk',
          'soy sauce',
          'rice vinegar',
          'garlic',
          'ginger',
          'sesame oil',
          'vegetable oil',
          'lime',
        ],
      },
      {
        name: 'Thai Satay Beef Noodle Stir-Fry with Pak Choi',
        ingredients: [
          'beef sirloin',
          'udon noodle',
          'pak choi',
          'mushroom',
          'sunflower seed butter',
          'coconut milk',
          'soy sauce',
          'oyster sauce',
          'garlic',
          'ginger',
          'sesame oil',
          'vegetable oil',
          'lime',
          'coriander',
        ],
      },
    ],
  },
  {
    caseId: 'en-nut-allergy-noodles',
    model: 'claude-sonnet-4-6',
    run: 3,
    meals: [
      {
        name: 'Thai Satay Noodle Stir-Fry with Chicken and Vegetables',
        ingredients: [
          'chicken breast',
          'rice noodle',
          'sunflower seed butter',
          'coconut milk',
          'soy sauce',
          'lime juice',
          'garlic',
          'ginger',
          'red bell pepper',
          'carrot',
          'spring onion',
          'sesame oil',
          'brown sugar',
          'coriander',
        ],
      },
      {
        name: 'Thai Satay Tofu and Broccoli Noodle Bowl',
        ingredients: [
          'firm tofu',
          'egg noodle',
          'broccoli',
          'sunflower seed butter',
          'coconut milk',
          'soy sauce',
          'lemongrass',
          'garlic',
          'ginger',
          'lime juice',
          'honey',
          'vegetable oil',
          'sesame seed',
        ],
      },
      {
        name: 'Thai Satay Prawn Noodle Stir-Fry with Snap Peas',
        ingredients: [
          'prawn',
          'rice vermicelli',
          'sugar snap pea',
          'sunflower seed butter',
          'coconut milk',
          'soy sauce',
          'garlic',
          'ginger',
          'turmeric',
          'lime juice',
          'fish sauce',
          'vegetable oil',
          'spring onion',
        ],
      },
    ],
  },
  {
    caseId: 'en-nut-allergy-noodles',
    model: 'claude-sonnet-5-5',
    run: 1,
    meals: [
      {
        name: 'Nut-Free Chicken Satay Noodle Stir-Fry',
        ingredients: [
          'rice noodle',
          'chicken breast',
          'sunflower seed butter',
          'soy sauce',
          'chicken broth',
          'brown sugar',
          'lime',
          'red bell pepper',
          'broccoli',
          'carrot',
          'garlic',
          'ginger',
          'vegetable oil',
          'cilantro',
        ],
      },
      {
        name: 'Beef Satay Udon Stir-Fry',
        ingredients: [
          'udon noodle',
          'beef sirloin',
          'sunflower seed butter',
          'soy sauce',
          'honey',
          'sweet chili sauce',
          'beef broth',
          'snap pea',
          'mushroom',
          'onion',
          'garlic',
          'vegetable oil',
          'lime',
        ],
      },
      {
        name: 'Crispy Tofu Veggie Satay Noodles',
        ingredients: [
          'egg noodle',
          'firm tofu',
          'sunflower seed butter',
          'soy sauce',
          'rice vinegar',
          'maple syrup',
          'vegetable broth',
          'cabbage',
          'carrot',
          'yellow bell pepper',
          'garlic',
          'ginger',
          'paprika',
          'vegetable oil',
          'green onion',
        ],
      },
    ],
  },
  {
    caseId: 'en-nut-allergy-noodles',
    model: 'claude-sonnet-5-5',
    run: 2,
    meals: [
      {
        name: 'Chicken Satay Rice Noodle Stir-Fry',
        ingredients: [
          'chicken breast',
          'rice noodle',
          'broccoli',
          'carrot',
          'red bell pepper',
          'garlic',
          'ginger',
          'sunflower seed butter',
          'soy sauce',
          'honey',
          'lime juice',
          'water',
          'paprika',
          'vegetable oil',
          'cilantro',
        ],
      },
      {
        name: 'Beef and Cabbage Satay Noodle Stir-Fry',
        ingredients: [
          'beef sirloin',
          'egg noodle',
          'green bean',
          'cabbage',
          'onion',
          'garlic',
          'sunflower seed butter',
          'soy sauce',
          'brown sugar',
          'rice vinegar',
          'red curry paste',
          'water',
          'vegetable oil',
        ],
      },
      {
        name: 'Crispy Tofu and Mushroom Satay Noodles',
        ingredients: [
          'firm tofu',
          'cornstarch',
          'rice noodle',
          'mushroom',
          'snap pea',
          'spinach',
          'garlic',
          'ginger',
          'sunflower seed butter',
          'soy sauce',
          'maple syrup',
          'lime juice',
          'turmeric',
          'water',
          'vegetable oil',
          'green onion',
        ],
      },
    ],
  },
  {
    caseId: 'en-nut-allergy-noodles',
    model: 'claude-sonnet-5-5',
    run: 3,
    meals: [
      {
        name: 'Chicken Satay Rice Noodle Stir-Fry (Nut-Free)',
        ingredients: [
          'chicken breast',
          'rice noodle',
          'sunflower seed butter',
          'soy sauce',
          'lime juice',
          'honey',
          'water',
          'garlic',
          'ginger',
          'red bell pepper',
          'broccoli',
          'carrot',
          'green onion',
          'vegetable oil',
        ],
      },
      {
        name: 'Beef Satay Egg Noodle Stir-Fry',
        ingredients: [
          'beef sirloin',
          'egg noodle',
          'sunflower seed butter',
          'soy sauce',
          'brown sugar',
          'curry powder',
          'water',
          'garlic',
          'ginger',
          'cabbage',
          'carrot',
          'onion',
          'cilantro',
          'vegetable oil',
        ],
      },
      {
        name: 'Crispy Tofu Satay Udon Stir-Fry',
        ingredients: [
          'firm tofu',
          'udon noodle',
          'sunflower seed butter',
          'soy sauce',
          'rice vinegar',
          'maple syrup',
          'water',
          'garlic',
          'ginger',
          'snap pea',
          'mushroom',
          'red bell pepper',
          'green onion',
          'vegetable oil',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-shellfish-allergy-paella',
    model: 'claude-sonnet-4-6',
    run: 1,
    meals: [
      {
        name: 'Classic Spanish Seafood Paella',
        ingredients: [
          'rice',
          'shrimp',
          'mussel',
          'squid',
          'tomato',
          'red bell pepper',
          'onion',
          'garlic',
          'chicken broth',
          'saffron',
          'smoked paprika',
          'olive oil',
          'lemon',
          'parsley',
          'salt',
        ],
      },
      {
        name: 'Mediterranean Grilled Seafood Rice Bowl',
        ingredients: [
          'rice',
          'shrimp',
          'cod fillet',
          'zucchini',
          'cherry tomato',
          'garlic',
          'olive oil',
          'saffron',
          'smoked paprika',
          'lemon',
          'basil',
          'salt',
        ],
      },
      {
        name: 'Seafood Fideuà with Aioli',
        ingredients: [
          'vermicelli',
          'shrimp',
          'squid',
          'tomato',
          'onion',
          'garlic',
          'fish broth',
          'smoked paprika',
          'saffron',
          'olive oil',
          'egg',
          'lemon',
          'parsley',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-shellfish-allergy-paella',
    model: 'claude-sonnet-4-6',
    run: 2,
    meals: [
      {
        name: 'Classic Spanish Seafood Paella',
        ingredients: [
          'paella rice',
          'mussel',
          'prawn',
          'squid',
          'olive oil',
          'onion',
          'garlic',
          'red bell pepper',
          'tomato',
          'smoked paprika',
          'saffron',
          'white wine',
          'chicken stock',
          'lemon',
          'parsley',
          'salt',
        ],
      },
      {
        name: 'Garlic Butter Prawn & Rice Skillet',
        ingredients: [
          'prawn',
          'long grain rice',
          'butter',
          'olive oil',
          'garlic',
          'cherry tomato',
          'spinach',
          'lemon',
          'chili flake',
          'parsley',
          'salt',
        ],
      },
      {
        name: 'Mediterranean Baked Salmon with Roasted Vegetables & Couscous',
        ingredients: [
          'salmon fillet',
          'couscous',
          'zucchini',
          'red bell pepper',
          'red onion',
          'cherry tomato',
          'olive oil',
          'garlic',
          'oregano',
          'lemon',
          'vegetable stock',
          'basil',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-shellfish-allergy-paella',
    model: 'claude-sonnet-4-6',
    run: 3,
    meals: [
      {
        name: 'Classic Spanish Seafood Paella',
        ingredients: [
          'paella rice',
          'shrimp',
          'mussel',
          'squid',
          'red bell pepper',
          'tomato',
          'onion',
          'garlic',
          'fish stock',
          'white wine',
          'saffron',
          'smoked paprika',
          'olive oil',
          'lemon',
          'parsley',
          'salt',
        ],
      },
      {
        name: 'Grilled Garlic Butter Shrimp with Saffron Rice',
        ingredients: [
          'shrimp',
          'long grain rice',
          'cherry tomato',
          'garlic',
          'butter',
          'olive oil',
          'lemon',
          'saffron',
          'chicken stock',
          'parsley',
          'chili flake',
          'salt',
        ],
      },
      {
        name: 'Spanish-Style Baked Fish with Tomatoes and Peppers',
        ingredients: [
          'white fish fillet',
          'tomato',
          'red bell pepper',
          'onion',
          'garlic',
          'olive',
          'caper',
          'olive oil',
          'smoked paprika',
          'white wine',
          'bread',
          'parsley',
          'lemon',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-shellfish-allergy-paella',
    model: 'claude-sonnet-5-5',
    run: 1,
    meals: [
      {
        name: 'Golden Cod and Pea Skillet Paella',
        ingredients: [
          'cod',
          'rice',
          'chicken broth',
          'red bell pepper',
          'pea',
          'onion',
          'garlic',
          'tomato',
          'olive oil',
          'smoked paprika',
          'saffron',
          'lemon',
          'parsley',
          'salt',
        ],
      },
      {
        name: 'Oven-Baked Salmon and Green Bean Paella',
        ingredients: [
          'salmon',
          'rice',
          'vegetable broth',
          'green bean',
          'cherry tomato',
          'onion',
          'garlic',
          'olive oil',
          'smoked paprika',
          'turmeric',
          'lemon',
          'salt',
          'black pepper',
        ],
      },
      {
        name: 'Paella-Style Tuna Rice Salad',
        ingredients: [
          'rice',
          'tuna',
          'red bell pepper',
          'cucumber',
          'cherry tomato',
          'pea',
          'red onion',
          'olive oil',
          'red wine vinegar',
          'lemon',
          'smoked paprika',
          'saffron',
          'parsley',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-shellfish-allergy-paella',
    model: 'claude-sonnet-5-5',
    run: 2,
    meals: [
      {
        name: 'Cod and Pea Summer Paella',
        ingredients: [
          'cod',
          'paella rice',
          'vegetable broth',
          'onion',
          'garlic',
          'red bell pepper',
          'pea',
          'tomato',
          'olive oil',
          'smoked paprika',
          'saffron',
          'lemon',
          'parsley',
          'salt',
        ],
      },
      {
        name: 'One-Pan Salmon and Asparagus Paella-Style Rice',
        ingredients: [
          'salmon',
          'rice',
          'vegetable broth',
          'onion',
          'garlic',
          'asparagus',
          'zucchini',
          'olive oil',
          'turmeric',
          'paprika',
          'lemon',
          'dill',
          'salt',
          'black pepper',
        ],
      },
      {
        name: 'Oven-Baked Haddock and Tomato Rice',
        ingredients: [
          'haddock',
          'rice',
          'tomato',
          'vegetable broth',
          'green bean',
          'onion',
          'garlic',
          'olive oil',
          'smoked paprika',
          'oregano',
          'lemon',
          'parsley',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-shellfish-allergy-paella',
    model: 'claude-sonnet-5-5',
    run: 3,
    meals: [
      {
        name: 'Classic Cod and Pea Summer Paella',
        ingredients: [
          'cod',
          'short-grain rice',
          'onion',
          'red bell pepper',
          'garlic',
          'tomato',
          'pea',
          'vegetable broth',
          'saffron',
          'smoked paprika',
          'olive oil',
          'lemon',
          'parsley',
          'salt',
        ],
      },
      {
        name: 'Salmon and Green Bean Paella Skillet',
        ingredients: [
          'salmon',
          'short-grain rice',
          'green bean',
          'cherry tomato',
          'onion',
          'garlic',
          'vegetable broth',
          'smoked paprika',
          'turmeric',
          'olive oil',
          'lemon',
          'salt',
          'black pepper',
        ],
      },
      {
        name: 'Oven-Baked Haddock and Summer Vegetable Paella',
        ingredients: [
          'haddock',
          'short-grain rice',
          'zucchini',
          'yellow bell pepper',
          'onion',
          'garlic',
          'tomato',
          'vegetable broth',
          'saffron',
          'smoked paprika',
          'oregano',
          'olive oil',
          'lemon',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-vegan-creamy-pasta',
    model: 'claude-sonnet-4-6',
    run: 1,
    meals: [
      {
        name: 'Creamy Vegan Carbonara with Smoked Tofu and Cashew Sauce',
        ingredients: [
          'spaghetti',
          'smoked tofu',
          'cashew',
          'nutritional yeast',
          'garlic',
          'olive oil',
          'lemon juice',
          'black pepper',
          'salt',
          'chives',
        ],
      },
      {
        name: 'Vegan Rigatoni al Forno with Cashew Béchamel and Roasted Garlic',
        ingredients: [
          'rigatoni',
          'cashew',
          'garlic',
          'oat milk',
          'nutritional yeast',
          'olive oil',
          'breadcrumb',
          'nutmeg',
          'salt',
          'black pepper',
          'parsley',
        ],
      },
      {
        name: 'Creamy Lemon and Asparagus Linguine with Vegan Parmesan',
        ingredients: [
          'linguine',
          'asparagus',
          'coconut cream',
          'lemon',
          'garlic',
          'caper',
          'nutritional yeast',
          'olive oil',
          'black pepper',
          'salt',
          'basil',
        ],
      },
    ],
  },
  {
    caseId: 'en-vegan-creamy-pasta',
    model: 'claude-sonnet-4-6',
    run: 2,
    meals: [
      {
        name: 'Vegan Creamy Carbonara-Style Pasta',
        ingredients: [
          'spaghetti',
          'silken tofu',
          'nutritional yeast',
          'tempeh',
          'olive oil',
          'garlic',
          'soy sauce',
          'smoked paprika',
          'black pepper',
          'salt',
        ],
      },
      {
        name: 'Creamy Cashew Penne with Roasted Garlic and Sun-Dried Tomato',
        ingredients: [
          'penne',
          'cashew',
          'sun-dried tomato',
          'garlic',
          'olive oil',
          'lemon juice',
          'nutritional yeast',
          'basil',
          'black pepper',
          'salt',
        ],
      },
      {
        name: 'Creamy Mushroom and Leek Fettuccine',
        ingredients: [
          'fettuccine',
          'mushroom',
          'leek',
          'oat cream',
          'white wine',
          'garlic',
          'olive oil',
          'nutritional yeast',
          'thyme',
          'black pepper',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-vegan-creamy-pasta',
    model: 'claude-sonnet-4-6',
    run: 3,
    meals: [
      {
        name: 'Vegan Smoky Carbonara-Style Pasta',
        ingredients: [
          'spaghetti',
          'tempeh',
          'cashew',
          'nutritional yeast',
          'garlic',
          'soy sauce',
          'smoked paprika',
          'olive oil',
          'black pepper',
          'salt',
        ],
      },
      {
        name: 'Creamy Vegan Mac and Cheese with Roasted Garlic',
        ingredients: [
          'macaroni',
          'butternut squash',
          'cashew',
          'nutritional yeast',
          'garlic',
          'onion',
          'plant-based milk',
          'dijon mustard',
          'olive oil',
          'salt',
          'black pepper',
        ],
      },
      {
        name: 'Creamy Vegan Mushroom and Thyme Fettuccine Alfredo',
        ingredients: [
          'fettuccine',
          'mushroom',
          'cashew',
          'nutritional yeast',
          'garlic',
          'plant-based milk',
          'thyme',
          'lemon juice',
          'olive oil',
          'chives',
          'salt',
          'black pepper',
        ],
      },
    ],
  },
  {
    caseId: 'en-vegan-creamy-pasta',
    model: 'claude-sonnet-5-5',
    run: 1,
    meals: [
      {
        name: 'Vegan Smoky Tofu Carbonara',
        ingredients: [
          'spaghetti',
          'smoked tofu',
          'cashew',
          'nutritional yeast',
          'garlic',
          'olive oil',
          'soy sauce',
          'lemon juice',
          'parsley',
          'black pepper',
          'salt',
        ],
      },
      {
        name: 'Creamy Garlic Mushroom Fettuccine Alfredo',
        ingredients: [
          'fettuccine',
          'mushroom',
          'oat cream',
          'nutritional yeast',
          'vegan butter',
          'garlic',
          'parsley',
          'black pepper',
          'salt',
        ],
      },
      {
        name: 'Silky Potato-Cheddar Shells with Broccoli',
        ingredients: [
          'pasta shell',
          'potato',
          'carrot',
          'broccoli',
          'onion',
          'garlic',
          'nutritional yeast',
          'soy milk',
          'olive oil',
          'mustard',
          'paprika',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-vegan-creamy-pasta',
    model: 'claude-sonnet-5-5',
    run: 2,
    meals: [
      {
        name: 'Vegan Smoky Tofu Carbonara',
        ingredients: [
          'spaghetti',
          'smoked tofu',
          'cashew',
          'plant milk',
          'nutritional yeast',
          'garlic',
          'olive oil',
          'soy sauce',
          'turmeric',
          'lemon juice',
          'black pepper',
          'salt',
        ],
      },
      {
        name: 'Creamy Garlic Mushroom Fettuccine Alfredo',
        ingredients: [
          'fettuccine',
          'mushroom',
          'oat cream',
          'vegan butter',
          'nutritional yeast',
          'garlic',
          'parsley',
          'black pepper',
          'salt',
        ],
      },
      {
        name: 'Ultra-Creamy Smoky Vegan Mac and Cheese',
        ingredients: [
          'macaroni',
          'potato',
          'carrot',
          'onion',
          'plant milk',
          'nutritional yeast',
          'garlic',
          'olive oil',
          'mustard',
          'smoked paprika',
          'lemon juice',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'en-vegan-creamy-pasta',
    model: 'claude-sonnet-5-5',
    run: 3,
    meals: [
      {
        name: 'Vegan Smoky Tofu Carbonara',
        ingredients: [
          'spaghetti',
          'smoked tofu',
          'cashew',
          'oat milk',
          'nutritional yeast',
          'garlic',
          'olive oil',
          'lemon juice',
          'black pepper',
          'parsley',
          'salt',
        ],
      },
      {
        name: 'Creamy Mushroom and Pea Fettuccine Alfredo',
        ingredients: [
          'fettuccine',
          'mushroom',
          'pea',
          'vegan butter',
          'flour',
          'oat milk',
          'nutritional yeast',
          'garlic',
          'nutmeg',
          'black pepper',
          'salt',
        ],
      },
      {
        name: 'Cheesy Roasted Red Pepper and White Bean Rigatoni',
        ingredients: [
          'rigatoni',
          'white bean',
          'roasted red pepper',
          'vegan cheese',
          'vegetable broth',
          'garlic',
          'olive oil',
          'smoked paprika',
          'basil',
          'salt',
        ],
      },
    ],
  },
  {
    caseId: 'et-fish-allergy-sushi',
    model: 'claude-sonnet-4-6',
    run: 1,
    meals: [
      {
        name: 'Kalamaki kauss',
        ingredients: [
          'riis',
          'avokaado',
          'kurk',
          'nori',
          'seesamiseemned',
          'sojakaste',
          'sidrunimahl',
          'mesi',
        ],
      },
      {
        name: 'Teriyaki kanakauss',
        ingredients: [
          'kanafilee',
          'riis',
          'brokkoli',
          'sojakaste',
          'mesi',
          'küüslauk',
          'seesamiõli',
          'roheline sibul',
          'taimeõli',
        ],
      },
      {
        name: 'Nori-rullid munaga',
        ingredients: [
          'riis',
          'nori',
          'muna',
          'kurk',
          'riisiäädikas',
          'suhkur',
          'sool',
          'sojakaste',
          'wasabi',
        ],
      },
    ],
  },
  {
    caseId: 'et-fish-allergy-sushi',
    model: 'claude-sonnet-4-6',
    run: 2,
    meals: [
      {
        name: 'Onigiri lõhega',
        ingredients: ['sushiriis', 'lõhefilee', 'sojakaste', 'seesam', 'sool', 'nori'],
      },
      {
        name: 'Sushi kauss',
        ingredients: [
          'sushiriis',
          'riisiäädikas',
          'kurk',
          'avokaado',
          'muna',
          'sojakaste',
          'seesam',
        ],
      },
      {
        name: 'Temaki kanapulgad',
        ingredients: [
          'sushiriis',
          'riisiäädikas',
          'kanafilee',
          'sojakaste',
          'nori',
          'kurk',
          'majonees',
        ],
      },
    ],
  },
  {
    caseId: 'et-fish-allergy-sushi',
    model: 'claude-sonnet-4-6',
    run: 3,
    meals: [
      {
        name: 'Onigiri tuunikalaga',
        ingredients: ['riis', 'tuunikala', 'nori', 'majonees', 'sojakaste', 'sool'],
      },
      {
        name: 'Kauss sushi-riisiga',
        ingredients: [
          'riis',
          'riisiäädikas',
          'avokaado',
          'kurk',
          'muna',
          'sojakaste',
          'seesamiõli',
          'seesam',
        ],
      },
      {
        name: 'Temaki-rullid kanaga',
        ingredients: [
          'kanafilee',
          'riis',
          'riisiäädikas',
          'nori',
          'avokaado',
          'kurk',
          'majonees',
          'sojakaste',
          'sool',
        ],
      },
    ],
  },
  {
    caseId: 'et-fish-allergy-sushi',
    model: 'claude-sonnet-5-5',
    run: 1,
    meals: [
      {
        name: 'Sushikauss munaga',
        ingredients: [
          'sushiriis',
          'riisiäädikas',
          'muna',
          'avokaado',
          'kurk',
          'porgand',
          'sojakaste',
          'seesamiseemned',
          'nori',
          'rapsiõli',
        ],
      },
      {
        name: 'Avokaadomaki',
        ingredients: [
          'sushiriis',
          'riisiäädikas',
          'nori',
          'avokaado',
          'kurk',
          'porgand',
          'kreemjuust',
          'sojakaste',
        ],
      },
      {
        name: 'Teriyaki kanakauss',
        ingredients: [
          'kanafilee',
          'riis',
          'brokkoli',
          'sojakaste',
          'mesi',
          'küüslauk',
          'ingver',
          'rapsiõli',
          'seesamiseemned',
          'nori',
        ],
      },
    ],
  },
  {
    caseId: 'et-fish-allergy-sushi',
    model: 'claude-sonnet-5-5',
    run: 2,
    meals: [
      {
        name: 'Teriyaki kanakauss',
        ingredients: [
          'riis',
          'kanafilee',
          'avokaado',
          'kurk',
          'sojakaste',
          'mesi',
          'riisiäädikas',
          'rapsiõli',
          'seesamiseemned',
        ],
      },
      {
        name: 'Munarull noriga',
        ingredients: ['muna', 'riis', 'nori', 'kurk', 'sojakaste', 'riisiäädikas', 'rapsiõli'],
      },
      {
        name: 'Tofu sushikauss',
        ingredients: [
          'tofu',
          'riis',
          'avokaado',
          'porgand',
          'sojakaste',
          'riisiäädikas',
          'seesamiõli',
          'seesamiseemned',
        ],
      },
    ],
  },
  {
    caseId: 'et-fish-allergy-sushi',
    model: 'claude-sonnet-5-5',
    run: 3,
    meals: [
      {
        name: 'Tofu-sushikauss',
        ingredients: [
          'sushiriis',
          'tofu',
          'avokaado',
          'kurk',
          'nori',
          'sojakaste',
          'riisiäädikas',
          'seesamiseeme',
          'rapsiõli',
        ],
      },
      {
        name: 'Munarull noriga',
        ingredients: ['muna', 'sushiriis', 'nori', 'kurk', 'avokaado', 'sojakaste', 'rapsiõli'],
      },
      {
        name: 'Kana-onigiri kurgisalatiga',
        ingredients: [
          'sushiriis',
          'kanafilee',
          'majonees',
          'sojakaste',
          'nori',
          'kurk',
          'riisiäädikas',
          'rapsiõli',
          'sool',
        ],
      },
    ],
  },
  {
    caseId: 'et-pescatarian-sunday-lunch',
    model: 'claude-sonnet-4-6',
    run: 1,
    meals: [
      {
        name: 'Ahjulõhe sidrunikastmes',
        ingredients: [
          'lõhefilee',
          'sidrun',
          'oliiviõli',
          'küüslauk',
          'till',
          'või',
          'sool',
          'must pipar',
          'kartul',
          'roheline oad',
        ],
      },
      {
        name: 'Ahjutursk tomatikastmes',
        ingredients: [
          'turskafilee',
          'purustatud tomat',
          'sibul',
          'küüslauk',
          'oliiv',
          'kappar',
          'oliiviõli',
          'pune',
          'sool',
          'must pipar',
          'petersell',
        ],
      },
      {
        name: 'Ahju-krevettide ja köögiviljapann',
        ingredients: [
          'krevetid',
          'paprika',
          'suvikõrvits',
          'punane sibul',
          'küüslauk',
          'oliiviõli',
          'sidrun',
          'paprikapulber',
          'sool',
          'must pipar',
          'riis',
        ],
      },
    ],
  },
  {
    caseId: 'et-pescatarian-sunday-lunch',
    model: 'claude-sonnet-4-6',
    run: 2,
    meals: [
      {
        name: 'Ahjulõhe sidrunikaste ja köögiviljadega',
        ingredients: [
          'lõhefileed',
          'kartul',
          'spargelkapsas',
          'sidrun',
          'kappar',
          'oliiviõli',
          'küüslauk',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Ahju-tursk tomatikastmes',
        ingredients: [
          'tursk',
          'purustatud tomat',
          'sibul',
          'küüslauk',
          'kirsstomat',
          'must oliiv',
          'oliiviõli',
          'tüümian',
          'oregano',
          'sool',
          'must pipar',
          'leib',
        ],
      },
      {
        name: 'Ahjupasta lõhe ja spinatiga',
        ingredients: [
          'pasta',
          'lõhefileed',
          'spinat',
          'ricotta',
          'rõõsk koor',
          'parmesan',
          'küüslauk',
          'sidrun',
          'oliiviõli',
          'sool',
          'must pipar',
        ],
      },
    ],
  },
  {
    caseId: 'et-pescatarian-sunday-lunch',
    model: 'claude-sonnet-4-6',
    run: 3,
    meals: [
      {
        name: 'Ahjulõhe sidrunikastmes',
        ingredients: [
          'lõhefilee',
          'kartul',
          'sidrun',
          'või',
          'küüslauk',
          'oliiviõli',
          'till',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Ahtuunikala tomatikastmes',
        ingredients: [
          'tuunikala praad',
          'purustatud tomat',
          'sibul',
          'küüslauk',
          'oliiv',
          'kappar',
          'oliiviõli',
          'basiilik',
          'ciabatta',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Krevetihautis ahjuriisiga',
        ingredients: [
          'krevetid',
          'pikateraline riis',
          'paprika',
          'sibul',
          'küüslauk',
          'purustatud tomat',
          'kana- või köögiviljapuljong',
          'suitsutatud paprikapulber',
          'parmesan',
          'oliiviõli',
          'sool',
          'must pipar',
        ],
      },
    ],
  },
  {
    caseId: 'et-pescatarian-sunday-lunch',
    model: 'claude-sonnet-5-5',
    run: 1,
    meals: [
      {
        name: 'Ahjulõhe sidruni ja tilliga',
        ingredients: [
          'lõhefilee',
          'kartul',
          'spargel',
          'sidrun',
          'till',
          'küüslauk',
          'oliiviõli',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Spinati-juustulasanje',
        ingredients: [
          'lasanjeplaat',
          'spinat',
          'kodujuust',
          'mozzarella',
          'purustatud tomat',
          'sibul',
          'küüslauk',
          'muna',
          'oliiviõli',
          'muskaatpähkel',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Ahjupaprikad riisi ja fetaga',
        ingredients: [
          'paprika',
          'riis',
          'kikerhernes',
          'fetajuust',
          'sibul',
          'küüslauk',
          'tomatipasta',
          'paprikapulber',
          'köögiviljapuljong',
          'petersell',
          'oliiviõli',
          'sool',
        ],
      },
    ],
  },
  {
    caseId: 'et-pescatarian-sunday-lunch',
    model: 'claude-sonnet-5-5',
    run: 2,
    meals: [
      {
        name: 'Ahjulõhe sparglitega',
        ingredients: [
          'lõhefilee',
          'kartul',
          'spargel',
          'sidrun',
          'küüslauk',
          'till',
          'oliiviõli',
          'või',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Spinatilasanje',
        ingredients: [
          'lasanjeplaat',
          'spinat',
          'kodujuust',
          'purustatud tomat',
          'mozzarella',
          'sibul',
          'küüslauk',
          'muna',
          'oliiviõli',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Ahjutursk koorekastmes',
        ingredients: [
          'tursafilee',
          'kartul',
          'sibul',
          'koor',
          'juust',
          'till',
          'või',
          'sool',
          'must pipar',
        ],
      },
    ],
  },
  {
    caseId: 'et-pescatarian-sunday-lunch',
    model: 'claude-sonnet-5-5',
    run: 3,
    meals: [
      {
        name: 'Ahjulõhe sparglitega',
        ingredients: [
          'lõhefilee',
          'kartul',
          'spargel',
          'sidrun',
          'küüslauk',
          'till',
          'oliiviõli',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Spinati-ricotta lasanje',
        ingredients: [
          'lasanjeplaat',
          'spinat',
          'ricotta',
          'purustatud tomat',
          'mozzarella',
          'sibul',
          'küüslauk',
          'oliiviõli',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Täidetud paprikad fetaga',
        ingredients: [
          'paprika',
          'riis',
          'kikerhernes',
          'feta',
          'purustatud tomat',
          'sibul',
          'küüslauk',
          'oregano',
          'petersell',
          'oliiviõli',
          'sool',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegan-sour-cream',
    model: 'claude-sonnet-4-6',
    run: 1,
    meals: [
      {
        name: 'Soe kartulisalat suitsulõhega',
        ingredients: ['kartul', 'suitsulõhe', 'hapukoor', 'sibul', 'till', 'sool', 'must pipar'],
      },
      {
        name: 'Soe kartulisalat räime ja sibulaga',
        ingredients: [
          'kartul',
          'suits-räimefileed',
          'hapukoor',
          'dijoni sinep',
          'punane sibul',
          'murulauk',
          'sool',
        ],
      },
      {
        name: 'Soe kartulisalat suitsumakrelliga',
        ingredients: [
          'kartul',
          'suitsumakrell',
          'hapukoor',
          'muna',
          'sibul',
          'till',
          'sool',
          'must pipar',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegan-sour-cream',
    model: 'claude-sonnet-4-6',
    run: 2,
    meals: [
      {
        name: 'Soe kartulisalat suitsukalaga',
        ingredients: ['kartul', 'suitsukala', 'hapukoor', 'sibul', 'till', 'sool', 'must pipar'],
      },
      {
        name: 'Kartulisalat mädarõika-hapukoorekastmega',
        ingredients: [
          'kartul',
          'suitsukala',
          'hapukoor',
          'mädarõigas',
          'roheline sibul',
          'sidrunimahl',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Kartuli-kalasupp tilliga',
        ingredients: [
          'kartul',
          'suitsukala',
          'hapukoor',
          'sibul',
          'porgand',
          'till',
          'vesi',
          'sool',
          'must pipar',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegan-sour-cream',
    model: 'claude-sonnet-4-6',
    run: 3,
    meals: [
      {
        name: 'Soe kartulisalat suitsulõhega',
        ingredients: ['kartul', 'suitsulõhe', 'hapukoor', 'sibul', 'till', 'sool', 'must pipar'],
      },
      {
        name: 'Kartulisalat suitsuräimega',
        ingredients: [
          'kartul',
          'suitsuräim',
          'hapukoor',
          'punane sibul',
          'kurk',
          'till',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Ahjukartulisalat suitsumakrelliga',
        ingredients: [
          'kartul',
          'suitsumakrell',
          'hapukoor',
          'roheline sibul',
          'oliiviõli',
          'dijoni sinep',
          'sool',
          'must pipar',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegan-sour-cream',
    model: 'claude-sonnet-5-5',
    run: 1,
    meals: [
      {
        name: 'Soe kartulisalat suitsutofuga',
        ingredients: [
          'kartul',
          'suitsutofu',
          'taimne hapukoor',
          'punane sibul',
          'hapukurk',
          'till',
          'sinep',
          'äädikas',
          'rapsiõli',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Ahjukartul hapukoore ja suitsutofuga',
        ingredients: [
          'kartul',
          'suitsutofu',
          'rapsiõli',
          'taimne hapukoor',
          'murulauk',
          'küüslauk',
          'suitsupaprika',
          'sool',
        ],
      },
      {
        name: 'Suitsune kartulisupp',
        ingredients: [
          'kartul',
          'porgand',
          'sibul',
          'suitsutofu',
          'vesi',
          'taimne hapukoor',
          'rapsiõli',
          'loorberileht',
          'till',
          'sool',
          'must pipar',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegan-sour-cream',
    model: 'claude-sonnet-5-5',
    run: 2,
    meals: [
      {
        name: 'Soe kartulisalat suitsutofuga',
        ingredients: [
          'kartul',
          'suitsutofu',
          'taimne hapukoor',
          'sibul',
          'hapukurk',
          'till',
          'rapsiõli',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Kartulisalat suitsuporganditega',
        ingredients: [
          'kartul',
          'porgand',
          'suitsupaprika',
          'sojakaste',
          'oliiviõli',
          'taimne hapukoor',
          'punane sibul',
          'murulauk',
          'sool',
        ],
      },
      {
        name: 'Soe kartuli-seenesalat',
        ingredients: [
          'kartul',
          'austerseen',
          'suitsupaprika',
          'sojakaste',
          'roheline hernes',
          'taimne hapukoor',
          'sibul',
          'petersell',
          'rapsiõli',
          'must pipar',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegan-sour-cream',
    model: 'claude-sonnet-5-5',
    run: 3,
    meals: [
      {
        name: 'Soe kartulisalat suitsutofuga',
        ingredients: [
          'kartul',
          'suitsutofu',
          'taimne hapukoor',
          'sibul',
          'hapukurk',
          'till',
          'rapsiõli',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Ahjukartul hapukoorekastmega',
        ingredients: [
          'kartul',
          'suitsutofu',
          'taimne hapukoor',
          'murulauk',
          'sibul',
          'oliiviõli',
          'suitsupaprika',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Suitsune kartulisupp',
        ingredients: [
          'kartul',
          'porgand',
          'sibul',
          'suitsutofu',
          'köögiviljapuljong',
          'taimne hapukoor',
          'till',
          'rapsiõli',
          'loorberileht',
          'sool',
          'must pipar',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegetarian-lentils',
    model: 'claude-sonnet-4-6',
    run: 1,
    meals: [
      {
        name: 'Läätsepasta tomatikastmes',
        ingredients: [
          'punane lääts',
          'pasta',
          'purustatud tomat',
          'sibul',
          'küüslauk',
          'oliiviõli',
          'parmesan',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Läätsesuppp kookospiimaga',
        ingredients: [
          'punane lääts',
          'kookospiim',
          'köögiviljapuljong',
          'sibul',
          'küüslauk',
          'ingver',
          'karripulber',
          'oliiviõli',
          'sool',
          'leib',
        ],
      },
      {
        name: 'Läätseburgid jogurtikastmega',
        ingredients: [
          'roheline lääts',
          'porgand',
          'sibul',
          'küüslauk',
          'muna',
          'riivsai',
          'köömned',
          'taimeõli',
          'kreeka jogurt',
          'pitaleib',
          'sool',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegetarian-lentils',
    model: 'claude-sonnet-4-6',
    run: 2,
    meals: [
      {
        name: 'Läätsepasta tomatikastmes',
        ingredients: [
          'punane läätse',
          'pasta',
          'purustatud tomat',
          'sibul',
          'küüslauk',
          'oliiviõli',
          'paprikapulber',
          'sool',
        ],
      },
      {
        name: 'Läätsekotletid jogurtikastmega',
        ingredients: [
          'roheline läätse',
          'muna',
          'sibul',
          'küüslauk',
          'riivsai',
          'köömned',
          'taimeõli',
          'jogurt',
          'sool',
        ],
      },
      {
        name: 'Kookospiimane läätsehautis',
        ingredients: [
          'punane läätse',
          'kookospiim',
          'riis',
          'sibul',
          'küüslauk',
          'karripulber',
          'oliiviõli',
          'sool',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegetarian-lentils',
    model: 'claude-sonnet-4-6',
    run: 3,
    meals: [
      {
        name: 'Läätsesupp koorega',
        ingredients: [
          'punane lääts',
          'sibul',
          'küüslauk',
          'tomatipüree',
          'kookospiim',
          'köögiviljapuljong',
          'oliiviõli',
          'köömned',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Läätsepasta tomatikastmes',
        ingredients: [
          'pasta',
          'pruun lääts',
          'purustatud tomat',
          'sibul',
          'küüslauk',
          'oliiviõli',
          'oregano',
          'parmesan',
          'sool',
        ],
      },
      {
        name: 'Läätsekotletid jogurtikastmega',
        ingredients: [
          'punane lääts',
          'sibul',
          'küüslauk',
          'muna',
          'jahu',
          'köömned',
          'paprikapulber',
          'oliiviõli',
          'jogurt',
          'sool',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegetarian-lentils',
    model: 'claude-sonnet-5-5',
    run: 1,
    meals: [
      {
        name: 'Läätsebolognese',
        ingredients: [
          'spagetid',
          'punane lääts',
          'sibul',
          'porgand',
          'küüslauk',
          'purustatud tomat',
          'tomatipüree',
          'vesi',
          'oliiviõli',
          'pune',
          'riivjuust',
          'sool',
        ],
      },
      {
        name: 'Läätse-juustuquesadillad',
        ingredients: [
          'tortilla',
          'punane lääts',
          'paprika',
          'mais',
          'tomatipüree',
          'suitsupaprika',
          'juust',
          'oliiviõli',
          'hapukoor',
          'sool',
        ],
      },
      {
        name: 'Kookosläätsesupp',
        ingredients: [
          'punane lääts',
          'porgand',
          'sibul',
          'küüslauk',
          'köögiviljapuljong',
          'kookospiim',
          'kurkum',
          'oliiviõli',
          'sidrunimahl',
          'leib',
          'sool',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegetarian-lentils',
    model: 'claude-sonnet-5-5',
    run: 2,
    meals: [
      {
        name: 'Läätsabolognese',
        ingredients: [
          'spagetid',
          'punane lääts',
          'sibul',
          'porgand',
          'küüslauk',
          'purustatud tomat',
          'tomatipasta',
          'vesi',
          'oliiviõli',
          'riivjuust',
          'sool',
          'must pipar',
        ],
      },
      {
        name: 'Läätsatortillad',
        ingredients: [
          'tortilla',
          'punane lääts',
          'mais',
          'sibul',
          'küüslauk',
          'tomatipasta',
          'paprikapulber',
          'vesi',
          'kurk',
          'cheddar',
          'hapukoor',
          'oliiviõli',
          'sool',
        ],
      },
      {
        name: 'Õrn läätsekarri riisiga',
        ingredients: [
          'punane lääts',
          'kookospiim',
          'porgand',
          'herned',
          'sibul',
          'küüslauk',
          'karripulber',
          'vesi',
          'riis',
          'oliiviõli',
          'sool',
        ],
      },
    ],
  },
  {
    caseId: 'et-vegetarian-lentils',
    model: 'claude-sonnet-5-5',
    run: 3,
    meals: [
      {
        name: 'Läätsepasta tomatikastmes',
        ingredients: [
          'pasta',
          'punane lääts',
          'purustatud tomat',
          'sibul',
          'porgand',
          'küüslauk',
          'oliiviõli',
          'juust',
          'sool',
        ],
      },
      {
        name: 'Läätsekarri kookospiimaga',
        ingredients: [
          'punane lääts',
          'kookospiim',
          'riis',
          'sibul',
          'porgand',
          'küüslauk',
          'karripulber',
          'päevalilleõli',
          'sool',
        ],
      },
      {
        name: 'Läätse-juustuquesadilla',
        ingredients: [
          'tortilla',
          'lääts',
          'juust',
          'paprika',
          'mais',
          'köömen',
          'suitsupaprika',
          'hapukoor',
          'päevalilleõli',
        ],
      },
    ],
  },
]
