import { NextResponse } from 'next/server'
import { headers } from 'next/headers'
import type { Prisma } from '@/generated/prisma/client'
import { auth } from '@/lib/auth'
import { getHouseholdMembership } from '@/lib/household'
import { prisma } from '@/lib/prisma'
import { serverEnv } from '@/lib/env'
import { checkRateLimit, retryAfterSeconds } from '@/lib/rate-limit'
import {
  AiCostCapExceededError,
  assertUnderCap,
  recordAiUsage,
  respondCapExceeded,
} from '@/lib/ai/usage'
import { isAiBudgetTimeout } from '@/lib/ai/timeout'
import { aiErrorStatusCode } from '@/lib/ai/error-status'
import { captureApiError } from '@/lib/errors'
import { withRequestId } from '@/lib/request-id'
import { generateMealImage, MealImageUnavailableError } from '@/lib/meal-images/generate'
import { MEAL_IMAGE_PROMPT_VERSION } from '@/lib/meal-images/prompt'
import { discardMealImage, putMealImage } from '@/lib/meal-images/storage'

/**
 * POST /api/meals/[id]/image — lazily generate a meal's hero illustration
 * (HON-735), the first time anyone opens a household-owned meal.
 *
 * Responses, all `{ status, imageUrl? }`:
 * - 200 `ready` + `imageUrl` — cached, or generated by this request.
 * - 202 `generating` — another request holds the claim; poll again.
 * - 200 `none` — the meal was edited while this request generated, so the
 *   image was thrown away; the next request draws the edited meal.
 * - 200 `failed` — generation has failed `MAX_ATTEMPTS` times; never retried.
 * - The stored status for a global meal (202 while `generating`), which is
 *   never generated here: an operator batch pays for shared assets (HON-738),
 *   so one household's AI cap is never charged for them.
 */

const ROUTE = '/api/meals/[id]/image'

/** A meal whose image failed this many times is never retried. */
const MAX_ATTEMPTS = 3

/**
 * A `generating` claim older than this belongs to a function that died:
 * `maxDuration` below kills every live one well before it.
 */
const CLAIM_STALE_MS = 3 * 60_000

/**
 * Wall-clock budget for all AI time in this request, in ms: two images and
 * two judge calls in the worst case (~43 s measured), and `generateMealImage`
 * only starts the second image when the budget still has room for it. The
 * remaining 10 s under `maxDuration` covers the Blob upload and the DB writes
 * after it, which is what keeps the 504 below reachable (HON-694, HON-699).
 */
const AI_BUDGET_MS = 50_000

type ImageBody =
  | { status: 'ready'; imageUrl: string }
  | { status: 'none' | 'generating' | 'failed'; error?: string }

const respond = (body: ImageBody, status = 200) => NextResponse.json(body, { status })

/**
 * Write image columns only while this request's claim still holds.
 *
 * `clearMealImage` (HON-734) resets `imageClaimedAt` whenever the meal's
 * content is edited, even mid-generation, and a stale-claim takeover replaces
 * it — so matching on it is how this request notices either.
 *
 * The first attempt also pins `updatedAt` and writes the same value back.
 * Prisma's `@updatedAt` would otherwise move on every image write, and the
 * prep-tips route guards its own cache write on `Meal.updatedAt` (HON-683):
 * the modal opens both at once, so a bump here would silently throw away the
 * freshly generated tips. If some other edit already moved `updatedAt`, the
 * fallback writes normally — rolling it back would re-open that guard.
 */
async function writeUnderClaim(
  mealId: string,
  claimedAt: Date,
  updatedAt: Date,
  data: Prisma.MealUpdateManyMutationInput,
): Promise<boolean> {
  const pinned = await prisma.meal.updateMany({
    where: { id: mealId, imageClaimedAt: claimedAt, updatedAt },
    data: { ...data, updatedAt },
  })
  if (pinned.count > 0) return true

  const moved = await prisma.meal.updateMany({
    where: { id: mealId, imageClaimedAt: claimedAt },
    data,
  })
  return moved.count > 0
}

async function handlePOST(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth.api.getSession({
    headers: await headers(),
  })

  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const membership = await getHouseholdMembership(session.user.id)

  if (!membership) {
    return NextResponse.json({ error: 'No household found' }, { status: 404 })
  }

  const { household } = membership
  const { id: mealId } = await params

  const meal = await prisma.meal.findFirst({
    where: {
      id: mealId,
      deletedAt: null,
      OR: [{ householdId: null }, { householdId: household.id }],
    },
    select: {
      id: true,
      name: true,
      description: true,
      preparationNotes: true,
      householdId: true,
      updatedAt: true,
      imageUrl: true,
      imageStatus: true,
      imageClaimedAt: true,
      imageAttempts: true,
      components: {
        select: {
          quantityPerServing: true,
          ingredient: {
            select: { name: true, defaultUnit: true, gramsPerPiece: true, densityGPerMl: true },
          },
        },
      },
    },
  })

  if (!meal) {
    return NextResponse.json({ error: 'Meal not found' }, { status: 404 })
  }

  if (meal.imageStatus === 'ready' && meal.imageUrl) {
    return respond({ status: 'ready', imageUrl: meal.imageUrl })
  }

  // Global meals are drawn once by the operator batch, never on a household's cap.
  if (meal.householdId === null) {
    const status = meal.imageStatus === 'ready' ? 'none' : meal.imageStatus
    // Same 202 as a household meal mid-generation, so a client polls both alike.
    return respond({ status }, status === 'generating' ? 202 : 200)
  }

  if (meal.imageStatus === 'failed' && meal.imageAttempts >= MAX_ATTEMPTS) {
    return respond({ status: 'failed' })
  }

  // Polls while another request generates must not spend rate-limit tokens.
  // The guarded claim below is what actually settles a race; this only skips
  // the obvious case early.
  const now = new Date()
  const staleBefore = new Date(now.getTime() - CLAIM_STALE_MS)
  if (
    meal.imageStatus === 'generating' &&
    meal.imageClaimedAt !== null &&
    meal.imageClaimedAt >= staleBefore
  ) {
    return respond({ status: 'generating' }, 202)
  }

  if (!serverEnv.OPENAI_API_KEY) {
    return NextResponse.json({ error: 'Meal images are not available' }, { status: 503 })
  }

  const rateLimitResult = await checkRateLimit(household.id, 'meal-image')
  if (!rateLimitResult.allowed) {
    return NextResponse.json(
      {
        error: 'Rate limit exceeded',
        message: `Maximum ${rateLimitResult.limit} meal image requests per hour`,
        resetAt: rateLimitResult.resetAt.toISOString(),
      },
      {
        status: 429,
        headers: { 'Retry-After': String(retryAfterSeconds(rateLimitResult)) },
      },
    )
  }

  try {
    await assertUnderCap(household.id)
  } catch (error) {
    if (error instanceof AiCostCapExceededError) {
      return respondCapExceeded(error)
    }
    throw error
  }

  // Claim before generating, so two households opening the same meal never
  // both pay. Same guarded-`updateMany` idiom as the prep-tips cache write:
  // it matches nothing when another request got there first.
  //
  // `updatedAt` is pinned for two reasons: the content below was read at that
  // version, so an edit since then must not be drawn from the stale read; and
  // writing it back keeps this claim from moving it (see `writeUnderClaim`).
  const claimedAt = now
  const claim = await prisma.meal.updateMany({
    where: {
      id: meal.id,
      deletedAt: null,
      updatedAt: meal.updatedAt,
      OR: [
        { imageStatus: 'none' },
        { imageStatus: 'failed', imageAttempts: { lt: MAX_ATTEMPTS } },
        // A crashed function never releases its claim.
        { imageStatus: 'generating', imageClaimedAt: { lt: staleBefore } },
        { imageStatus: 'generating', imageClaimedAt: null },
      ],
    },
    data: { imageStatus: 'generating', imageClaimedAt: claimedAt, updatedAt: meal.updatedAt },
  })

  // Usually another request won the claim. Rarely the meal was edited since the
  // read above; 202 is still right, because the next poll re-reads and claims.
  if (claim.count === 0) {
    return respond({ status: 'generating' }, 202)
  }

  let uploadedUrl: string | null = null

  try {
    const image = await generateMealImage(
      {
        name: meal.name,
        description: meal.description,
        preparationNotes: meal.preparationNotes,
        components: meal.components.map((c) => ({
          name: c.ingredient.name,
          quantity: c.quantityPerServing,
          unit: c.ingredient.defaultUnit,
          gramsPerPiece: c.ingredient.gramsPerPiece,
          densityGPerMl: c.ingredient.densityGPerMl,
        })),
      },
      {
        abortSignal: AbortSignal.timeout(AI_BUDGET_MS),
        budgetMs: AI_BUDGET_MS,
        mealId: meal.id,
        onUsage: (usage) =>
          recordAiUsage({ householdId: household.id, feature: 'meal_image', ...usage }),
      },
    )

    uploadedUrl = await putMealImage(meal.id, Buffer.from(image.bytes), image.mediaType)

    const attached = await writeUnderClaim(meal.id, claimedAt, meal.updatedAt, {
      imageStatus: 'ready',
      imageUrl: uploadedUrl,
      imagePromptVersion: MEAL_IMAGE_PROMPT_VERSION,
    })

    if (!attached) {
      // The meal was edited (or the claim taken over) while we generated: this
      // image shows the old ingredients, so it must never be attached.
      await discardMealImage(uploadedUrl, ROUTE)
      return respond({ status: 'none' })
    }

    return respond({ status: 'ready', imageUrl: uploadedUrl })
  } catch (error) {
    captureApiError(error, {
      route: ROUTE,
      userId: session.user.id,
      feature: 'meal_image',
      householdId: household.id,
    })

    // Only reached before the image was attached, so an uploaded blob is an orphan.
    await discardMealImage(uploadedUrl, ROUTE)

    const statusCode = aiErrorStatusCode(error)
    // A 429 or a missing key says nothing about this meal, and retrying later
    // succeeds — counting it would lock the meal out after three busy moments.
    // Everything else counts: it was probably billed, or will fail again.
    const transient = statusCode === 429 || error instanceof MealImageUnavailableError

    try {
      await writeUnderClaim(meal.id, claimedAt, meal.updatedAt, {
        imageStatus: 'failed',
        ...(transient ? {} : { imageAttempts: { increment: 1 } }),
      })
    } catch (writeError) {
      // The stale-claim takeover recovers the row; the original error is the one to map.
      captureApiError(writeError, { route: ROUTE, operation: 'meal-image-mark-failed' })
    }

    // Same two-name check as the other AI routes (HON-694).
    if (isAiBudgetTimeout(error)) {
      return respond({ status: 'failed', error: 'Generating the image took too long.' }, 504)
    }

    if (error instanceof MealImageUnavailableError) {
      return respond({ status: 'failed', error: 'Meal images are not available' }, 503)
    }

    if (statusCode === 429) {
      return respond({ status: 'failed', error: 'Image service is busy.' }, 429)
    }
    if (statusCode !== undefined && statusCode >= 500) {
      return respond({ status: 'failed', error: 'Image service unavailable.' }, 502)
    }

    return respond({ status: 'failed', error: "Couldn't generate the image." }, 500)
  }
}

export const POST = withRequestId(handlePOST)

/**
 * Platform execution ceiling for this route, in seconds.
 *
 * Stated explicitly because `AI_BUDGET_MS` is only meaningful if the platform
 * lets the function run that long — otherwise the request is killed first and
 * the friendly 504 above never runs. 60 is the value every Vercel plan allows,
 * so this cannot fail to deploy (HON-693). It is also what makes
 * `CLAIM_STALE_MS` safe: no live request can hold a claim for 3 minutes.
 */
export const maxDuration = 60
