import { NextResponse } from 'next/server'
import { headers } from 'next/headers'
import type { Prisma } from '@/generated/prisma/client'
import { auth } from '@/lib/auth'
import { getHouseholdMembership } from '@/lib/household'
import { prisma } from '@/lib/prisma'
import { serverEnv } from '@/lib/env'
import { checkRateLimit, retryAfterSeconds } from '@/lib/rate-limit'
import {
  AiCostCapExceededError,
  assertUnderCap,
  recordAiUsage,
  respondCapExceeded,
} from '@/lib/ai/usage'
import { isAiBudgetTimeout } from '@/lib/ai/timeout'
import { aiErrorStatusCode } from '@/lib/ai/error-status'
import { captureApiError } from '@/lib/errors'
import { withRequestId } from '@/lib/request-id'
import { extractHue } from '@/lib/meal-images/colour'
import { generateMealImage, MealImageUnavailableError } from '@/lib/meal-images/generate'
import { presentMealImage } from '@/lib/meal-images/present'
import { MEAL_IMAGE_PROMPT_VERSION } from '@/lib/meal-images/prompt'
import { discardMealImage, putMealImage } from '@/lib/meal-images/storage'

/**
 * POST /api/meals/[id]/image — lazily generate a meal's hero illustration
 * (HON-735), the first time anyone opens a household-owned meal.
 *
 * Responses, all `{ status, imageUrl?, imageHue? }`:
 * - 200 `ready` + `imageUrl` + `imageHue` — cached, or generated by this
 *   request. `imageHue` is null when the image carries no colour (HON-744).
 * - 202 `generating` — another request holds the claim; poll again.
 * - 200 `none` — the meal was edited while this request generated, so the
 *   image was thrown away; the next request draws the edited meal.
 * - 200 `failed` — generation has failed `MAX_ATTEMPTS` times; never retried.
 * - 429 `none` — the image provider's rate limit outlasted one short wait;
 *   the claim is released without counting an attempt (HON-742).
 * - A `ready` image at an older prompt version is treated as absent and
 *   redrawn, with its attempts reset (HON-753); the old blob is deleted once
 *   the new one is attached.
 * - The stored status for a global meal (202 while `generating`), which is
 *   never generated here: an operator batch pays for shared assets (HON-738),
 *   so one household's AI cap is never charged for them.
 */

const ROUTE = '/api/meals/[id]/image'

/** A meal whose image failed this many times is never retried. */
const MAX_ATTEMPTS = 3

/**
 * A `generating` claim older than this belongs to a function that died:
 * `maxDuration` below kills every live one well before it.
 */
const CLAIM_STALE_MS = 3 * 60_000

/**
 * Wall-clock budget for all AI time in this request, in ms: two images and
 * two judge calls in the worst case (~43 s measured), and `generateMealImage`
 * only starts the second image when the budget still has room for it. The
 * remaining 10 s under `maxDuration` covers the Blob upload and the DB writes
 * after it, which is what keeps the 504 below reachable (HON-694, HON-699).
 */
const AI_BUDGET_MS = 50_000

/**
 * A provider 429 is waited out at most once here, for at most 15 s: longer,
 * and the image after it no longer fits `AI_BUDGET_MS` (HON-742). A 429 that
 * outlasts it releases the claim instead of failing the meal.
 */
const RATE_LIMIT_RETRIES = 1
const RATE_LIMIT_MAX_WAIT_MS = 15_000

type ImageBody =
  | { status: 'ready'; imageUrl: string; imageHue: number | null }
  | { status: 'none' | 'generating' | 'failed'; error?: string }

const respond = (body: ImageBody, status = 200) => NextResponse.json(body, { status })

/**
 * The meal's card hue from the image bytes (HON-744). A failure is logged and
 * stored as null, never raised: an image that was generated and paid for must
 * not be thrown away over its colour.
 */
async function hueOf(bytes: Uint8Array, mealId: string): Promise<number | null> {
  try {
    return (await extractHue(bytes)).hue
  } catch (error) {
    captureApiError(error, { route: ROUTE, operation: 'meal-image-hue', mealId })
    return null
  }
}

/**
 * Write image columns only while this request's claim still holds.
 *
 * `clearMealImage` (HON-734) resets `imageClaimedAt` whenever the meal's
 * content is edited, even mid-generation, and a stale-claim takeover replaces
 * it — so matching on it is how this request notices either.
 *
 * The first attempt also pins `updatedAt` and writes the same value back.
 * Prisma's `@updatedAt` would otherwise move on every image write, and the
 * prep-tips route guards its own cache write on `Meal.updatedAt` (HON-683):
 * the modal opens both at once, so a bump here would silently throw away the
 * freshly generated tips. If some other edit already moved `updatedAt`, the
 * fallback writes normally — rolling it back would re-open that guard.
 */
async function writeUnderClaim(
  mealId: string,
  claimedAt: Date,
  updatedAt: Date,
  data: Prisma.MealUpdateManyMutationInput,
): Promise<boolean> {
  const pinned = await prisma.meal.updateMany({
    where: { id: mealId, imageClaimedAt: claimedAt, updatedAt },
    data: { ...data, updatedAt },
  })
  if (pinned.count > 0) return true

  const moved = await prisma.meal.updateMany({
    where: { id: mealId, imageClaimedAt: claimedAt },
    data,
  })
  return moved.count > 0
}

async function handlePOST(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth.api.getSession({
    headers: await headers(),
  })

  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const membership = await getHouseholdMembership(session.user.id)

  if (!membership) {
    return NextResponse.json({ error: 'No household found' }, { status: 404 })
  }

  const { household } = membership
  const { id: mealId } = await params

  const meal = await prisma.meal.findFirst({
    where: {
      id: mealId,
      deletedAt: null,
      OR: [{ householdId: null }, { householdId: household.id }],
    },
    select: {
      id: true,
      name: true,
      description: true,
      preparationNotes: true,
      householdId: true,
      updatedAt: true,
      imageUrl: true,
      imageStatus: true,
      imageHue: true,
      imagePromptVersion: true,
      imageClaimedAt: true,
      imageAttempts: true,
      components: {
        select: {
          quantityPerServing: true,
          ingredient: {
            select: { name: true, defaultUnit: true, gramsPerPiece: true, densityGPerMl: true },
          },
        },
      },
    },
  })

  if (!meal) {
    return NextResponse.json({ error: 'Meal not found' }, { status: 404 })
  }

  const presented = presentMealImage(meal)
  if (presented.imageStatus === 'ready' && presented.imageUrl) {
    return respond({ status: 'ready', imageUrl: presented.imageUrl, imageHue: presented.imageHue })
  }

  // Global meals are drawn once by the operator batch, never on a household's cap.
  if (meal.householdId === null) {
    const status = meal.imageStatus === 'ready' ? 'none' : meal.imageStatus
    // Same 202 as a household meal mid-generation, so a client polls both alike.
    return respond({ status }, status === 'generating' ? 202 : 200)
  }

  if (meal.imageStatus === 'failed' && meal.imageAttempts >= MAX_ATTEMPTS) {
    return respond({ status: 'failed' })
  }

  // Polls while another request generates must not spend rate-limit tokens.
  // The guarded claim below is what actually settles a race; this only skips
  // the obvious case early.
  const now = new Date()
  const staleBefore = new Date(now.getTime() - CLAIM_STALE_MS)
  if (
    meal.imageStatus === 'generating' &&
    meal.imageClaimedAt !== null &&
    meal.imageClaimedAt >= staleBefore
  ) {
    return respond({ status: 'generating' }, 202)
  }

  if (!serverEnv.OPENAI_API_KEY) {
    return NextResponse.json({ error: 'Meal images are not available' }, { status: 503 })
  }

  const rateLimitResult = await checkRateLimit(household.id, 'meal-image')
  if (!rateLimitResult.allowed) {
    return NextResponse.json(
      {
        error: 'Rate limit exceeded',
        message: `Maximum ${rateLimitResult.limit} meal image requests per hour`,
        resetAt: rateLimitResult.resetAt.toISOString(),
      },
      {
        status: 429,
        headers: { 'Retry-After': String(retryAfterSeconds(rateLimitResult)) },
      },
    )
  }

  try {
    await assertUnderCap(household.id)
  } catch (error) {
    if (error instanceof AiCostCapExceededError) {
      return respondCapExceeded(error)
    }
    throw error
  }

  // Claim before generating, so two households opening the same meal never
  // both pay. Same guarded-`updateMany` idiom as the prep-tips cache write:
  // it matches nothing when another request got there first.
  //
  // `updatedAt` is pinned for two reasons: the content below was read at that
  // version, so an edit since then must not be drawn from the stale read; and
  // writing it back keeps this claim from moving it (see `writeUnderClaim`).
  //
  // A `ready` row only reaches here at a stale prompt version (HON-753). Its
  // claim pins the version read, and resets the attempts: a new prompt is a
  // new image, owed the full `MAX_ATTEMPTS`.
  const claimedAt = now
  const redraw = meal.imageStatus === 'ready'
  const claim = await prisma.meal.updateMany({
    where: {
      id: meal.id,
      deletedAt: null,
      updatedAt: meal.updatedAt,
      OR: redraw
        ? [{ imageStatus: 'ready', imagePromptVersion: meal.imagePromptVersion }]
        : [
            { imageStatus: 'none' },
            { imageStatus: 'failed', imageAttempts: { lt: MAX_ATTEMPTS } },
            // A crashed function never releases its claim.
            { imageStatus: 'generating', imageClaimedAt: { lt: staleBefore } },
            { imageStatus: 'generating', imageClaimedAt: null },
          ],
    },
    data: {
      imageStatus: 'generating',
      imageClaimedAt: claimedAt,
      updatedAt: meal.updatedAt,
      ...(redraw ? { imageAttempts: 0 } : {}),
    },
  })

  // Usually another request won the claim. Rarely the meal was edited since the
  // read above; 202 is still right, because the client polls the GET, reads the
  // edit's `none`, and POSTs again (`useMealImage`).
  if (claim.count === 0) {
    return respond({ status: 'generating' }, 202)
  }

  let uploadedUrl: string | null = null

  try {
    const image = await generateMealImage(
      {
        name: meal.name,
        description: meal.description,
        preparationNotes: meal.preparationNotes,
        components: meal.components.map((c) => ({
          name: c.ingredient.name,
          quantity: c.quantityPerServing,
          unit: c.ingredient.defaultUnit,
          gramsPerPiece: c.ingredient.gramsPerPiece,
          densityGPerMl: c.ingredient.densityGPerMl,
        })),
      },
      {
        abortSignal: AbortSignal.timeout(AI_BUDGET_MS),
        budgetMs: AI_BUDGET_MS,
        rateLimitRetries: RATE_LIMIT_RETRIES,
        maxRateLimitWaitMs: RATE_LIMIT_MAX_WAIT_MS,
        mealId: meal.id,
        onUsage: (usage) =>
          recordAiUsage({ householdId: household.id, feature: 'meal_image', ...usage }),
      },
    )

    uploadedUrl = await putMealImage(meal.id, Buffer.from(image.bytes), image.mediaType)
    const imageHue = await hueOf(image.bytes, meal.id)

    const attached = await writeUnderClaim(meal.id, claimedAt, meal.updatedAt, {
      imageStatus: 'ready',
      imageUrl: uploadedUrl,
      imagePromptVersion: MEAL_IMAGE_PROMPT_VERSION,
      imageHue,
    })

    if (!attached) {
      // The meal was edited (or the claim taken over) while we generated: this
      // image shows the old ingredients, so it must never be attached.
      await discardMealImage(uploadedUrl, ROUTE)
      return respond({ status: 'none' })
    }

    // The image this one replaced — a stale-version redraw, or a stale claim
    // over one. Deleted only now it is detached, as `clearMealImage` orders it;
    // until then the row still points at it, so a failure orphans nothing.
    if (meal.imageUrl && meal.imageUrl !== uploadedUrl) {
      await discardMealImage(meal.imageUrl, ROUTE)
    }

    return respond({ status: 'ready', imageUrl: uploadedUrl, imageHue })
  } catch (error) {
    captureApiError(error, {
      route: ROUTE,
      userId: session.user.id,
      feature: 'meal_image',
      householdId: household.id,
    })

    // Only reached before the image was attached, so an uploaded blob is an orphan.
    await discardMealImage(uploadedUrl, ROUTE)

    const statusCode = aiErrorStatusCode(error)
    const rateLimited = statusCode === 429
    // A 429 or a missing key says nothing about this meal, and retrying later
    // succeeds — counting it would lock the meal out after three busy moments.
    // Everything else counts: it was probably billed, or will fail again.
    // A 429 goes further and releases the claim to `none`, so the next open
    // simply asks again once the provider's per-minute window clears (HON-742).
    const transient = rateLimited || error instanceof MealImageUnavailableError

    try {
      await writeUnderClaim(
        meal.id,
        claimedAt,
        meal.updatedAt,
        rateLimited
          ? { imageStatus: 'none', imageClaimedAt: null }
          : {
              imageStatus: 'failed',
              ...(transient ? {} : { imageAttempts: { increment: 1 } }),
            },
      )
    } catch (writeError) {
      // The stale-claim takeover recovers the row; the original error is the one to map.
      captureApiError(writeError, { route: ROUTE, operation: 'meal-image-mark-failed' })
    }

    // Same two-name check as the other AI routes (HON-694).
    if (isAiBudgetTimeout(error)) {
      return respond({ status: 'failed', error: 'Generating the image took too long.' }, 504)
    }

    if (error instanceof MealImageUnavailableError) {
      return respond({ status: 'failed', error: 'Meal images are not available' }, 503)
    }

    if (rateLimited) {
      return respond({ status: 'none', error: 'Image service is busy.' }, 429)
    }
    if (statusCode !== undefined && statusCode >= 500) {
      return respond({ status: 'failed', error: 'Image service unavailable.' }, 502)
    }

    return respond({ status: 'failed', error: "Couldn't generate the image." }, 500)
  }
}

export const POST = withRequestId(handlePOST)

/**
 * GET /api/meals/[id]/image — the stored image state, for the meal detail
 * modal to poll while another request holds the claim (HON-737).
 *
 * Read-only on purpose: polling the POST would re-claim a failed or stale row
 * and could start a paid generation from a poll. Same `{ status, imageUrl?, imageHue? }`
 * body as the POST, always 200.
 */
async function handleGET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth.api.getSession({
    headers: await headers(),
  })

  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const membership = await getHouseholdMembership(session.user.id)

  if (!membership) {
    return NextResponse.json({ error: 'No household found' }, { status: 404 })
  }

  const { id: mealId } = await params

  try {
    const meal = await prisma.meal.findFirst({
      where: {
        id: mealId,
        deletedAt: null,
        OR: [{ householdId: null }, { householdId: membership.household.id }],
      },
      select: { imageUrl: true, imageStatus: true, imageHue: true, imagePromptVersion: true },
    })

    if (!meal) {
      return NextResponse.json({ error: 'Meal not found' }, { status: 404 })
    }

    // A stale prompt version reads as `none`, same as every meal payload (HON-753).
    const { imageStatus, imageUrl, imageHue } = presentMealImage(meal)

    if (imageStatus === 'ready' && imageUrl) {
      return respond({ status: 'ready', imageUrl, imageHue })
    }

    return respond({ status: imageStatus === 'ready' ? 'none' : imageStatus })
  } catch (error) {
    captureApiError(error, { route: ROUTE, userId: session.user.id, operation: 'meal-image-read' })
    return NextResponse.json({ error: "Couldn't read the meal image." }, { status: 500 })
  }
}

export const GET = withRequestId(handleGET)

/**
 * Platform execution ceiling for this route, in seconds.
 *
 * Stated explicitly because `AI_BUDGET_MS` is only meaningful if the platform
 * lets the function run that long — otherwise the request is killed first and
 * the friendly 504 above never runs. 60 is the value every Vercel plan allows,
 * so this cannot fail to deploy (HON-693). It is also what makes
 * `CLAIM_STALE_MS` safe: no live request can hold a claim for 3 minutes.
 */
export const maxDuration = 60
