-- HON-696: one household per user, enforced by the schema rather than by
-- `runHouseholdClaim`'s Serializable isolation alone.
--
-- Audited 2026-09-23 on `staging` and `main`: no user holds more than one
-- membership. If this migration fails at deploy time, re-run that audit and
-- resolve the offenders (with the user present) — do not edit this file:
--
--   SELECT "userId", count(*), array_agg("householdId")
--   FROM household_member
--   WHERE "userId" IS NOT NULL
--   GROUP BY "userId" HAVING count(*) > 1;

-- Fail with a pointer to the audit instead of a bare unique-violation.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM "household_member"
    WHERE "userId" IS NOT NULL
    GROUP BY "userId" HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'household_member has users with more than one membership; run the HON-696 audit query and resolve them before applying this migration';
  END IF;
END $$;

-- The unique index serves every lookup the plain one did.
-- DropIndex
DROP INDEX "household_member_userId_idx";

-- CreateIndex
CREATE UNIQUE INDEX "household_member_userId_key" ON "household_member"("userId");

-- Load-bearing assumption: the index is NULLS DISTINCT (PostgreSQL's default),
-- so the manual member rows with no linked user — many per household — stay
-- legal. Assert it rather than trust the default.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_index i
    JOIN pg_class c ON c.oid = i.indexrelid
    WHERE c.relname = 'household_member_userId_key' AND i.indnullsnotdistinct
  ) THEN
    RAISE EXCEPTION 'household_member_userId_key must be NULLS DISTINCT: manual members have a NULL "userId"';
  END IF;
END $$;
